### ISSUE TITLE
pc104 doesn't start in icub-cluster.py

### ISSUE THREAD

**Issue by urielmtz** [robotology/icub-support#100]
Hello,

We updated pc104 to version 5.0-15-10-26 and it replies to the ping, but when we run pc104 with icub-cluster.py its checkbox isn't ticked.

Cheers
Uriel

**Comment by barbalberto** [comment]
Can you please login into pc104 through ssh and check the hostname of the pc104?

**Comment by urielmtz** [comment]
The hostname in /etc/hostname is pc104, is this ok?

Cheers
Uriel

On Thu, Nov 5, 2015 at 8:24 AM, Alberto Cardellino <notifications@github.com
> wrote:

> Can you please login into pc104 through ssh and check the hostname of the
> pc104?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robotology/icub-support/issues/100#issuecomment-153985671>
> .
>



-- 
*Uriel Martinez-Hernandez*
Research Associate
Sheffield Robotics and the Department of Psychology
The University of Sheffield
Mappin Street, Sheffield, S1 3JD, United Kingdom



*Contact*
Mobile phone: (+44) 7 58 20 32 522

*Personal web page*
http://uriel-martinez.wikidot.com

*LinkedIn*
uk.linkedin.com/pub/uriel-martinez-hernandez/39/a48/a17

**Comment by super-ste** [comment]
Hi all, was this issue solved? 
@barbalberto do you have further troubleshooting steps for this?

**Comment by julijenv** [comment]
any news?
@barbalberto , @urielmtz
