### ISSUE TITLE
skin patch of left forearm does not work 

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-support#101]
as per title.

the gui shows a part of the left forearm working and another part not working. all other patches are working fine.

**Comment by marcoaccame** [comment]
Hi @julijenv, this is the problem I talked you about.

**Comment by matejhof** [comment]
This seems to be still the case. The smaller patch on the upper part of the forearm surely did not work yesterday. Cannot remember the other patch, but I think all forearm seemed dead.
Btw., some other skin parts of the purpley had phantom activations - in particular torso and right palm.

**Comment by S-Dafarra** [comment]
Part of the left forearm patch is still not working. Any news on this? cc @julijenv
