### ISSUE TITLE
error in opening driver <xsensmtx> 

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-support#102]
Since yesterday, I have experienced quite often (3 times out of about 20 launches of robotInterface) that robotInterface cannot be launched because of error in opening the driver <xsensmtx>.

I powered off and then on the motors before launching robotInterface. I am however quite sure that I have waited a long enough time (all boards could bootstrap and exit the bootloader phase).

All times I launched a second time and the error did not appear anymore.
 
![xsensmtx-purple](https://cloud.githubusercontent.com/assets/7148284/10940413/73b01150-8306-11e5-8be2-725c42136083.jpg)

**Comment by barbalberto** [comment]
xsensormtx is the IMU device, it is a USB device plugged into the pc104 so it is not affected by motor power off/on. Maybbe the usb connector is not well plugged in

**Comment by marcoaccame** [comment]
thank you @barbalberto, I reported that just because I wanted to give as much information as possible.

Anyway, situation is getting worse and worse. Now it happens about 1 launch of robotInterface every 4, without powering off/on. 

Thus, an intervention is urgently required as @DanielePucci wants to use heavily the robot.

**Comment by super-ste** [comment]
hi all,
what is the status of this?
@DanielePucci, is it there any intervention needed on our side?
cc @julijenv

**Comment by julijenv** [comment]
Did see any other complaint check the wires, but nothing to say about it, @DanielePucci @francesco-romano , did u remove the sensor to didnt get the error message poping up????

**Comment by francesco-romano** [comment]
I had not experienced this for at least one  week.
For me we can close and if it happens again I'll open again.
