### ISSUE TITLE
FT left leg sensor issues (broken?) 

### ISSUE THREAD

**Issue by jeljaik** [robotology/icub-support#107]
There are problems with the left leg FT sensor. Two axes return zero constantly as can be seen in the following graph (top left corner). @julijenv has already checked this personally.

![screenshot from 2015-11-11 17 08 19](https://cloud.githubusercontent.com/assets/5030039/11095874/5e885f3a-8897-11e5-84ef-c90105e588e3.png)

**Comment by super-ste** [comment]
Is this the HIP FT sensor of the ANKLE FT sensor?

**Comment by julijenv** [comment]
it has been replaced the sensor 220 instead of the 209.
Test need to be done to make sure that the issue is close, wait for feedback from @jeljaik .

**Comment by jeljaik** [comment]
So far I haven't seen any strange behavior and force readings seem just fine. Thank you guys.
