### ISSUE TITLE
Left thumb broken

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#109]
The left thumb (probably the joint 9) of the purple iCub doesn't work.

**Comment by pattacini** [comment]
This thumb was operative during Wednesday demo. @massimoregoli reported he found it broken 2 days ago.

May I ask you guys to promptly report such failures in time, without leaving the robot broken after usage? That's an important issue, so I do expect you will take this message quite seriously.

**Comment by spada1978** [comment]
proximal thumb repaired
