### ISSUE TITLE
Error due to AEA of board 6

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#116]
`[ERROR] from BOARD 6, src LOCAL, adr 0, time 1559s 748m 519u: (code 0x02000009, par16 0x0000 par64 0x0000400000000000) -> MC: AEA encoder invalid data + INFO = NO MORE`

@julijenv this error is still occurring

**Comment by DanielePucci** [comment]
It has happened after a reboot of `robotInterface`

**Comment by julijenv** [comment]
has been restored, one wire gotr broken, it should be alright now
