### ISSUE TITLE
Weight of iCubDarmstadt01

### ISSUE THREAD

**Issue by francesco-romano** [robotology/icub-support#118]
30.4 kg without left upper leg cover and skin.

![icub](https://cloud.githubusercontent.com/assets/2189180/11306320/56b45ca2-8fb1-11e5-9485-d2b0e4af602a.png)

@robertocalandra @paraschos @rueckert

**Comment by DanielePucci** [comment]
Guys, @jeljaik @francesco-romano,  please update https://github.com/robotology/icub-support/issues/98#event-470239945 with a little description of the robot's characteristics (i.e. Legs V2, etc). Thanks ;)
