### ISSUE TITLE
AEA left upper arm not responding 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#123]
After an hardware fix on the right thumb by @spada1978 @julijenv, we get the following message at `robotInterface` startup

~~~
[ERROR] from BOARD 10.0.1.1 (leftUpperArm), src LOCAL, adr 0, time 247s 316m 517u: (code 0x02000009, par16 0x0003 par64 0x0000400000000000) -> MC: AEA encoder invalid data + INFO = NO MORE
~~~

@spada1978 @julijenv @super-ste @francesco-romano

**Comment by julijenv** [comment]
Has been restored by @gandini
