### ISSUE TITLE
Torque/CompliantMode not working properly for shoulder joints

### ISSUE THREAD

**Issue by jeljaik** [robotology/icub-support#127]
When launching `demoRedBall`, in particular, the `demoRedBall` module. The arms start shaking as soon as the control mode is switched from position to compliant mode. A similar behavior is reported when switching from `Stiff Mode` to `Compliant Mode` from the `yarpmotorgui` in particular for the `roll joint` of the shoulders.

c.c. @randaz81

**Comment by traversaro** [comment]
Are you running `wholeBodyDynamics` or `wholeBodyDynamicsTree` ? This seems could also be problem of torque feedback.

**Comment by jeljaik** [comment]
For sure `wholeBodyDynamics` when launching the demo. But I am experiencing a shoulders-related issue as well when using `wholeBodyDynamicsTree` and `torqueBalancing`
