### ISSUE TITLE
Fingers tendons broken

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#129]
Joints 11 and 12 of left hand and 8 of right hand are not working. 
12 broke while I was using actionsRenderingEngine to grasp an object. The others are don't know as they were already broken.

**Comment by spada1978** [comment]
I spoke this morning with Vadim and I said there lscia the roboto for necessary maintenance Friday

**Comment by spada1978** [comment]
repaired proximal left hand index for demo this afternoon

**Comment by spada1978** [comment]
adduction repaired right thumb
