### ISSUE TITLE
Tendon number 8 broken left shoulder

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#131]
While doing a YOGA demo, the tendon broke. 

Thanks @julijenv who is already working on that.

**Comment by super-ste** [comment]
Guys, guys
before doing any more YOGA demos or waving arm around in an uncontrolled fashion, let's make sure we troubleshoot and solve the issue #64  

cc @julijenv 
@DanielePucci 
@francesco-romano

**Comment by DanielePucci** [comment]
The point is that we were performing the yoga demo in torque control, so this rules out an eventual PID related problem causing the issue. Probably, the left shoulder of iCubGenova02 requires an inspection from a mechanical perspective for ruling out an hardware problem.

**Comment by francesco-romano** [comment]
Let's close this issue for now.
The tendon has already been replaced.
