### ISSUE TITLE
Changing The texture pattern of the palm in "icubSim" 

### ISSUE THREAD

**Issue by LakshithaHKUST** [robotology/icub-support#135]
Hello,
Is it possible to change the texture pattern in the right or left palm(Simulator)?
To add an arbitrary image from a file?
Thanks

**Comment by pattacini** [comment]
Dear @LakshithaHKUST 

As per our guidelines, [**`icub-support`**](https://github.com/robotology/icub-support/blob/master/CONTRIBUTING.md) is not the right place where to post such a request.

Could you please open a ticket on this in [**`icub-main`**](https://github.com/robotology/icub-main/issues) or [**`Q&A`**](https://github.com/robotology/QA/issues) instead?

Best,
Ugo
