### ISSUE TITLE
Issue with the skin

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-support#136]
It seems that torso, left and right forearms, left and rights palms, left and right hand fingertips are disconnected. Thank you

**Comment by julijenv** [comment]
After the upgrade of the skin and the forearms V2 on the robot, by fault of time, we didnt havce time to check to good functionning of the skin part, as a result some short circuit were present on the different boards.
It has been by the way repaired:
- skin left forearm and palm and fingertips
- skin right palm and fingertips
- cable A of the head tendon was out of place
- skin torso had a one signal wire broken
- mecchanical of the right eye has been tighten BUT it isnt sufficient
- flat cable for the left eye has been changed
