### ISSUE TITLE
Left index not closing on startup

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#139]
Hi,  after the left arm has been repaired and reattached, I noticed that the left index was not closing during the calibration stage. I don't really need it too much, but maybe some people do afterwards, so It'll be nice to get it repaired.

Thanks!

**Comment by vtikha** [comment]
@tanismar please specify which robot you are talking about. Add the tag of the robot name to the issue, and put the name also in the title.

**Comment by pattacini** [comment]
not the robot name in the title :smirk: 
see [**`guidelines`**](https://github.com/robotology/icub-support/blob/master/CONTRIBUTING.md).

**Comment by vtikha** [comment]
I still put it there to please @super-ste :smile:

**Comment by alecive** [comment]
... and me ! :dancer:

**Comment by pattacini** [comment]
I can always :gun: and :bomb: you, but it's :christmas_tree: :santa:

**Comment by super-ste** [comment]
Me thinks okay what  @pattacini  does.
Me thinks stinky :us: should be kept out this repo.

AUGH
![image](https://cloud.githubusercontent.com/assets/8122012/11847799/6e1293e6-a41f-11e5-80fc-b7108f23490f.png)

**Comment by julijenv** [comment]
Has been repaired the day before yesterday by @spada1978
