### ISSUE TITLE
broken shoulder cable

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#140]
Hi, 
doing my tool use experiment, because of a small mistake, I tried to reach a wrong position, and a shoulder cable broke. 

See you after Xmas!!

BEst 
Tanis

**Comment by pattacini** [comment]
Tanis ... please the label!

**Comment by pattacini** [comment]
I think it's Bluey, @tanismar correct me if I'm wrong.

**Comment by spada1978** [comment]
the cables were broken.
They were wiring cables 7 and 8.
