### ISSUE TITLE
metallic structure on right side is ruined

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-support#142]

**Comment by super-ste** [comment]
Pics? Anything more meaningful?

**Comment by super-ste** [comment]
After exhaustive researches, the culprit is found in the following pic.
![image](https://cloud.githubusercontent.com/assets/8122012/11960671/11299f8a-a8d4-11e5-97dc-8fbdc9a494b2.png)


That will be "manually adjusted" once the head is back in production

**Comment by lornat75** [comment]
![thor-chris-hemsworth-la-4-23-13](https://cloud.githubusercontent.com/assets/1403333/11974936/15bd4cb4-a969-11e5-9699-b2b5cae84b8e.jpg)

Please assign this issue to him...

**Comment by julijenv** [comment]
any news on theis isssue?
@valegagge
