### ISSUE TITLE
unreliable external network connectivity

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#15]
@mbrunettini reported problems with external network connectivy. Suspects:

- [ ] broken network board on server
- [x] RJ45 connector on the back of the rack (this happened in the past)

**Comment by lornat75** [comment]
@apaikan

**Comment by mbrunettini** [comment]
Now the rack is connected directly, bypassing the RJ45 on the rack.
This allows to test the network card. Still in testing.

**Comment by mbrunettini** [comment]
The network card has been tested and no problems were found.
Replaced RJ connector.
Issue closed.
