### ISSUE TITLE
Left knee in HW fault (also restarting the robot)

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#151]
The robot fell while in half-sitting position and the left knee went on hw fault, the error was still there even after restarting.

**Comment by julijenv** [comment]
The black wire of the ROIEL was broken and has been repaired, have a good work.
@DanielePucci ,  @jeljaik , @hu-yue

**Comment by jeljaik** [comment]
Merci beaucoup!

**Comment by alecive** [comment]
@jeljaik are you testing your french? :stuck_out_tongue:

**Comment by super-ste** [comment]
I smell yankees in this thread...

Vade Retro!!

(Testing my latin)
