### ISSUE TITLE
Right arm 4DC and/or STRAIN problems

### ISSUE THREAD

**Issue by gsaponaro** [robotology/icub-support#156]
Hi, we have some problems in the right_arm CAN network of our robot (network 2). We verified all the relevant connections and wires. Here is our analysis so far, which likely isolates the problem in the 4DC control board (see third experiment below) and perhaps also in the STRAIN force/torque sensor.

1. With all the boards of this CAN network connected, **canLoader** shows:
![160112_can2_canloader_problem](https://cloud.githubusercontent.com/assets/6716962/12302877/780aa576-ba1f-11e5-8aa5-54625fc5490d.png)

2. We disconnected the BLLs of this CAN network (one at a time, first the bottom then the top), and in both cases **canLoader** again showed problems:
![160113_can2_problem_disconnected_bottom_bll](https://cloud.githubusercontent.com/assets/6716962/12302936/bfdcc03c-ba1f-11e5-9efb-4c8b1214492d.png)
![160113_can2_disconnected_top_bll](https://cloud.githubusercontent.com/assets/6716962/12302943/c40534be-ba1f-11e5-862b-b9f2e142058e.png)
therefore the two BLL boards are fine.

3. We disconnected the 4DC board and obtained no errors in **canLoader** -> 4DC faulty.

4. We disconnected the STRAIN f/t sensor, no errors in **canLoader**, but errors when starting the **robotInterface** calibration procedure. Full log is [here](https://gist.github.com/gsaponaro/da8114d4207f5ca494d0), excerpt of relevant parts and **yarpmotorgui** screenshot below:
```
[ERROR]sharedcan [2] thread:1 msg:7 joint:4 timed out
[ERROR]readWord16: message timed out
...
[ERROR]100ms Timeout occured in setControlModeRaw ( j:4), current mode: cal, requested: pos
...
[ERROR]100ms Timeout occured in setControlModeRaw ( j:6), current mode: cal, requested: pos
...
[ERROR]Right_Arm_Calibrator : checkGoneToZeroThreshold: joint  4  Timeout while going to zero! 
```

![160113_yarpmotorgui_when_strain_disconnected](https://cloud.githubusercontent.com/assets/6716962/12303313/91ac6e86-ba21-11e5-8a0a-06bdadb8c51f.png)

Our thoughts so far:
* we probably need a replacement 4DC;
* question: could the **canLoader** problems also be caused by the STRAIN f/t sensor? Any other suggestions?

/cc @lorejam

**Comment by julijenv** [comment]
Hi @gsaponaro,
As more or less anticipated yesterday, I guess that as the BLL number ID 2 is not visible, so it means that something weird happen !!!
FIRST:
I'd like you to:
-> Do a power cycle of the motors. (switch OFF (wait 10s) and ON - or just TURN ON if u just restart the robot)
-> disconnect the BLL and MC4 (4DC) and do canLoder.
make a screenshot
SWITCH OFF the motors
-> disconnect the FT SENSOR and reconnect the MC4 (4DC) and do canLoder.
make a screenshot
By doning so we will nkow which boardd is actually making this UNKNWON Board appearing.
Once finding the responsible.

SECOND:

I would highly suggest u to reflash the boards (BLL and 4DC - !!! BUT NOT THE FT sensor!!!, ticking the EEPROM case on the right side inside canLoader software) on the right arm.
Do that in 2 steps:
Do a power cycle of the motors. (switch OFF (wait 10s) and ON - or just TURN ON if u just restart the robot)
wait 5s
select the firmware required by the board, tick the EEPROM and download the firmware.
repeat that for all the boards (BLL and 4DC)

THIRD
SHUT DOWN THE MOTORS
replug all the filters to all their corresponding boards and check with canLoader
if you still have this UNKNOWN message on.
Let us know

**Comment by gsaponaro** [comment]
Thank you, just a clarification about the first test: when you say "disconnect the BLL", you mean disconnect both the BLLs on net 2 (2B0 and 2B1), correct?

**Comment by julijenv** [comment]
well actually id like you to make a test on every single board so just let connected 1 board at the time.
is it clearer like that?

**Comment by gsaponaro** [comment]
OK. In the following tests (and also the ones from yesterday), we always do a power cycle and verify consistency of results by repeating the same test ~5 times. We have also replaced all the CAN filters.

As you can see below, if we leave only 1 or 2 boards connected at a time, there are no problems.  Problems only show up when 3+ boards are connected.

**First**

Having disconnected bottom BLL and the MC4 (4DC), thus having left only top BLL and STRAIN:

![160115_test1a_disconnected_topbll_and_4dc](https://cloud.githubusercontent.com/assets/6716962/12358661/4dc55166-bba6-11e5-9422-5ef068df0272.png)

Having disconnected top BLL and the MC4 (4DC), thus having left only bottom BLL and STRAIN:

![160115_test1b_disconnected_bottombll_and_4dc](https://cloud.githubusercontent.com/assets/6716962/12358796/e253b7f0-bba6-11e5-9f6f-a85bee724519.png)

Having disconnected both BLLs and the MC4 (4DC), thus having left only STRAIN:

![160115_test1c_disconnected_both_blls_and_4dc](https://cloud.githubusercontent.com/assets/6716962/12358885/5c9c0602-bba7-11e5-918b-9c79680a4f1d.png)

Having disconnected everything except MC4 (4DC):

![160115_test1d_disconnected_everything_except_4dc](https://cloud.githubusercontent.com/assets/6716962/12358923/a00601d6-bba7-11e5-9b0a-a65c1db1123e.png)

**Second**

We reflashed the 4DC with EEPROM option successfully (4DC.1.19.out.S, build 85).

We reflashed the BLL with id 1 with EEPROM option successfully (2BLL.1.50.out.S, build 85).

We reflashed the BLL with id 2 with EEPROM option successfully (2BLL.1.57.out.S, build 85).

**Third**

Reconnected everything, power flashed as usual, waited, and... the problem persists:

![160115_after_fw_upgrade](https://cloud.githubusercontent.com/assets/6716962/12359304/95a62f7a-bba9-11e5-9acf-dda21eaf7674.png)

**Our opinion so far**

The BLLs are fine (see also experiment 2 of our first message in this issue from yesterday, where one BLL at a time was connected and there were 3+ boards -> always problems).
The culprit seems to be 4DC (most likely) or STRAIN, because they are the ones present in the error situations.

**Comment by kt10aan** [comment]
@gsaponaro, we had some issues with board recognition too. The usual debugging and trouble shooting procedure  was not helping and the problem was at the filter. See https://github.com/robotology/icub-support/issues/91.

Also, as @julijenv mentioned, sometimes the flashing of the boards has to be done again, manually. See also https://github.com/robotology/icub-support/issues/144

**Comment by gsaponaro** [comment]
Hi @kt10aan, thanks for the input. We have already verified both of those things (CAN filters, and manual re-flashing of the firmware, except STRAIN as per @julijenv's last message).

@julijenv: we have performed the tests you requested (see a couple of messages up), waiting for the next suggestion when you can, thanks.

*if we leave only 1 or 2 boards connected at a time, there are no problems. Problems only show up when 3+ boards are connected.*

**Comment by julijenv** [comment]
HI @gsaponaro, did you try to plug everything but the STRAIN?
This could definitely helping us finding if it is the STRAIN is the responsible for this mess!
In any csae we are arranging things to send you a spare MC4.
How does it sounds?

**Comment by gsaponaro** [comment]
Hi there,

Yes, we made that test too - screenshot above, where it says *Having disconnected both BLLs and the MC4 (4DC), thus having left only STRAIN* -> **canLoader** showed STRAIN ok, consistently and after power cycles.

Yes, having the spare MC4 would be great and helpful. :) Let's continue the discussion by email about the delivery then.

I'll update this issue once we make more tests with the spare.

**Comment by julijenv** [comment]
@gsaponaro , no Giovanni Im asking you to plug everything EXCEPT (BUT) the STRAIN, which means MC4 and both BLLs. :P

**Comment by gsaponaro** [comment]
Oh sorry, reading too fast here :)

Yes, in fact we did that test too (Experiment 4 in the very first message of this issue) -> it gave calibration errors, full **robotInterface** log attached in that message ([direct link](https://gist.github.com/gsaponaro/da8114d4207f5ca494d0)).

**Comment by julijenv** [comment]
@gsaponaro ,
Could you just make a canLoader test; that's it nothing more and see if he bad message show up.
VBecause of course not having the strain brings the robot to do not calibrate, except maybe if your remove all the sentence in icub_all.xml containing the FT sensro for your damaged arm.
Just do canLoader

**Comment by gsaponaro** [comment]
Sure, will do it first thing tomorrow.

(In the previous test, indeed we had commented out the FT parts from ```icub_all.xml```.)

**Comment by gsaponaro** [comment]
The situation when STRAIN is unplugged while BLLs + MC4 are plugged is consistently like this (we tried it many times including power cycles):

1.
**canLoader** shows fine:
![160120_can2_disconnected_strain](https://cloud.githubusercontent.com/assets/6716962/12446176/8c86f37e-bf60-11e5-81ec-b789f406803b.png)

2.
However, when there are more packets and traffic on this CAN network (i.e., calibration procedure with properly modified xml, commenting STRAIN F/T parts), we get errors:
```
[ERROR]sharedcan [2] board 4 FAULT OVERLOAD AXIS 0
...
[ERROR]sharedcan [2] board 3 FAULT OVERLOAD AXIS 1
```

Delivery address and contacts have been sent by email yesterday night, thanks.

**Comment by gsaponaro** [comment]
Good news: replacement MC4 installed, arm works smoothly after trying **canLoader**, **robotInterface** and moving all joints with **yarpmotorgui**. Many thanks. :)

Just a small issue left: occasionally (20% of the times), **canLoader** is showing some junk in the "Additional info" string of a BLL or STRAIN board, like in the screenshot below. Even after a clean power cycle. Any thought about this?
 
![160122_icublisboa01_can2_junk_in_bll_description](https://cloud.githubusercontent.com/assets/6716962/12518852/faf4a7ba-c132-11e5-89d2-e876558f79d7.png)

**Comment by gsaponaro** [comment]
Funny... the junk characters are not appearing anymore now. If they do, we'll re-flash the corresponding firmware with EEPROM option selected, as suggested on Skype. Thanks again, issue solved.
