### ISSUE TITLE
PC104 reboots when motor power switch is turned on

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#159]
If I turn the motors off and back on using the green switch, as soon as the motors switch is back "on", the pc104 reboots. Once the reboot finish, the pc104 is apparently working fine.

**Comment by julijenv** [comment]
did it happen again? @traversaro @reafrancesco ,can we close it?

**Comment by traversaro** [comment]
I had this issue only on `iCubGenova03`, so I think that only @reafrancesco can tell us if the problem still exists.
