### ISSUE TITLE
Strange movements on wrist calibration

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#161]
After updating everything on the `iCubGenova03` robot (`yarp`,`icub-main`,`icub-firmware-build`,`icub-firmware-shared` and after flashing the firmware with `updateRobot.sh`) the following all the torso, the legs joints are in hardware fault before calibration. Also the first 4 joints of the arms are in the same situation. 

The head calibrates correctly, while the wrist calibration is causing some violent movements of the wrist. 

This is the complete output of the `robotInterface`: 
https://gist.github.com/traversaro/6bca9f6aa2a580f6a5f2

**Comment by traversaro** [comment]
A board reboot solved the hardware fault issue, but joints 4-7 of the arms still have the abovementioned calibration issues, and start in idle.

**Comment by reafrancesco** [comment]
We had a look and it seems that updateFirmware.txt had wrong firmware version for many boards included the right and left arms. So if you @traversaro read that file to work out the firmware versions than this explains the problem you experienced. I have proceeded to flash the correct version of the firmware for the mentioned boards and THIS SOLVED THE PROBLEM

**Comment by traversaro** [comment]
We should update the `firmwareUpdate.txt` file : 
https://github.com/robotology/icub-main/blob/master/app/robots/iCubGenova03/firmwareUpdate.txt to avoid further problems in the future.

**Comment by traversaro** [comment]
This should have been fixed by https://github.com/robotology/icub-main/commit/6e1de9b7c2a395be4113d499e8eebb6d1d670a85 , please reopen if needed.
cc @reafrancesco
