### ISSUE TITLE
Connector of Cable 5A1 broke iCubDarmstadt

### ISSUE THREAD

**Issue by rueckert** [robotology/icub-support#166]
Hi,

the wires of the cable 5A1 in the left leg got loose. I attached a picture. Could someone please tell me how the wiring should look like. I can of course use the other leg as reference, however, I would like to get your experts opinion. 

As we do not have neither the right tools nor the connectors, I would try to solder the wires and connect them with the remaining metal pins in the connector. That is only a temporary solution, however, Morteza would like to get some data to continue with our collaborative work. 

Many thanks, Elmar
![img_3646](https://cloud.githubusercontent.com/assets/10942366/12452452/d0205836-bf8e-11e5-90dc-5206228c1e3f.JPG)

**Comment by julijenv** [comment]
Hi @rueckert ,
Please add the label of your robot as a starter point like that we already know with who we are dealing with or if not available yet just write it down.
Second, please try to buy this list of tools and mainly the one in blue
[iCubMaintenanceTools (1).xlsx](https://github.com/robotology/icub-support/files/97618/iCubMaintenanceTools.1.xlsx)
now here the pinout of the cable which got snapped
![5a1](https://cloud.githubusercontent.com/assets/7140395/12455528/5c6f745e-bf9c-11e5-9775-867c4cf23c4a.png)

good luck

**Comment by rueckert** [comment]
Hi,

thank you very much for the swift and detailed instructions. I fixed the cable and all errors are gone.
