### ISSUE TITLE
board 2 right arm malfunctioning

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-support#169]
The calibration of the right arm is partial. During calibration only few joints move and anyway at the end of the calibration all the shoulder and elbow joints result in IDLE. @julijenv Do you think is related to a malfunction board (BOARD 2)?

**Comment by julijenv** [comment]
after a check it appears, that when the robot has been opened to fix the hanging system on the robot, some connections got loose and the power board was not power correctly and so no power and the elbow.
I fixed \as well the annulare joint which was broken
