### ISSUE TITLE
Broken wires on left leg

### ISSUE THREAD

**Issue by KevinAStein** [robotology/icub-support#171]
Hi,
We have a couple of broken wires on the left leg, precisely on top of the knee joint (see picture below).
This seems not to have affected the functionality of the robot (robotInterface starting without problems, all demos still working the same way), but without skin sensors. They have been broken for a while, but we plan to repair them today/this week.

What do these wires connect exactly?

![broken_wire](http://orb.iwr.uni-heidelberg.de/ftp/icub_screenshots/broken_wire.jpg)

cc @hu-yue

**Comment by KevinAStein** [comment]
Follow-up question, is it ok to remove this piece from the robot?
Is it removable by just unscrewing the screw on top of the part? (which seems to be the one that keeps it there?)

**Comment by super-ste** [comment]
Hi @KevinAStein 
the device whose wires got disconnected is hte board used to measure the deflection of the spring in your SEA setup.
From the picture you sent, looks like the spring ("C" shaped steel thingy which came in a box with your robot) is not mounted therefore I'd expect you read no deflection there.

It is OKAY to remove that board as long as you remember what you are doing and are okay not to measure the defleciton of the spring.
And YES you guessed correctly as which one is the screw to remove :smiley: 

If you want to resolder the wires on the NEI (this is the name of the device) plese follow the order below

![image](https://cloud.githubusercontent.com/assets/8122012/12611268/21f0a5b4-c4ec-11e5-90a3-5fbee1cebd57.png)

**Comment by KevinAStein** [comment]
HI @super-ste 
Thanks, we already resoldered the wires as per correct order.

I'm not sure about how to test if it is working again, I mean, if we now mount the spring, then how do we read the deflection using this board? 
We have mounted springs before but we used to read encoders motor side and joint side to see the difference between the two, and probably never used this "hte board"?

Thanks!

**Comment by super-ste** [comment]
@randaz81 @maggia80 
this goes far beyond my reach... any hint?

**Comment by hu-yue** [comment]
@randaz81 @maggia80 should I open anew issue for this in QA since it is not related to "broken wire"?
