### ISSUE TITLE
icubmoddev: command not found

### ISSUE THREAD

**Issue by marijnfs** [robotology/icub-support#173]
For some reason icubmoddev isn't being build anymore. I tried rebuilding all source trees; yarp and icub-main on both server and pc104, but it appears nowhere. Where is it supposed to show up?

**Comment by pattacini** [comment]
Hi @marijnfs 
Please follow these instructions: https://github.com/robotology/QA/issues/68.

**Comment by marijnfs** [comment]
Ok so I should just use yarpdev? It is essentially the same binary?

**Comment by traversaro** [comment]
Exactly.
