### ISSUE TITLE
strain_get_matrix_rc : invalid response Error 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#181]
While opening the `canLoader --calib` window the leg FT sensors of iCubGenova04 with @fjandrad and @julijenv , we got this error several times: 
~~~
strain_get_matrix_rc : invalid response
~~~

This is due to this line of code:
https://github.com/robotology/icub-main/blob/a12d93d60a5af69cbe970c68b7d55e40dd40b49d/src/tools/canLoader/canLoaderLib/downloader.cpp#L774

The problem was always happening, but it affects different elements of the calibration matrix every time.

@valegagge 

cc @randaz81

**Comment by valegagge** [comment]
The problem has been fixed in version 3.0.4. 
Strain sensors on iCubGenova04 were not updated with last firmware version.
I just updated them and all is ok.
