### ISSUE TITLE
Wrist limits wrong on Bluey

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#186]
When launching the robotInterface, everything starts without errors, but the right wrist is almost at 90 degree with the arm, and so the kinematic. Yarpmotorgui does not show any fault, and sliders work, but 0 limit is found at this degree, instead of pointing forward.  Would appreciate fast fixing for further testing upcoming demo implementation. 

Thanks in advance!!
Tanis

**Comment by spada1978** [comment]
it was necessary to replace the carbon piece RC_TLR_017_P_001 as broken in correspondence of the fixing screw.
They were also pulled the movement of 1B2M2 and 1B2M1 pulse motor cables
