### ISSUE TITLE
Starting Robotinterface shows error icub Viola

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#194]
##### Description of the failure
90029		22701,767589		ERROR		cfw2can [0] thread:6 msg:65 joint:1 timed out

##### Detailed conditions when the failure occurred
When starting yarpmotorgui it was found some hardware fault in the arms.
After proceeding to restarting robotinterface and the motors, the logger showed the previously mentioned error. We would see the head move a little and the eyes too, afterwards it would stop moving. No movement of the arms and hands was observed.

**Comment by traversaro** [comment]
it was  @fjandrad who posted the issue, sorry Silvio I didn't notice you had your git account open on the icub23.

**Comment by julijenv** [comment]
didnt hear anything since then - should I close it?

**Comment by traversaro** [comment]
The day after we were not able to reproduce this issue, closing.

**Comment by randaz81** [comment]
Just as a memo: this error shows up when a board gets disconnected from the pc104, either because it is unable to respond on the CAN bus (wires damaged) or the board power supply is down.
