### ISSUE TITLE
Hardware fault iCub Viola

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#199]
##### Description of the failure
4289		145,177093		ERROR		 from BOARD 10.0.1.5 (EB5), src LOCAL, adr 0, time 16s 299m 296u: (code 0x05000014, par16 0x0303 par64 0x0100000000000006) -> CFG: EOtheEncodeerReader cannot be configured. verification fails. in p16 the number of joints (lsb) and encoders (msb), in p64 the error status of verification reading + .

##### Detailed conditions when the failure occurred
During a `YOGA++` demo test on both feet robot signalled hardware fault in the torso.
When restarting it shows the  message displayed above.

**Comment by julijenv** [comment]
It has been found the 3S0 AEA encoder broken - it has been successfully replaced.
