### ISSUE TITLE
Add configuration files for enabling skin diagnostics

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#2]
@barbalberto

I would assign this issue to MarcoM. as soon as he has a github account.

**Comment by lornat75** [comment]
cc @maggia80

**Comment by barbalberto** [comment]
It seems that some robot has the "enable diagnostic true" by default which is not correct, maybe some typo while generating files for new robots. I'll suggest to production guys to verify that all robots has false until we have the new and correct skinSpecs files.

**Comment by lornat75** [comment]
we should explain the production how to update the config files and enable diagnostics! @maggia80

On 18/mar/2015, at 18:10, "Alberto Cardellino" <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that some robot has the "enable diagnostic true" by default which is not correct, maybe some typo while generating files for new robots. I'll suggest to production guys to verify that all robots has false until we have the new and correct skinSpecs files.

**Comment by lornat75** [comment]
@davidetome: was this check done? Can we close the issue?

**Comment by davidetome** [comment]
fixed on 25/3/15. all flags settled false for all robots in repo
