### ISSUE TITLE
middle finger broken on the right hand of the black iCub

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#206]
##### Description of the failure
The proximal joint of the right hand's middle finger doesn't move anymore, probably the tendon is broken

##### Detailed conditions when the failure occurred

High pwm was being applied to the proximal joint while pushing against an object

**Comment by spada1978** [comment]
Replacement cable proximal right middle finger broken, and tension occurs proximal thumb and right wrist cables, replacing 7 right shoulder cord
