### ISSUE TITLE
Joint 9 of right thumb is damaged

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-support#211]
##### Description of the failure
The cable actuating the joint 9 (proximal) of the right arm became a tangled jammed mess and thus that joint is no longer working.

##### Detailed conditions when the failure occurred
The thumb did not undergo any special shock during usage, but we then noticed it was tangled. It could be possibly due to the way it was mounted.

cc @vtikha @julijenv @spada1978 @massimoregoli @lornat75 @nawidj

**Comment by pattacini** [comment]
Thanks a lot @julijenv for your availability!
cc @vtikha

**Comment by julijenv** [comment]
it has been repaired successfully, hope it will last!
