### ISSUE TITLE
Cable in left shoulder broken 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#212]
##### Description of the failure
A cable in the left shoulder broke. 
![421213706_15610827159318758916](https://cloud.githubusercontent.com/assets/1857049/14110587/5c9d0c8c-f5c7-11e5-9838-867c0d185f8b.jpg)

##### Detailed conditions when the failure occurred

I was doing some sanity checks on the low level torque control, so it is an unsafe operation by definition. : )

**Comment by traversaro** [comment]
cc @reafrancesco @julijenv

**Comment by julijenv** [comment]
recabled and changed cableN2 of the left shoulder, tested with success, ready to be used.
