### ISSUE TITLE
Cannot log into iCubSheffield01

### ISSUE THREAD

**Issue by dcam0050** [robotology/icub-support#219]
##### Description of the failure
I tried logging into iCubSheffield01 using ssh but I'm being denied entry. It arrived a week ago and was working. The problem happened after I updated the software on the icub blades. When it got here I set up passwordless ssh but after updating the software and tried sshing again I received a notification that the password had been changed.

I can ping pc104 but when I try to ssh into icub@pc104 or root@pc104 am denied access. The passwords I tried are icub and icubPassword. 

Thanks

**Comment by barbalberto** [comment]
See issue #114

**Comment by dcam0050** [comment]
PC104 reverted to the original password live.
