### ISSUE TITLE
Non standard screws used to mount the left_leg FT sensor 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#222]
While replacing the F/T sensor of the left_leg, we stripped some screws. We did not have any replacements, so we had to buy the most similar replacements that we were able to find. 
This issue is to notify to the icub production/support team that this non-standard screws are current used in `iCubDarmstadt01` : 
![photo_2016-04-14_17-43-50](https://cloud.githubusercontent.com/assets/1857049/14534230/7b7219ec-0268-11e6-8e9e-5db2022a2add.jpg)
![photo_2016-04-14_17-43-43](https://cloud.githubusercontent.com/assets/1857049/14534229/7b71ccee-0268-11e6-8b6e-89751e06ba53.jpg)

**Comment by DanielePucci** [comment]
@julijenv
