### ISSUE TITLE
l_pinky (joint 15 of left_arm) not working 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#223]
##### Description of the failure
The `l_pinky` degree of freedom (joint 15 of left_arm part)  of the left hand is not moving when a new position is commanded using the yarpmotorgui. Furthermore, the yarpmotorgui reports a position of `l_pinky` of `113.437` degrees, even if the fingers are totally opened (that should be equal to the 0 position), hinting that there could be a problem in the sensed position. 

##### Detailed conditions when the failure occurred
We noticed this only today, so we don't know what caused this failure. During this week we tested mainly balancing experiments, so we did not directly used the hands.

**Comment by julijenv** [comment]
close because already mentionned in #224
