### ISSUE TITLE
3D printing a broken plastic part

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-support#229]
Hi @robotology/icub-support-team 

iCub developers in Plymouth are wondering whether they could 3D print the little plastic part visible in the figure below that just got broken.

![snapshot](https://cloud.githubusercontent.com/assets/3738070/14849444/6340005e-0c73-11e6-87ec-6148d4d6e332.png)

Is there any chance to retrieve the drawing?

**Comment by pattacini** [comment]
cc @mstoelen

**Comment by pattacini** [comment]
Hi @mstoelen 

Here's the [**3D model**](https://github.com/robotology/icub-support/files/241546/rc_iit_003_p_006_00.stl.gz).
Hope this helps.

**Comment by mstoelen** [comment]
Great - thanks!
