### ISSUE TITLE
icub24 laptop has frequent window manager problems 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#233]
##### Description of the failure
We have continuous problems on the iCubGenova02 setup due to the Window Manager (Unity?), see for example how I found the robot laptop today: 
![guiproblem](https://cloud.githubusercontent.com/assets/1857049/14917884/7b994d5e-0e21-11e6-9c60-3e3c978ada2b.png)

Given that by chatting with other users this is not the first Window Manager-related problem, can we switch to use by default some more stable and usable window manager (for example XFCE)? 

@mbrunettini @drdanz

**Comment by mbrunettini** [comment]
I suspect it's not related to the Window Manager, but to the nVidia video drivers. There are other issue, that will be fixed upgrading to Ubuntu 16.04. 
I will switch the default vm to gnome, anyway.

**Comment by DanielePucci** [comment]
As @lornat75 pointed out in https://github.com/robotology/icub-support/issues/215#issuecomment-207087477 it is better to leave this kind of issues open till the upgrade.

**Comment by traversaro** [comment]
I think that this was fixed by switching the default WM to Metacity.

**Comment by DanielePucci** [comment]
👍

**Comment by drdanz** [comment]
You know my answer.

**Comment by traversaro** [comment]
Note: to correctly use Qt5 YARP GUIs menus on Metacity on Trusty, it is necessary to remove the appmenu-qt5 package, see https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619 for more info.
