### ISSUE TITLE
Left Shoulder not moving

### ISSUE THREAD

**Issue by AlexAntn** [robotology/icub-support#247]
Shoulder won't move on startup on iCubPlymouth01, robotInterface keeps printing:
`[ERROR]sharedcan [1] board 1 ABS ENCODER ERROR AXIS 1`

This problem came up after we had to replace cable 4 on the left shoulder. 
yarpMotorGui says that joint 1 has an hardware fault, and the angle of this joint does not update even when moving the arm.

I checked the cables both on the back and on the arm, and no cable was visibly broken.

Any other possible debug we can run?

**Comment by julijenv** [comment]
Hi @AlexAntn ,
Could you explain me how you proceed to restore the cable 4?
what did you unmount? Did you remove the upper arm cover, by any chance?
If not, just check this cable.
![s4_1b1](https://cloud.githubusercontent.com/assets/7140395/15682208/ed5a71d0-275c-11e6-8661-cadbfd530358.png)
Let me know,

**Comment by AlexAntn** [comment]
Hello @julijenv ,

We did not remove the upper arm cover when replacing the cable, we only removed the torso front-cover.

I checked those connectors, didn't see anything obviously out of place. In either case, i did take a picture:

![img_20160531_114202](https://cloud.githubusercontent.com/assets/9463167/15682396/5ee828d6-2755-11e6-92f8-c8ace4fbfa06.jpg)

Thanks for the reply!

**Comment by julijenv** [comment]
Hi @AlexAntn ,
could you please take a look at the sensor at the level of the shoulder 
AE2 on the photo below.
![image](https://cloud.githubusercontent.com/assets/7140395/16050334/922b55b8-325b-11e6-8292-e73bfcc5c4d7.png)
I guess this one is broken, most probably one of the wire is unsoldered?.
anyhow, please try to get in touch with icub.cupport on skype, thx

**Comment by AlexAntn** [comment]
Hello @julijenv ,

I checked the sensor in AE2 and didn't see any broken cable. I opened the arm covers to see if the cable could be broken half-way, and i couldn't see any signs of it either.... 

This being said, the cable could be broken half-way, beneath the rubber cover...

I'll try to get in contact with the icub support on skype, thanks!

**Comment by julijenv** [comment]
Hi @AlexAntn ,
any news?
Could you try to remove the connector I told you that was probably broken and check (when robot has the red butoon pressed) if the message is still the same.
send me the log file.
thx in advance

**Comment by AlexAntn** [comment]
Hello @julijenv ,

No news yet, as i haven't been able yet to find the time to contact icub.support on skype.

In any case, i ran the yarprobotinterface twice, first with the cable still plugged in (nothing changed) and then with the cable plugged out (the top-most one on the left side, as indicated on your image).

1) With the cable still on: [OutputCableOn.txt](https://github.com/robotology/icub-support/files/330308/OutputCableOn.txt)

2) with the cable unplugged: [OutputCableOn.txt](https://github.com/robotology/icub-support/files/330309/OutputCableOn.txt)


From what i saw on the output, it's a different cable/board (the main difference was that, with the cable unplugged, both board 1 and board 2 were showing errors, as opposed to just board 1 with the cable still plugged).

Thanks for the reply!

**Comment by julijenv** [comment]
Hi @AlexAntn ,
could you reup the file with the connector unplugged coz actually you put twice the same file.
c u soon

**Comment by AlexAntn** [comment]
Hello @julijenv ,

I'm so sorry, here it goes:

2) with the cable unplugged: [OutputCableOff.txt](https://github.com/robotology/icub-support/files/330483/OutputCableOff.txt)


Thanks!

**Comment by julijenv** [comment]
Hi @AlexAntn,

ok so now I understand my error, it is for sure AE2 which has a problem but the connection is done at the level of the board 1B0 (the one below and the connector is labelled S2 - in the inside part of torso).
do continuity test and try to understand which cable is broken.
good luck, let me know

**Comment by AlexAntn** [comment]
Hello @julijenv ,

I was going to perform the continuity test today on the cable S2, but as i was reaching the cable, i noticed a thin white wire loose (see image), which is probably the cause of the error.

![broken white wire](https://cloud.githubusercontent.com/assets/9463167/16456211/12be10da-3e0f-11e6-89a6-85ecf21b7680.jpg)


![broken white cable](https://cloud.githubusercontent.com/assets/9463167/16456512/fd59e394-3e0f-11e6-92aa-1f9477d28b9c.jpg)

(sorry for the low quality pictures)

This being said, the connector is in a really hard place to remove, as it is blocked by the metal cillinder (to attach the back cover of the iCub, see picture).

How can i remove the connector? is it possible to remove the blocking cillinder? 

Thanks!

**Comment by julijenv** [comment]
Hi @AlexAntn ,
Please unscrew the standoffo cover (mettalic cilinder) and rewire the connector. Let me know.

**Comment by julijenv** [comment]
Hi @AlexAntn ,
any news?

**Comment by AlexAntn** [comment]
Hello @julijenv ,


I still haven't been with the iCub since friday, i will let you know as soon as we get some news!

Thanks!

**Comment by AlexAntn** [comment]
Hello @julijenv ,

We finally managed to crimp the wires back. Now everything is working fine! :)

Sorry for taking this long to provide an update, and thanks for the help!
