### ISSUE TITLE
Joints 7 of right_arm (r_hand_finger) goes in fault immediatly after startup

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#249]
##### Description of the failure
During startup or immediatly after startup, the joints of the right arm after the number 3 go to fault/idle. 

##### Detailed conditions when the failure occurred
I will comment this issue for each occurrence on the problem. : )

**Comment by traversaro** [comment]
## Conditions
We startup the robot successfully, then after some minutes the hand fall. 

## Log 
https://gist.github.com/traversaro/0ab25c4bdd71aabd96baa7caf3143deb#file-log_1_jun_2016_lumix-txt

## Joints situation
![screenshot from 2016-06-01 15 51 07](https://cloud.githubusercontent.com/assets/1857049/15712071/1cb8a938-2811-11e6-8ab0-8592e2f09754.png)

**Comment by traversaro** [comment]
## Conditions 
We started the robot, and the joints 8 => 15 went in fault during calibration.
After some minutes also the joints 4 => 7 went in fault. 

# Joint conditions 
After startup:
![screenshot from 2016-06-01 15 59 08](https://cloud.githubusercontent.com/assets/1857049/15712339/44b09062-2812-11e6-9109-c0aa50c1e50f.png)

After some minutes:
![screenshot from 2016-06-01 16 00 07](https://cloud.githubusercontent.com/assets/1857049/15712354/543c3040-2812-11e6-9f1a-6b9f3e1a81f7.png)

## Log 
https://gist.github.com/traversaro/d54e57868a6b290d8dad8e4da93b42ee#file-log_1_jun_2016_lumix_test2-md

**Comment by traversaro** [comment]
@julijenv found the problem: on cable 4N1 the two CAN cables (black and white) where exchanged:
![photo_2016-06-01_16-59-09](https://cloud.githubusercontent.com/assets/1857049/15716434/2f1b6a58-281a-11e6-83ef-3d920abb07f5.jpg) 

@julijenv fixed it and now everything seems to be working fine.

**Comment by traversaro** [comment]
Actually there are still problems, and @julijenv will check again friday morning.

**Comment by traversaro** [comment]
Current situation: with the `r_upper_arm` link without cover, starting the robot will always result in the Joint 7 of the right_arm (`r_hand_finger`) to be in Hardware Fault (I guess there is some board detached). 

Occasionaly there is also an hardware fault on the joint 1 of the right_leg (`r_hip_roll`), but this failure does not seems to be related.

**Comment by traversaro** [comment]
Update: at the moment, the only joint that is consistently in hardware fault is the joint 7 of the `right_arm` (`r_hand_finger`).

**Comment by davidetome** [comment]
the motor was shorted with the chassis. Replaced -> Fixed
