### ISSUE TITLE
Tactile network - left hand

### ISSUE THREAD

**Issue by AGiagkos** [robotology/icub-support#251]
Dear list, 

There is an issue with Aberystwyth iCub. The tactile network on left hand does not function. Palm receives signals but digits do not (we also noticed that the palm signals have slow update rate compared to the right hand). We have tried to find out where the problem is with the wiring - many of the wires have came loose from the PCB E714755. There are some questions we'd like to ask in connection to wiring.

Could you please point us to the pin out for PCB labelled E714755? In particular, the pin out signals of the J1 plug. We'd also like to know what the MTB3_003 unit on the diagram provided online (URL) is. 

Additionally, are the small PCBs attached to E714755 passive connections/jumpers or are they any active components in the small boards attached to the J2-6? 

Also, are the tactile sensors SPI? If so, where does the conversion to CAN bus occur? Which PCB?

The problem that we are seeing is that we get clean signals on J1 (colours GREEN, YELLOW, BLUE and WHITE). However, when we connect the one of the little boards on in J2-6, the signals do not disappear, rather we do not longer get the 50Hz typical signals we see on the other hand. In between the bursts at 50Hz we get multiple transitions. 

Any extra diagrams or hints related to this wiring are much appreciated. 

Many thanks,

Alexandros & Pete

**Comment by julijenv** [comment]
Hi @AGiagkos ,
sorry for my laste reply, anyhow could you try to get in touch with the icub.support team on skype, because what you are explaining and requesting is far from being clear to me, we may have to debug a bit together and i could explain you a bit more what do what.
add us on your contact lis on skype:
icub.support
