### ISSUE TITLE
Shoulder cables out of place

### ISSUE THREAD

**Issue by francesco-romano** [robotology/icub-support#252]
Cables of the right shoulder are out of place (it happened during yoga++ demo).

Because of the demo of tomorrow morning can you check also all the other cables?

Furthermore, the hand and the head should be closed.

cc @julijenv @spada1978

**Comment by traversaro** [comment]
Fixed by @julijenv .

**Comment by traversaro** [comment]
It happened again, given that there is again a demo tomorrow, can you try to check it @spada1978  ? Thanks!

**Comment by spada1978** [comment]
cable n.7 replaced and made new mechanical cabling
