### ISSUE TITLE
Joint 0 head goes in hardware fault while joint 1 goes in idle 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#253]
When lowering the robot for doing the balancing demo, the joint 0 of the head goes in hardware fault. 

The only `yarprobotinterface` message that seems related is:
~~~
618854		327260,726010		DEBUG		cfw2can [0] msg from board 1: PWM DIS CH1 
618856		327260,726066		DEBUG		cfw2can [0] msg from board 1: PWM DIS COUPLED:1 
618859		327260,726093		DEBUG		cfw2can [0] msg from board 1: PWM DIS CH0 
~~~

**Comment by francesco-romano** [comment]
related to https://github.com/robotology/icub-support/issues/240

**Comment by traversaro** [comment]
Closing because it is a duplicate of https://github.com/robotology/icub-support/issues/240 .
