### ISSUE TITLE
Tactile sensors on right arm are not working

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#258]
##### Description of the failure
 Tactile sensors on right forearm and hand are not working.

##### Detailed conditions when the failure occurred

Tactile sensors on right forearm and hand are the only ones that are not working. Lights on boards controlling those parts do not seem to blink normally: the blink frequency is faster than usual.

**Comment by julijenv** [comment]
has been solved

**Comment by matejhof** [comment]
This seems to be coming back - after fresh robot starts, the skin on right forearm is dead.
Right hand  (palm and fingers) is often dead too. Sometimes it comes up, but activations in fingers are weird - persisting phantoms etc.

**Comment by spada1978** [comment]
the electric wires have been boosted in power filters of the skin located in the cover forearm
