### ISSUE TITLE
replacing left shoulder cables

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-support#259]
Please fill in the following two sections:

##### Description of the failure
cable n.7 of the left shoulder snapped off its path.

##### Detailed conditions when the failure occurred
excessive consumption of the left shoulder cables(n.5, n.7, n.8) caused a failure at the shoulder

**Remark**: if you are not a daily icub-support user (e.g. newbie), please read carefully the guidelines for contributing linked at the top of this page. In particular, the name of your robot must be always indicated: either using labels if you're already a contributor, as per standard, or by specifying it while detailing the issue.

**Comment by spada1978** [comment]
the cables have been replaced. 5 - on 7 and 8, and the wiring it has been carried out again with julien
