### ISSUE TITLE
iCubSheffield broken cables

### ISSUE THREAD

**Issue by dcam0050** [robotology/icub-support#260]
##### Description of the failure
1. Torso yaw cable broken
2. Middle distal cable broken
3. Middle proximal cable broken

##### Detailed conditions when the failure occurred
Failure 1: Using it in normal operation turning to point to an object and saw the cable snap
Failures 2 and 3: Not present when they happened

Cables have been removed and would like to request a complete set of replacement cables. Thanks.

**Comment by dcam0050** [comment]
Who do I need to contact to get a quote and order a full set of tendons? Thanks

**Comment by julijenv** [comment]
Hi @dcam0050 ,
Do you have some spare cables, especially the torso yaw one (Number 13) to restore the torso in the meanwhile?
here below is an example I would recommend you to order to be safe for a long time.
It is a kit of at least 2 piece each and 5 for the most breakable and wearable cable (7 and 8).
let me know, what you think about it.
You could notice tendon V2 with a different code number - about this I'd like you to send me a couple picture a of one of your foream at the level of the wrist or without the forearm cover would be of a great help (there are 2 versions of it) to know if i dont give you too much cable to order :S.
thx in advance
[order.xlsx](https://github.com/robotology/icub-support/files/320884/order.xlsx)

**Comment by dcam0050** [comment]
Hey @julijenv unfortunately we don't have any spare torso cables here to restore the torso so it would be great if we could ship the list of cables you suggest as fast as possible. 

Here are the iCub forearm pictures you requested:
![img_3662](https://cloud.githubusercontent.com/assets/4288535/16189392/142e8ef2-36d2-11e6-91f2-f060acb08971.JPG)
![img_3661](https://cloud.githubusercontent.com/assets/4288535/16189409/23f0c526-36d2-11e6-9bd1-2d4257c73d5c.JPG)
![13493321_1419489984743808_1882621561_o](https://cloud.githubusercontent.com/assets/4288535/16189499/99e25614-36d2-11e6-85e7-44fe45b2e3cd.jpg)
![13509479_1419490258077114_1927723927_o](https://cloud.githubusercontent.com/assets/4288535/16189500/99e59d88-36d2-11e6-9190-252b271f82d8.jpg)

Are these good enough to determine which version tendon v2 is?
Thanks

**Comment by julijenv** [comment]
Hi @dcam0050 ,
everything is alright, the list I sent to you is perfectly fitting your need, I will send you an invoice (I mean one of my colleague which deal with the purchase office will send you an offer for the set of cable).
Could you please give your personnal mail address on skype to forward it to my colleague?
my skypeID : icub.support
thx in advance

**Comment by dcam0050** [comment]
Any progress with the cables invoice? There's a deadline approaching soon so we need the cables urgently. Thanks.
