### ISSUE TITLE
mais board at the right hand

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-support#266]
Please fill in the following two sections:

##### Description of the failure
Mais board seems to receive no power. Leds are off at the right hand.

##### Detailed conditions when the failure occurred
The filter connector seems to be connected no problem and the cover of the arm and hand have been removed already.

**Remark**: if you are not a daily icub-support user (e.g. newbie), please read carefully the guidelines for contributing linked at the top of this page. In particular, the name of your robot must be always indicated: either using labels if you're already a contributor, as per standard, or by specifying it while detailing the issue.

**Comment by julijenv** [comment]
HI @reafrancesco ,
done
