### ISSUE TITLE
thumb abduction,  left arm 

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-support#268]
Please fill in the following two sections:

##### Description of the failure

broken cable to be substituted
##### Detailed conditions when the failure occurred

**Remark**: if you are not a daily icub-support user (e.g. newbie), please read carefully the guidelines for contributing linked at the top of this page. In particular, the name of your robot must be always indicated: either using labels if you're already a contributor, as per standard, or by specifying it while detailing the issue.

**Comment by spada1978** [comment]
replaced the cable and re-performs the mechanical wiring
