### ISSUE TITLE
Various software issues on icub19 laptop

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#269]
* There is no interned access on the laptop, even if DNS queries are correctly resolved and there is internet access on `icub-srv` . 
* `meld` is not running on the `pc104` (`meld` is called by `yarp-config robot --diff YARP_ROBOT_NAME`, so it is quite critical that it works correctly to main the robots configuration files). 

cc @mbrunettini

**Comment by mbrunettini** [comment]
1) can you check that the IP address is 10.0.0.1 and the GW is 10.0.0.1?
2) did you export the DISPLAY variable before using MELD?

**Comment by traversaro** [comment]
2) All other graphical programs are working, I can't easily copy paste the error message that only `meld` is outputting because the internet is not working : )

**Comment by traversaro** [comment]
1) ![425421408_11893145411895658176](https://cloud.githubusercontent.com/assets/1857049/16612863/8b9d6e24-4369-11e6-9ee7-4f7977d4d311.jpg)

**Comment by mbrunettini** [comment]
fixed.
1) wrong NATting configuration on server, due to reinstallation
2) locale not configured conrrectly on PC104, fixed in next image release

**Comment by traversaro** [comment]
There is a workaround for 2) in the meanwhile? Setting `LC_ALL` in the terminal where you want to use `meld`?

**Comment by mbrunettini** [comment]
it IS working on lumix now.
I fixed on the PC104, the next image will be working by default on alla images.

**Comment by traversaro** [comment]
Thanks!
