### ISSUE TITLE
Robot unable to read from EMS board EB11 (right_leg skin/inertials)

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#271]
The robots seems unable to read data from the EB11 board, and the `yarprobotinterface` is flooded with error message in this sense.

**Comment by marcoaccame** [comment]
actually, diagnostics says that the board EB11 cannot write can frames into CAN2.
that typically happens when CAN2 is disconnected.

advices are: fix CAN2 cabling or remove devices which use EB11:CAN2

**Comment by DanielePucci** [comment]
For the record: to avoid being distracted by all those errors, I disable the right_leg skin/inertials in the yarprobotinterface configuration file.

**Comment by davidetome** [comment]
found a cutted wire on can line between eb11 and skin mtb3 boards. fixed
