### ISSUE TITLE
Broken right shoulder cable on icub black

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#272]
##### Description of the failure
Broken right shoulder cable on iCub Black

##### Detailed conditions when the failure occurred
I was testing some tool use actions, and in one of the robot pulled his arm too close to the body, creating a tension that broke the cable :(

**Comment by vtikha** [comment]
This is extremely unfortunate as the robot is needed by 9:00 tomorrow morning. Is it possible to have it fixed first thing in the morning? Thanks in advance

**Comment by tanismar** [comment]
I know... I am very sorry... :( I hope it can get fixed on time :S

**Comment by spada1978** [comment]
as your request repaired on time. cable number 7 replaced and the wiring again.

**Comment by vtikha** [comment]
Thank you very much @spada1978
