### ISSUE TITLE
Right shoulder tendons out of place

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#276]
Please fill in the following two sections:

##### Description of the failure
Right shoulder tendons out of place

##### Detailed conditions when the failure occurred
During the Fast YOGA++, the right shoulder tendons went out of place

**Remark**: if you are not a daily icub-support user (e.g. newbie), please read carefully the guidelines for contributing linked at the top of this page. In particular, the name of your robot must be always indicated: either using labels if you're already a contributor, as per standard, or by specifying it while detailing the issue.

@spada1978 @julijenv

**Comment by spada1978** [comment]
the cable was not broken but only escaped from the place the crimp.
was the wiring again
