### ISSUE TITLE
Right elbow gets stuck even if the robot is off

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#277]
##### Description of the failure
When moving the right elbow, one observes that it gets stuck even if the motors are off.

##### Detailed conditions when the failure occurred

Random checks discovered the problem.

@julijenv @spada1978

**Comment by spada1978** [comment]
it was necessary to dismantle the engine right elbow experiencing the breakup of 618-4 ball bearing number IIT in 1803 that should be placed on RC_TLR_003_P_034 piece.
So the ball bearing 618-4 replaced and reassembled everything was replaced.
![cuscinetto](https://cloud.githubusercontent.com/assets/14175004/16794615/46c2c64e-48d9-11e6-8581-a99877fe1eec.JPG)
