### ISSUE TITLE
skin problems on left upper arm 

### ISSUE THREAD

**Issue by matejhof** [robotology/icub-support#28]
Hi,
The skin on left upper arm had problems already before the blackie went to Shanghai. One triangle seemed to be often “stuck” - permanently activated.  I think the one on the picture below.
![left_arm_skin_problems](https://cloud.githubusercontent.com/assets/6461061/7982001/56a2441e-0ab3-11e5-91ec-aac87e975e42.png)
Phantom activations were appearing also on other regions of the upper arm. Can you please have a look?

Thanks!
Matej

**Comment by matejhof** [comment]
The problem still persists. From what I understood from @julijenv , to fix it may require replacing the PCB.

**Comment by maggia80** [comment]
Yes, the only way to solve it, is to replace the pcb.

**Comment by super-ste** [comment]
If I am not mistaken the skin is being replaced right now. @Julijenv ,can you confirm and provide possible restoration time?
