### ISSUE TITLE
right hand pinky finger distal

### ISSUE THREAD

**Issue by reafrancesco** [robotology/icub-support#281]
Please **fill in the following two sections** and then **remove any comment become unnecessary**:

##### Description of the failure
re-connection of the last joint in the right hand

##### Detailed conditions when the failure occurred

**Remark**: if you are not a daily icub-support user (e.g. newbie), please read carefully the guidelines for contributing linked at the top of this page. In particular, the name of your robot must be always indicated: either using labels if you're already a contributor, as per standard, or by specifying it while detailing the issue.

**Comment by spada1978** [comment]
replaced the 2391 codice IIT cable code of the little finger and the ring finger and made the mechanical wiring
