### ISSUE TITLE
Mechanical Backlash on the right leg

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-support#283]
##### Description of the failure
When trying to set the hip roll joint to the home position, the right leg starts oscillating, especially when the error from the reference gets close to zero.

It happens all the time the robot is set to the HOME position and it has to be killed.

The cause seems to be a mechanical backlash on the leg ( @julijenv should already know about this problem)

@julijenv @spada1978   @francesco-romano

**Comment by pattacini** [comment]
@S-Dafarra you should have received an email inviting you to join our dev group in robotology. This way you'll be entitled to assign labels to issues.

**Comment by julijenv** [comment]
the screws holding the internal harmonic elipsoidal shape with teeth were all totaly loose. . It has been performed on one of those screws some unscrewing glue and all the other have been tightened.
