### ISSUE TITLE
Left Thumb not moving

### ISSUE THREAD

**Issue by TeoKa** [robotology/icub-support#285]
##### Description of the failure

The left thumb was not moving. yarplogger did not report any [ERROR].

In the yarpmotorgui:
- The left thumb joint was running in position control - not in hardware fault.
- Physically moving the left thumb joint, the encoder measured different positions.
- However, moving the left thumb joint from the yarpomotorgui, the joint physically did not move.
##### Detailed conditions when the failure occurred

Running the iCub start up (yarprobotInterface) either from yarpmanager and from terminal.

**Comment by julijenv** [comment]
The motor works and I came to inspect, let's keep thsi issue open until it wont work anymore, at that time we will try to figure out what is really not working properly.
