### ISSUE TITLE
Boards not responding to pc104

### ISSUE THREAD

**Issue by gregoire-pointeau** [robotology/icub-support#288]
### Description of the failure
Hello, we have a failure when launching `yarproborinterface`.
It seems that the boards don't respond to `pc104`
It comes after a full update of the system.

### Detailed conditions when the failure occurred
Here is the log of the error we have: 

>AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
sharedcan [1] thread:0 msg:91 joint:0 timed out
getFirmwareVersion: message timed out
Unable to read firmware version 
sharedcan [1] thread:0 msg:91 joint:1 timed out
getFirmwareVersion: message timed out
Unable to read firmware version 
sharedcan [1] thread:0 msg:91 joint:2 timed out
getFirmwareVersion: message timed out
Unable to read firmware version 
###################################################################################
###################################################################################
  It has been detected that your control boards are not using the same
  CAN protocol used by iCubinterface. iCubInterface cannot continue.
  Please update your system (iCubInterface and/or your control board firmware.
  For further information please visit: http://wiki.icub.org/wiki/Firmware
###################################################################################
###################################################################################
checkFirmwareVersions() failed. CanBusMotionControl::open returning false, 
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
sharedcan [5] thread:0 msg:91 joint:0 timed out
getFirmwareVersion: message timed out
Unable to read firmware version 
sharedcan [5] thread:0 msg:91 joint:1 timed out
getFirmwareVersion: message timed out
Unable to read firmware version 
###################################################################################
###################################################################################
  It has been detected that your control boards are not using the same
  CAN protocol used by iCubinterface. iCubInterface cannot continue.
  Please update your system (iCubInterface and/or your control board firmware.
  For further information please visit: http://wiki.icub.org/wiki/Firmware
###################################################################################
###################################################################################
checkFirmwareVersions() failed. CanBusMotionControl::open returning false, 
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
lAnalogWrapper: the parameter 'deviceId' has been deprecated, please use parameter 'name' instead. 
lAnalogWrapper: the parameter 'deviceId' has been deprecated, please use parameter 'name' instead. 
One or more devices failed opening... see previous log messages for more info 

Thanks for your help.

**Comment by julijenv** [comment]
hI @gregoire-pointeau ,
could you please do a canLoader and check the ID and version of all the boards for any net?
youu could send me the pictures of all the net, to cjheck with you if you wish or joining me on skype,
c u around,

**Comment by gregoire-pointeau** [comment]
![net0](https://cloud.githubusercontent.com/assets/4243669/17967084/9a09ac4c-6ac5-11e6-9c4b-52d1736e37a4.png)
![net1](https://cloud.githubusercontent.com/assets/4243669/17967086/9a263998-6ac5-11e6-8e5d-d2fb19b8ac5a.png)
![net2](https://cloud.githubusercontent.com/assets/4243669/17967087/9a276b42-6ac5-11e6-9138-a2ec9626d246.png)
![net3](https://cloud.githubusercontent.com/assets/4243669/17967091/9a2c0756-6ac5-11e6-8d23-6633dfe01198.png)
![net4](https://cloud.githubusercontent.com/assets/4243669/17967089/9a29ee4e-6ac5-11e6-9cfe-bb8d24c764d7.png)
![net5](https://cloud.githubusercontent.com/assets/4243669/17967088/9a273d70-6ac5-11e6-90f3-74160941fa19.png)
![net6](https://cloud.githubusercontent.com/assets/4243669/17967085/9a1ac8ec-6ac5-11e6-9a59-4741e7253f13.png)
![net7](https://cloud.githubusercontent.com/assets/4243669/17967090/9a2c0eb8-6ac5-11e6-9cd9-8f7b1b7c15bf.png)
![net8](https://cloud.githubusercontent.com/assets/4243669/17967092/9a37c028-6ac5-11e6-88ed-2176d866b4d1.png)
![net9](https://cloud.githubusercontent.com/assets/4243669/17967093/9a38bf8c-6ac5-11e6-8fc0-ebc02b60e68c.png)

**Comment by julijenv** [comment]
hi @gregoire-pointeau ,
did u update the firmware on the boards? did you turn ON the motors?
let me know

**Comment by gregoire-pointeau** [comment]
Latest error:

>AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
AxisType not found
motorPwmLimit not found
lAnalogWrapper: the parameter 'deviceId' has been deprecated, please use parameter 'name' instead. 
lAnalogWrapper: the parameter 'deviceId' has been deprecated, please use parameter 'name' instead. 
Head_Calibrator : invalid number of startupPosition params 
Torso_Calibrator : invalid number of startupPosition params 
Left_Arm_Calibrator : invalid number of startupPosition params 
Right_Arm_Calibrator : invalid number of startupPosition params 
Left_Hand_Calibrator : invalid number of startupPosition params 
Right_Hand_Calibrator : invalid number of startupPosition params 
One or more devices failed opening... see previous log messages for more info

**Comment by gregoire-pointeau** [comment]
Full log is:

[log_25_08_2016.txt](https://github.com/robotology/icub-support/files/437050/log_25_08_2016.txt)

**Comment by pattacini** [comment]
@gregoire-pointeau try to use labels to identify the robot instead of specifying the robot name within the title of the issue :wink: 

Here are the [**guidelines**](https://github.com/robotology/icub-support/blob/master/.github/CONTRIBUTING.md) to post to `icub-support`.

**Comment by gregoire-pointeau** [comment]
After @julijenv update, new log: 
[log_25_08_2016.txt](https://github.com/robotology/icub-support/files/437360/log_25_08_2016.txt)


@pattacini I'll do ! (but in between icub-main, and icub-support I'm not always allowed to change labels, this is why I didn't do it here. But now, I know, don't worry !)

**Comment by pattacini** [comment]
@gregoire-pointeau yeah, users can **assign labels** only in [`icub-support`](https://github.com/robotology/icub-support) and [`Q&A`](https://github.com/robotology/QA), because  `write` permissions is required to do that and we tend to be not that _generous_ with `yarp` and `icub-main` repos :wink:

**Comment by julijenv** [comment]
After a complete update, always try to laucnh the robot from the main repostirory (in that case @randaz81  made some modifications in your config files which didnt allow you to start with your old config files).

**Comment by gregoire-pointeau** [comment]
Robot starts and all joints respond.
However the calibration is not perfect (the arms aren't aligned very well).

[log_29_august_12h45.txt](https://github.com/robotology/icub-support/files/442232/log_29_august_12h45.txt)

**Comment by gregoire-pointeau** [comment]
After a fine calibration, everything went back to normal.
Thanks !
