### ISSUE TITLE
Skin fingertips hardware failures

### ISSUE THREAD

**Issue by martz21** [robotology/icub-support#29]
Hi!

The fingertips tactile sensors of our iCub are not working properly: they are functioning only sometimes, apparently at random, and in any case, in the few times they are up, a big pressure must be applied in order to have some useful signals out of them. 
It was suggested that this issue sounds like probably broken pcb.
Do you have any suggestions on how to proceed?

Thanks,
Martina

**Comment by martz21** [comment]
Please find attached the pictures required!
I hope this helps

LEFT HAND
![left_hand](https://cloud.githubusercontent.com/assets/7202439/8037084/b891db88-0df3-11e5-89bc-fb3103a1839b.jpeg)
![left_hand_board](https://cloud.githubusercontent.com/assets/7202439/8037085/b891f474-0df3-11e5-8a38-cede5e159e93.jpeg)
![left_hand_ft](https://cloud.githubusercontent.com/assets/7202439/8037088/b894a57a-0df3-11e5-86d7-362e2549e6c4.jpeg)

RIGHT HAND
![right_hand](https://cloud.githubusercontent.com/assets/7202439/8037086/b893e68a-0df3-11e5-9cd3-c3a3dd090137.jpeg)
![right_hand_board](https://cloud.githubusercontent.com/assets/7202439/8037087/b8944a94-0df3-11e5-8b25-013da84c9275.jpeg)
![right_hand_ft](https://cloud.githubusercontent.com/assets/7202439/8037089/b89522fc-0df3-11e5-892a-a6079b172875.jpeg)

**Comment by Tobias-Fischer** [comment]
Hi,
I just wanted to follow up whether you have an idea what the problem might be?

Thanks,
Tobias

**Comment by martz21** [comment]
Hi!

We tried to unplug and plug the boards on the knuckles, however nothing changed: the fingertips are only working irregularly. 
How sensitive are the fingertips supposed to be? If we try to only slide on surfaces, it looks like they never get activated (the skinGui does not show any activity).

Any suggestion you could give will be greatly appreciated. Thanks in advance.
M.

**Comment by maggia80** [comment]
We will check the fingertips once we will have the arm here in IIT

**Comment by martz21** [comment]
Yesterday I tried the tactile sensors: in the first trial the fingertips were giving some signals when a certain pressure was applied, but after this first trial, they were not giving any signal, like they didn't get activated anymore. Did you experience this behaviour before?

**Comment by maggia80** [comment]
We have found an issue in the flexible pcb of the fingertips. We discovered broken traces in some fingertips due to fabrication process. And the bad thing is that they breaks in such a way they still work in some conditions. I can not say if the problem you have experienced is due to this issue or a broken wire , but I can tell you that as soon as we will have your arm we can check on it the status of the fingertips.

**Comment by martz21** [comment]
Is there a way we can check here if the problem is related to the pcb or to some connections?

**Comment by Tobias-Fischer** [comment]
The reason @martz21 asks is, that https://github.com/robotology/icub-support/issues/31 is now resolved, and therefore we do not necessarily need to ship the arm back. So maybe it would be possible to replace the PCB's you are referring to ourselves? If not, which part of the iCub do you suggest to ship back? The forearm?

Best, Tobias

**Comment by julijenv** [comment]
Hi iCubLondon01 users,
As it has been said previously by @maggia80 , some trace connectedd directly on the wire pads of the fingertips pcb are really easily breakable.
left fingertip pcbs
![p1040032](https://cloud.githubusercontent.com/assets/7140395/8676242/945f4d1a-2a48-11e5-884a-a0536b73bad1.JPG)
right fingertip pcbs
![p1040024](https://cloud.githubusercontent.com/assets/7140395/8676262/b51135a0-2a48-11e5-9bdc-e928b5447df8.JPG)
To try to restore the pcbs, you will need a very powerful magnifying lens and a sharp knife tip or cutter.
remove a bit of insulation copper (green) above the thin line of power (K pad) on the pcb
and put some soldering paste on it to gete a better contact.
left pad
![left_pad_resoldered](https://cloud.githubusercontent.com/assets/7140395/8676731/8ecdcbee-2a4b-11e5-96c8-26a9e045642a.png)
right_pad
![right_pad](https://cloud.githubusercontent.com/assets/7140395/8676740/95ffc944-2a4b-11e5-8e70-970db1b2ddcf.png)
Let us know, if you make it.

**Comment by martz21** [comment]
Hi! Thanks for the previous message.
Are the boards you mention the small ones (5 in total) on the knuckles?
Can they be taken off completely from the hand to make this work?
Thanks in advance for your help.

**Comment by julijenv** [comment]
No, the pcb on the pictures are the ones on the fingertips itselves- just remove the nail and you should see it.
best of luck if you try it out!

**Comment by martz21** [comment]
Hi! We had a look at the boards as you suggested but we are not sure whether the boards are the same (they seem to look different); also, we cannot tell if the problem is the same that you showed in your pictures. I upload below the pictures we took from one of our fingertip board.
Please let us know if the pictures give you any hint regarding the problem.
Thank you in advance!

![1308161998245](https://cloud.githubusercontent.com/assets/7202439/8751197/923cf49e-2ca3-11e5-810b-e7f84d7636d3.jpg)
![1308162013502](https://cloud.githubusercontent.com/assets/7202439/8751196/923ca7c8-2ca3-11e5-9f25-8254c94fa88d.jpg)
![1308162014182](https://cloud.githubusercontent.com/assets/7202439/8751198/923dfe48-2ca3-11e5-8058-f130c1e922c0.jpg)
![1308162051843](https://cloud.githubusercontent.com/assets/7202439/8751195/923b82e4-2ca3-11e5-9106-4808242114a9.jpg)
![1308162051963](https://cloud.githubusercontent.com/assets/7202439/8751200/924b3662-2ca3-11e5-963c-6beeafd9322e.jpg)
![1308162056194](https://cloud.githubusercontent.com/assets/7202439/8751199/9248b18a-2ca3-11e5-8dce-99dffd38af55.jpg)

**Comment by maggia80** [comment]
Hi,

The circuit is the same. You do not see the break in the trace, it is weird but where is the red circle in the picture below, there could be the break. You should as Julien wrote you remove the green solder mask and solder over the trace. If just a couple of fingertips have this issue none of them are working. Because they share the same bus. 

![923cf49e-2ca3-11e5-810b-e7f84d7636d3](https://cloud.githubusercontent.com/assets/6987330/8794077/9310dea6-2f7f-11e5-9158-d260d421625a.jpg)

**Comment by Tobias-Fischer** [comment]
Hi all,
Through some mystery, our fingertips seem to work fine nowadays. I have the feeling that changing the `yarpserver` to run on our desktop machine rather than `ikart` seemed to have improved the detection of touches on the fingertip (for some weird reason, maybe it just randomly works better). Do you think we can close this issue, @martz21?

Best, Tobias

**Comment by maggia80** [comment]
I dont think so. However I have recently updated the firmware of the boards reading the fingertip. You should install it thought the canLoadere application. The parameters are cfw002 CAN NET 7 and 8 and the firmware is in the icub-firmware-build git repo, skin.hex

**Comment by Tobias-Fischer** [comment]
Hi @martz21,
we just tested the fingertips again and they are working fine now. Can you please close this issue?

Thanks, Tobi
