### ISSUE TITLE
Change Ethernet connector on the head 

### ISSUE THREAD

**Issue by AnneLaureM** [robotology/icub-support#292]
Hello iCub-Support

A few months ago, we had some contact failures with the Ethernet cable of the iCub, so we have improvised a fix with our available material at INSERM and we have changed the connector on the head of the iCub.
![2016-09-09 17 03 32](https://cloud.githubusercontent.com/assets/7047323/18393180/b73e4f3e-76b4-11e6-93e4-ad49905bc501.jpg)

But we think it will be better to repair correctly the connector.
Do you think it will be possible to send us a new connector and some crimps ?

Cheers,

Anne-Laure
cc @gregoire-pointeau

**Comment by julijenv** [comment]
feedback about that? can I close?
@gregoire-pointeau , @AnneLaureM

**Comment by AnneLaureM** [comment]
We have received the connector. Thanks !
