### ISSUE TITLE
iCub power supply not working

### ISSUE THREAD

**Issue by AlexAntn** [robotology/icub-support#293]
iCub power supply is no longer working, for iCubPlymouth01

Upon turning on the iCub power supply, after summer break, we heard a snap. Upon closer inspection of the power supply, we noticed the lower box was not presenting any voltage numbers (was, effectively, off).

Checking the fuses on the power plugs, both fuses are ok.

**Comment by vtikha** [comment]
@AlexAntn, sorry for the late reply. Could you please send us some pictures (front and back) of the power supplies you have, in particular the lower box? We will try and determine a few things and take it up from there.

**Comment by AlexAntn** [comment]
Update:

Today we opened the power supply unit, to check for any blown fuse. We found the fuse on the front-right to be blown, so we replaced it and turned it on again.

Upon turning on, the new fuse was also blown, so we assume there is some short-circuit on the PSU itself.


How can we replace it? 


Details on the current non-working PSU:
XFR-2.8Kw-60-46, Xantrex, - Power supply, 2,8 Kw, 0-60V, 0-46A, 89x430x534mm, 15kg, 19" rack mount, 2U
Order code: XFR-2.8Kw-60-46

**Comment by AlexAntn** [comment]
Pictures of the Power Supply Unit:
(Lower unit is the broken one)

Front:
![img_20160916_144906](https://cloud.githubusercontent.com/assets/9463167/18588238/89bb8d38-7c1d-11e6-8b4b-114c367fb0d3.jpg)

Rear:
![img_20160916_144920](https://cloud.githubusercontent.com/assets/9463167/18588239/8b5eae04-7c1d-11e6-93db-9f33c0ed8ad8.jpg)

Detail on top:
![img_20160916_144933](https://cloud.githubusercontent.com/assets/9463167/18588243/8cb59c0e-7c1d-11e6-976d-ab61b9f12bf3.jpg)

Detail on front:
![img_20160916_144951](https://cloud.githubusercontent.com/assets/9463167/18588245/8df018b0-7c1d-11e6-9b07-46f29a523c72.jpg)


Thanks @vtikha !!

**Comment by vtikha** [comment]
@AlexAntn thanks for the update and pics, we will get back to you asap.

**Comment by vtikha** [comment]
@AlexAntn unfortunately it is busted 👎 . I sent you an email containing all the details necessary for you to proceed.
