### ISSUE TITLE
Accelerometers of the black iCub's hands affect tactile response

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#297]
### Description of the failure

The accelerometers of the black iCub's hands, if enabled, affect the tactile response of the hands themselves.
### Detailed conditions and logs of the failure

The problem occurs when the accelerometers are enabled (through the iCub_*.xml file read by yarprobotinterface). They work properly, but the tactile response becomes very very noisy (it basically becomes useless) on the index and middle fingers, sometimes also on the thumb and on the palm. Even when it is not noisy (mostly ring and little fingers), it doesn't work properly, sometimes there is some delay, sometimes it freezes.
Disabling the accelerometers everthing goes back to normal.

**Comment by maggia80** [comment]
we should check the low level firmware. I would suggest to connect a USB/CAN converter and read the messages sent by robotinterface, and than send the messages to the board in a different order (i.e. activating only the accelerometer and only after the skin or viceversa)

@julijenv
