### ISSUE TITLE
Problems on the tactile sensors of the hands

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#3]
@alecive, @massimoregoli, @pattacini reported that the tactile sensors on the hand do not always work after startup. 

In particular we noticed that if the palm is pressed at startup the fingertip reach saturate to max value and never come back. This suggests a hardware issue.

**Comment by lornat75** [comment]
@maggia80

**Comment by maggia80** [comment]
I am working on a board that will be mounted on top of the mais. The board will give us the possibility to test each individual fingertip without unsolder anything. This is because we are having a lot of problems with the fingertips in this period and the debug (even with the skin diagnostic enabled) is complicated.

**Comment by maggia80** [comment]
next week we will received the boards, and we will test it on the new hands (2.0) of the black robot.

**Comment by bhigy** [comment]
Have there been any update on this? Today, I noted issues on both hands. 

On the left one, the palm is not working. 

On the right one, the fingertip of the middle finger is not working while the thumb, the index and the ring fingers stopped working after a few minutes. Also, there were artifacts on the little finger (it was flickering even though I didn't touch it).

**Comment by super-ste** [comment]
This issue will be addressed once we have some proof the new board as per issue #33 is resolutive.

**Comment by lornat75** [comment]
Issue #33 was closed. Can we close this issue too?

**Comment by bhigy** [comment]
Right hand fingertips were still not working a few days ago.

**Comment by massimoregoli** [comment]
I didn't experience this issue anymore, it's probably due to recent firmware updates. I guess we can close it.
