### ISSUE TITLE
Joint 5 and 6 unresponsive/broken

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-support#303]
### Description of the failure
Joints 5 and 6 of the left arm are not responsive and cause blocks and failures of the black iCub during common tasks.

### Detailed conditions and logs of the failure
The black iCub is currently unreliable to normal usage.
@julijenv and @spada1978 are aware of the issue.
Further investigation for possible other problems to the left arm are needed.

cc: @tanismar

**Comment by julijenv** [comment]
it has been replaced the 2 motor joint 5 and 6, IITCODE 4471.
the right forearm is now working properly

**Comment by tanismar** [comment]
great! thanks a lot!
