### ISSUE TITLE
Broken pole lock, replacement request

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#306]
### Description of the failure

The cable of the pole lock is broken.

### Detailed conditions and logs of the failure
As in the picture below, the cable connecting the lock (see red circles) of the pole is broken. 

![broken_lock](https://cloud.githubusercontent.com/assets/7060968/19264791/896cecd0-8fa2-11e6-97bc-fe9000758559.jpg)

Since we are not able to repair this kind of cable, we would like to ask if it is possible to have a replacement of the piece of cable? 
Thanks!

**Comment by julijenv** [comment]
hi @hu-yue ,
we will build a new one and send it to you.
best regards , Iwill let you know, please close the issue when you will remounted it.

**Comment by hu-yue** [comment]
@julijenv Sure, I wait for your update then! Thank you very much!

**Comment by spada1978** [comment]
hi
 I realized the pole cable.
if I communicate the shipping address, you will be sent as soon as possible

**Comment by hu-yue** [comment]
@spada1978 Thank you very much! 
The shipping address is as follows:
Yue Hu, 
ORB, Heidelberg University 
Berliner Str 43, 
69120, Heidelberg
Germany

**Comment by hu-yue** [comment]
@spada1978 @julijenv the cable has arrived and we have already mounted the lock back to the pole. Closing the issue.Thanks again!

**Comment by spada1978** [comment]
Perfect...
see you
