### ISSUE TITLE
Right hand needs check 

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#312]
### Description of the failure
A small cable and a plastic holder fell down from the right hand.

### Detailed conditions and logs of the failure
Performing tool use experiments, the robot touched the table some times, a few of them with a slight pressure. It seems that everything is working, and indeed I could finish the experiments, but maybe a cable of some of the small fingers (pinky or ring finger) broke. The two pieces that fall off are in the table in front of the black icub.

**Comment by spada1978** [comment]
checked right wrist occurred cable break The 45 mm.
it was decided to replace
