### ISSUE TITLE
iCubGenova04 (green): right and Left thumb abduction encoder have discontinuous reads

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-support#319]
@julijenv has already seen the problem: he tried to move the encoder, but it is stuck.

**Comment by julijenv** [comment]
Hi @valegagge ,
The magnets have been rotated in order to be on a full range to calibrate correctly.
Did the calibration went alright?
if evrything went well I would like to close the sissue thx

**Comment by valegagge** [comment]
issue fixed
