### ISSUE TITLE
Need to change cable 8 (right_arm) that has been squeezed during tests to solve the #308 issue

### ISSUE THREAD

**Issue by misaki43** [robotology/icub-support#325]
Hello @julijenv and others,
Yesterday we tried to solve the #308 issue, and we have manipulated parameters and matrix of the the right arm. At some point, the arm has done a bad movement and the cable 8 moved and has been squeezed.
I send you some [pictures](https://github.com/robotology/icub-support/files/578406/icub_cable_broken.zip) of this cable, can you help us to repair it please

? 

Thanks, 

Oriane

@serena-ivaldi @dogoepp @marcoaccame @olivierrochel-inria

**Comment by julijenv** [comment]
nothing to worry about, the cable was pinched but in any way broken, or worn.
they recabled it and everything went alright
