### ISSUE TITLE
Neck tendons broken

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#326]
### Description of the failure

Neck tendon broken

### Detailed conditions and logs of the failure

While testing new control algorithms for balancing, the robot fell and the shock on the head made the tendon break.

@julijenv @spada1978

**Comment by DanielePucci** [comment]
@francesco-romano @S-Dafarra

**Comment by spada1978** [comment]
replaced the cable B IIT code 5964 and performs the wiring again
