### ISSUE TITLE
problem with fingertips

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#33]
@bhigy @massimoregoli can you add more details?

**Comment by pattacini** [comment]
Last week I sent a failure report to @robotology/icub-support-admin (through email) about the following issues:

- Left hand fingertips do not work.
- Right hand fingertips undergo frequent freezing.

@super-ste is working on it right now.

/cc @giuliavezzani

**Comment by bhigy** [comment]
On the left hand, the fingertips of the thumb, index, middle and little finger are not working.
On the right hand, the palm and the fingertips of the ring and little finger are not working.

**Comment by maggia80** [comment]
We have fixed the lefthand. Let me know if you find any other issue in the left fingertips. I will update about the status of the right hand soon.

**Comment by pattacini** [comment]
so far so good...

**Comment by pattacini** [comment]
@maggia80 @julijenv 
at certain point we'd need to schedule the same upgrade on the right hand.

**Comment by maggia80** [comment]
see #19
