### ISSUE TITLE
Broken right shoulder tendons

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-support#331]
### Description of the failure
Broken right shoulder tendons (4 and 5).

### Detailed conditions and logs of the failure
Tendons broke upon launching an application to move iCub right arm to an initial position.

**Comment by spada1978** [comment]
Sostituito cavo n.4 e n.5 codice IIT 4761.1 e 4762.1.
Sostituito n.1 tensionatore codice IIT 3842 e inserito n.1 vite TCEI 2,5 x 10 codice 2433.
Effettuato cablaggio meccanico
