### ISSUE TITLE
Confirming skin version number of our iCub

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-support#344]
@gsaponaro commented on [Thu Dec 15 2016](https://github.com/robotology/QA/issues/174)

Hi, having read [here](http://wiki.icub.org/wiki/Tactile_sensors_(aka_Skin)) that there exist different versions of the iCub skin, we'd like to know which particular type is mounted on `iCubLisboa01`. For reference, this skin was installed during summer 2014.

/cc @randaz81 @maggia80 @vicentepedro https://github.com/robotology/QA/issues/39

---

@pattacini commented on [Thu Dec 15 2016](https://github.com/robotology/QA/issues/174#issuecomment-267414097)

cc @robotology/icub-support-team

**Comment by pattacini** [comment]
Hi @gsaponaro 

Could you take some pictures of the wrist in particular and post them here, so that @julijenv will be able to give you a certain answer?

**Comment by gsaponaro** [comment]
Thank you, here it is:

![img_20161221_171608-resized](https://cloud.githubusercontent.com/assets/6716962/21399009/bb9239cc-c7a1-11e6-8eab-0a411c0b45b9.jpg)

**Comment by julijenv** [comment]
Hi @gsaponaro , could you please take a picture of the palm as well.
The skin part of the upper forearm is V1. and the other part of the forearm never changed sicne the beginning so it is V1, wait for a picture to tell you which version of the palm skin u havfe

**Comment by gsaponaro** [comment]
Sure. I removed part of the glue (but not all) to lift part of the palm cover, is the picture below clear enough?

![img_20161221_174340](https://cloud.githubusercontent.com/assets/6716962/21399938/aea46452-c7a5-11e6-8325-49e3e686893b.jpg)

(Top number says P23.)

**Comment by julijenv** [comment]
palm V2

**Comment by gsaponaro** [comment]
Great, thanks.
