### ISSUE TITLE
fingertip came loose

### ISSUE THREAD

**Issue by frank-foerster** [robotology/icub-support#346]
### Description of the failure
Our iCub's fingertip came loose today as depicted on the image.

### Detailed conditions and logs of the failure

My simple question: can we just fix it by glueing it back to area that I marked with the red oval
using superglue, or do I need to use some special glue for this.
Or is there another solution not requiring any glue.

![icub_loose_fingertip](https://cloud.githubusercontent.com/assets/16962752/21646751/5487da9a-d28f-11e6-9479-a06d50d59b9e.JPG)

Many thanks.

**Comment by julijenv** [comment]
Hi @frank-foerster ,
we usually glue this plastic bit of the fingertipskin on the pcb thanks to a repair extreme glue from pattex:
here is one example the price and where to get it in UK:
https://www.amazon.co.uk/Pattex-Repair-Extreme-Power-Glue/dp/B000WL3KR2
LEt us know if you cant find it

**Comment by frank-foerster** [comment]
Thanks, that was what I wanted to know.
