### ISSUE TITLE
Ethernet connector in the backpack is lousy 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-support#352]
### Description of the failure
The ethernet female connector in the backpack is lousy, i.e. the ethernet male connector can be detached even without touching the connector tab. 

### Detailed conditions and logs of the failure
While operating the robot, I lost connection with `icub-head` because the ethernet connector was lousy.

**Comment by traversaro** [comment]
It happened again today @nunoguedelha .

**Comment by traversaro** [comment]
@julijenv During our face to face meeting, I forgot to mention this, it is actually quite problematic.

**Comment by nunoguedelha** [comment]
Has been fixed by @julijenv. Closing the issue.
