### ISSUE TITLE
Right hand cable broken

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#357]
Dear @julijenv, 

We are missing you in Erzelli! :D 

The right hand thumb cable is broken - as the yarpmotorgui is not working I cannot tell you which joint, but I send you the photo attached. 

It is strange that it's broken because since before Christmas nobody has touch the robot and it was working. Maybe some of the cables are touching..? (as you may see in the photo, the cable is very long, it broke at the beginning!)

We are planning to run some experiments in the coming days.. is it possible for you to come?

Thanks a lot!
Alex.

![img_20170113_160715](https://cloud.githubusercontent.com/assets/11769446/21934827/3715774c-d9ab-11e6-98d2-ec98d5424b87.jpg)

**Comment by amaroyo** [comment]
@julijenv 

Left hand thumb cable broken. You can find which one is it! The thumb is totally blocked, even in idle position. I havent used the left hand at all, only at calibration.

![img-20170120-wa0003](https://cloud.githubusercontent.com/assets/11769446/22143709/453acf70-defb-11e6-8420-95ccba62e9f8.jpeg)

**Comment by julijenv** [comment]
Hi @amaroyo ,
it is the proximal joint (j9).

**Comment by julijenv** [comment]
closing issue,
It has been rewired both thumb proximal joint (j9) and mounted the new dorso cover.
material used for the repair:
IITCODE Qta Description
1815 x 5m : carlstahl 0.63mm
2391 x 5m : carlstahl 0.45-0.61mm
