### ISSUE TITLE
Left camera disconnects sometimes

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#360]
### Description of the failure
Left camera disconnects randomly

### Detailed conditions and logs of the failure
While working on the robot, camera left disconnected.
Sometimes, connection can be restored by rebooting the robot.

**Comment by julijenv** [comment]
Hi @giuliavezzani ,
we will have a look at it ASA the robot will be available for the team to work on it

**Comment by towardthesea** [comment]
I think it was solved!

**Comment by julijenv** [comment]
From what i recall the ribbon flat cable has been changed
