### ISSUE TITLE
VGA cable needed

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-support#362]
Hi @julijenv,
It would be great if you could send us a VGA cable for debugging the PC104, as it seems we need one to debug the new icub image (see https://github.com/robotology/QA/issues/177).
Thanks a lot,
Tobi

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
unfortunately we dont have any european project going on together, so I guess you will have to create your own.
you could find the way to create the VGA cable to PC104 by looking to:
#183 and #299 
if too lazy to look for it I recopy the link ;)
https://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/doc/howTo/Connect_VGA_to_PC104.pdf
Let me know,

**Comment by pattacini** [comment]
@julijenv WYSIWYD is considered already over?

**Comment by julijenv** [comment]
@Tobias-Fischer @pattacini ,
WYSIWYD is over, but in our great generosity, we will send you one VGA cable to PC, that was around, consider this as a favor and a lucky day for you that I have it, or else you would have had to make it :D:D:D:D.
Please give us a shipping address, the personn to receive it and his phone number.

**Comment by Tobias-Fischer** [comment]
Hi @julijenv, thanks a lot, that's highly appreciated :)! Glad you have a spare cable around.
This is the shipping address:

Tobias Fischer
Level 1 Stores
Electrical Engineering Department
Imperial College
London, SW7 2BT
United Kingdom

Delivery Contact: Hisham Maarki - +44 020 7594 6162

Thanks a lot :)
Tobi

**Comment by Tobias-Fischer** [comment]
I have no idea how you've done it, but the cable arrived already. You're a star! Thanks a lot :)

**Comment by pattacini** [comment]
Julien is Julien 😉

**Comment by julijenv** [comment]
hope it works, :D:D:D:D
