### ISSUE TITLE
Testing ATI 45 sensor on iCubGenova04

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#367]
Description:
Due to some estrange external forces that appear during the use on the robot, which should not be there, a test considering a commercial robot on the iCub was programmed. 

This requires the replacement of a sensor on the iCubGenova04 by the ATI 45 with serial number FT18003NET. The sensor changed is the left upper leg sensor SN272.

**Comment by julijenv** [comment]
hi @fjandrad ,
Is it done???

**Comment by fjandrad** [comment]
Done thanks for the help

**Comment by fjandrad** [comment]
Results where reported in 
https://redmine.robotology.eu/issues/1453
