### ISSUE TITLE
Testing screw loosness on the FT sensors

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#368]
Description:
Due to some estrange external forces that appear during the use on the robot, which should not be there, a test considering different values of torque for screwing the FT sensors was programmed.

This requires the dismount and mount of a sensor on the iCubGenova04 repeatedly changing the values of the torque used to screw it. The sensor changed is the left upper leg sensor SN272.
The values to be tested are from 2Nm to 0.5Nm.

Remark: 2Nm seems to be on the limit for the kind of screws used on the interface of the sensors.

**Comment by julijenv** [comment]
is it done, now?????
@fjandrad
