### ISSUE TITLE
Torso oscillations 

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#370]
### Description of the failure
Torso of `iCubDarmstadt01` (**now in Genova**) oscillates in the `(0,0,0)` position

### Detailed conditions and logs of the failure
If we set different torso joints value, the oscillations descrease.
However if we move the robot torso, the oscillations start again.

More information are available here: https://github.com/robotology/QA/issues/147
In addition, @julijenv and @spada1978 already tried to fix it when it was in Darmstadt

**Comment by randaz81** [comment]
ki pos too high?

**Comment by giuliavezzani** [comment]
thanks @randaz81 for the help!
It seems that setting **`ki=0`**  for **`torso join no.2`**  solves the problem!
We will test tomorrow if this change is enough even while we normally use the robot.

**Comment by giuliavezzani** [comment]
Today torso **seems to be stable** even **without decreasing** the `ki` value for torso joint no.2

**Comment by giuliavezzani** [comment]
We tested how torso behaves while moving during `depth2kin` and with manual movements from `yarpmotorgui` and **`ki=0.0`** for **torso joint no. 2**. It works well, so I modified the configuration file for the torso in the .local.
Thanks @randaz81!
