### ISSUE TITLE
Problems in left camera

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#372]
### Description of the failure
Sometimes,  left camera is not working.
If I play with the `yarpmotorgui` changing the value of eye version of the left, I got some strange images on the left camera.

### Detailed conditions and logs of the failure
It's likely then there's a problem with the firewire cable connecting the camera to PC104. Due to wear and tear and the fast movements of the bulb it tends to become loose.

More details are available [here](https://github.com/tacman-fp7/handover/issues/22).

**Comment by giuliavezzani** [comment]
Solved! Thanks @julijenv

**Comment by julijenv** [comment]
it has been changed the flat cable (IITCODE 356).
