### ISSUE TITLE
Eyes need to be calibrated

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#377]
### Description of the failure
The `iCubDarmstadt01` eyes are in strange positions

### Detailed conditions and logs of the failure

![eyes](https://cloud.githubusercontent.com/assets/9597070/21267039/d26b976c-c3a8-11e6-879c-d35b4230b7bd.jpg)

**Comment by julijenv** [comment]
Hi @giuliavezzani ,
I agree with you that it isnt beautiful, but unfortunately as long as the to camera point in the same direction, so far so godd.
Please check if the tilt of every camera is aligned.
thx

**Comment by giuliavezzani** [comment]
Point clouds seem to be very good :) 
I think we can use the eyes like that.
Thanks!
