### ISSUE TITLE
Files on the head Linux PC disappear when you reboot.

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#383]
Files added to the Linux filesystem of the head PC disappear after reboot.

@francesco-romano
@maggia80 @julijenv
@Fabrizio69 @davidetome 
@mbrunettini

**Comment by lornat75** [comment]
This happens when the SSD drive is configured as read-only. The picture shows how to correctly configure it as "read-write".

![switch](https://cloud.githubusercontent.com/assets/1403333/22519669/8960f25a-e8b1-11e6-9f7f-9a515053f79f.jpg)

**Comment by davidetome** [comment]
@lornat75 the switch is always set in RW mode when the robots leave the production, otherwise we won't be able to burn the OS on it! May be it has been accidentally switched later..

@Fabrizio69
