### ISSUE TITLE
Left shoulder broken

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#388]
### Description of the failure
Left shoulder tendons are broken

### Detailed conditions and logs of the failure
Possibly, it was caused by new testing PID gains values.

**Comment by julijenv** [comment]
the robot had the shoulder cables  N1 and N8 broken as well as the the elbow AEA connector and wires tear apart,
IITCODE Qta Descrition
4758.1 x 1 : cable shoulder #1
4765.1 x 1 : cable shoulder #8
1895 x 1 : left pulley crimkp cover
