### ISSUE TITLE
Graphic interface frozen on icub21 and icub22

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-support#394]
It happens sometimes that the ubuntu graphic interface freeze while showing multiple desktops on laptop **icub21** and **icub22**.
Any tips for resolving it?

cc @claudiofantacci

**Comment by claudiofantacci** [comment]
When it happens, you can try to unfreeze the PC by keeping pressed the **Windows+ALT+F1** (Windows or equivalent button) while clicking with the mouse.

This problem is quite strange, but eventually you can recover from it without rebooting the PC.

**Comment by traversaro** [comment]
This just happened to @gabrielenava @MartaLorenzini on the `icub24` laptop on the `iCubGenova02` setup, running on Ubuntu 16.04 . It is quite a serious problem, has the average user has **NO** idea on how to restore the laptop to a working state. Even in this case, we had to look up to this issue to find the solution.

**Comment by claudiofantacci** [comment]
The next Ubuntu release will roll back to Gnome as default DE.
I think we will also benefit from it 😄

**Comment by randaz81** [comment]
in case `Windows+ALT+F1` does not work, try `ALT+ENTER`.

**Comment by traversaro** [comment]
Happen also today on iiticubws014 .

**Comment by traversaro** [comment]
It happened also today.
