### ISSUE TITLE
Right hand fingers not working

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#411]
Please **fill in the following two sections** and then **remove any comment and/or remark become unnecessary**:

### Description of the failure

Some fingers from the right arm (namely midle, ring and pinky) seem not to respond to any command, even when sent from yarpmotorgui.

### Detailed conditions and logs of the failure

Error was already present when I started the robot.

---
**Remark**: if you are not a daily icub-support user, please read carefully the guidelines for contributing linked at the top of this page. In particular, the **name of your robot** must be always indicated: either using **labels** if you're already a contributor, as per standard, or by specifying it while detailing the issue.

**Comment by spada1978** [comment]
made new crimping of electric motors can 5 cavbi right forearm card
