### ISSUE TITLE
Right ring finger does not reach full open position

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-support#416]
### Detailed conditions and logs of the failure
The right ring finger does not fully open while trying to reach 0 degrees.

It does not seem to be related to issue [400](https://github.com/robotology/icub-support/issues/400) where the ring finger was closing again after reaching the fully open position.

**Comment by julijenv** [comment]
it has been recalibrated the pinky finger and everything went back to almost stretched last 2 fingers.
