### ISSUE TITLE
fingertips on iCub purple do not work

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#42]
Massimo @massimoregoli noticed the following problems with the fingertips:

- Left hand: thumb not working, one taxel of the other fingertips get max activation
- Right hand: strange noise on middle and thumb

@maggia80

**Comment by maggia80** [comment]
we are preparing two fingertips and we will mount them to replace the two faulty one.

**Comment by lornat75** [comment]
What is the status of this issue?

**Comment by maggia80** [comment]
as far as I know we can close it
