### ISSUE TITLE
Right thumb proximal joint not working

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#422]
### Description of the failure

The tendon of the right thumb proximal joint is broken.

**Comment by julijenv** [comment]
repaired by alessandro,
please @spada1978 ,
add the piece used to repair it and close the issue thx

**Comment by spada1978** [comment]
replaced broken cable and again carried out the mechanical proximal wiring

**Comment by spada1978** [comment]
è stato utilizzato 1 m di cavo codice iit 1815
