### ISSUE TITLE
Facial expression module doesn't work

### ISSUE THREAD

**Issue by claudia-lat** [robotology/icub-support#423]
The facial expression module has got a problem in reading from the serial port.

**Comment by julijenv** [comment]
Hi @claudia-lat ,
went there to check other issues, and find out that depending on the connection with the power line we can see on dmesg ¦ tail the main face expression board respond but unfortunately the facial expression light and motor movement dont do anything.
Ill try next time to plug the USB to one of the 2 other USB plug to test the compatibility

**Comment by julijenv** [comment]
Hi @claudia-lat ,
everything seems alright for now, I close it, if ever neeeded let's reopen it

**Comment by claudia-lat** [comment]
thanks!

**Comment by S-Dafarra** [comment]
The software modules seem to open correctly, but I can't see any light and the eyes don't blink.

**Comment by S-Dafarra** [comment]
Facial expressions seem working. It was probably related to missing flags.
