### ISSUE TITLE
Head cable detached

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#425]
Hello @julijenv, 

We are testing the new cover for the face of the iCub. I just opened the head and I found a cable detached. I wanted to ask you if the cable should be attached again to the board of if it's superfluous. Please, take a look to the photo below.

Thanks a lot, 
Alex

![img_20170314_142429](https://cloud.githubusercontent.com/assets/11769446/23903981/a652af9a-08c6-11e7-834c-b2b605a2027f.jpg)

**Comment by julijenv** [comment]
Hi @amaroyo ,
the connector could be plugged but mainly it is useless as long as the other board below wworks fine, we could say that it is a spare part and to do not interfere some times to the rest of the boards we dont connect it.
you can close the face cover and forget about it ;)
