### ISSUE TITLE
icub head cable A broken

### ISSUE THREAD

**Issue by Arya07** [robotology/icub-support#429]
### Description of the failure
During normal usage of iCub head the cable snapped when the head was moving
The cable in question is cable A.

**Comment by spada1978** [comment]
A replaced the cable and made the mechanical neck harness again
replaced the two grains 2 x 2 and the magnetic plate cord grip

**Comment by spada1978** [comment]
n.1 cavo A codice 5965
n. 2 grani 2 x 2 codice iit 1839
n.1 vite 2,5 x 10 codice IIt 2433
è da scaricare pertanto sulla commessa n.1450
