### ISSUE TITLE
Left and right hand skins not working

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-support#430]
Left and right hand skins are unresponsive.

You can test them using the Skin_GUI_All applications.

**Comment by julijenv** [comment]
Hi @claudiofantacci ,
To me nothing to declare for the left arm, everything looks alright,
for the right arm instead we found one MTB board with a different FW and not responding, and also 1 fingertip which gave some issue and on which I will tackle the issue soon. For the time being I just remove the switch board to prevent the fingertip to disturb the other patch of the hand skin.

**Comment by claudiofantacci** [comment]
Thanks @julijenv ,
yesterday both hand skins were not working.
Did you tested the left hand skin?

**Comment by julijenv** [comment]
I did either the forearm , palm and fingertip for the left arm, was one part of those not functionning during your test, yesterday?

**Comment by claudiofantacci** [comment]
Yes, the left hand skins (including fingertips) were not working.

I just tested them again and they are working properly, but the middle fingertip.

**Comment by julijenv** [comment]
you mean but the middle fingertip of the RIGHT hand I presume???
the middle left was working this morning?!?!

**Comment by claudiofantacci** [comment]
Sorry Julien, my bad.

I'll start from the beginning 🙃 

The LEFT hand is working just fine.
The RIGHT hand is working fine, but for the middle finger.

**Comment by julijenv** [comment]
i know i ll take care of it ;P

**Comment by julijenv** [comment]
been changed 
IITCODe Qty Description
1466 x 1 : iCub, subassembly - Fingertips for right hand, middle finger, address 1, with lycra
