### ISSUE TITLE
Right hand middle distal spring is loose - which is the correct replacement?

### ISSUE THREAD

**Issue by gsaponaro** [robotology/icub-support#435]
### Description of the failure

After manipulation experiments, we noticed that the right middle distal spring is loose (joint 14, r_middle_distal), in particular at the "falangina" physical joint.

We have the following spare, we just need a confirmation that this is the correct spring for that phalanx or not:

![img_20170329_142153](https://cloud.githubusercontent.com/assets/6716962/24456600/6a6c672a-148b-11e7-8b48-58ea76640094.jpg)

Thanks.

**Comment by julijenv** [comment]
Hi @gsaponaro ,
This part is the good spare part for both last articulations of any distal joint.
However, be aware that this part is good for Right hand (coz letter R of RT017-180-156) but wouldnt be suited for left hand which should be (LT017-180-156).
good luck fro the replacement,
