### ISSUE TITLE
Replacing parts for the iCub fingers plastic protections

### ISSUE THREAD

**Issue by pedrombmachado** [robotology/icub-support#437]
### Description of the failure
Need replacing plastic parts for the iCub fingers.

### Detailed conditions and logs of the failure
This is not a critical problem because the there is none physical problem. Two of the plastic finger protections needs to be replaced. The wires are intact and there was no other damage.
Many thanks

**Comment by julijenv** [comment]
Hi @pedrombmachado,
pictures please?

**Comment by pedrombmachado** [comment]
Hi @julijenv ,
  Sorry for my late reply. I am on my annual leave and therefore I cannot upload the photos until the 19/04/2017.

**Comment by julijenv** [comment]
HI @pedrombmachado ,
dont worry, have fun in holidays. I'm not in a hurry.

**Comment by pedrombmachado** [comment]
Hi @julijenv ,
   I am back from my annual leave. Please find the photos below:
![img_20170419_110116](https://cloud.githubusercontent.com/assets/9907068/25174645/f3765b2e-24ef-11e7-81cc-be42138db7f9.jpg)
![img_20170419_110123](https://cloud.githubusercontent.com/assets/9907068/25174643/f37608d6-24ef-11e7-9f3f-354a68fa9ac3.jpg)
![img_20170419_110132](https://cloud.githubusercontent.com/assets/9907068/25174642/f375d528-24ef-11e7-8184-97a1a81061b1.jpg)
![img_20170419_110140](https://cloud.githubusercontent.com/assets/9907068/25174644/f37627c6-24ef-11e7-9fbe-d6f8e6a1204d.jpg)
![img_20170419_110147](https://cloud.githubusercontent.com/assets/9907068/25174646/f376f714-24ef-11e7-943e-a96c4e12c3b0.jpg)

**Comment by pedrombmachado** [comment]
Hi @julijenv ,
   Thanks for your help. The following tools and parts are required:
1) Cable Sleeve Expander [link](http://uk.rs-online.com/web/p/cable-sleeving-tools/3212436/)
2)  Silicone Flexible Tubing [link](http://uk.rs-online.com/web/p/flexible-tubes/4190062/?searchTerm=4190062&relevancy-data=636F3D3126696E3D4931384E525353746F636B4E756D6265724D504E266C753D656E266D6D3D6D61746368616C6C26706D3D5E5C647B367D247C5E5C647B377D247C5E5C647B31307D2426706F3D313426736E3D592673743D52535F53544F434B5F4E554D4245522677633D4E4F4E45267573743D34313930303632267374613D3431393030363226)
