### ISSUE TITLE
Broken head tendon 

### ISSUE THREAD

**Issue by fvannu** [robotology/icub-support#442]
### Description of the failure

During the calibration at the startup of the robot, one of the tendons in the head broke.
Particularly is Cable A as indicated in the Head_V2_cabling.pdf

![img_20170413_174409](https://cloud.githubusercontent.com/assets/23313360/25012769/c7e36876-2071-11e7-921b-b757248e02ff.jpg)

**Comment by julijenv** [comment]
Hi @fvannu , @reafrancesco ,
the first question is : Do u have spare parts for replacing it??
If not, Please head up to IIT Main Headquarter to get cable A.

**Comment by fvannu** [comment]
We don't have any, so we will get one as soon as possible.

**Comment by julijenv** [comment]
it has been restored,
IITCODE Qta DEsceiption
5965 x 1 : head neck cable A
