### ISSUE TITLE
Cameras/eyes cover do not open on the new iCub face

### ISSUE THREAD

**Issue by pedrombmachado** [robotology/icub-support#446]
Please **fill in the following two sections** and then **remove any comment and/or remark become unnecessary**:

### Description of the failure
Cameras/eyes cover do not open on the new iCub face

### Detailed conditions and logs of the failure
The iCub eyes cover do not open after replacing the iCub face. This only happens with the new version, because the situation is solved when I install the old iCub face.

![img_20170419_144132](https://cloud.githubusercontent.com/assets/9907068/25186773/101636fe-2519-11e7-8aff-6d38b0721ade.jpg)
![img_20170419_155427](https://cloud.githubusercontent.com/assets/9907068/25186772/1014d1ce-2519-11e7-8403-d895724f1b3e.jpg)
![img_20170419_155509](https://cloud.githubusercontent.com/assets/9907068/25186802/29203d16-2519-11e7-96a5-9b5dac87dc7b.jpg)

**Comment by julijenv** [comment]
Hi @pedrombmachado ,
Could you try tpo launch some command of facial expression to see if the eyes reopen???
thx in advance or else C U on skype

**Comment by pedrombmachado** [comment]
Hi @julijenv ,
  Sorted with your support.
