### ISSUE TITLE
Left shoulder tendon broken

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [robotology/icub-support#457]
### Description of the failure
Left shoulder tendon broken

### Detailed conditions and logs of the failure
We don't know how this happened, as we found the part broken during a workshop, when the robot was off. The cable is stressed and damaged in other parts as well.

**Comment by arrenglover** [comment]
Looking at the robot it is already fixed. However, @massimoregoli  said that something is still not working with the left arm.

**Comment by ChiaraBartolozzi** [comment]
@massimoregoli could you please explain what do you mean by "something is still not working"?

**Comment by spada1978** [comment]
sostituiti cavi n.7 e 8 codice IIt 4764.1 e 300 4765.2 perche rotti.
effettuato nuovamente il cablaggio meccanico della spalla
