### ISSUE TITLE
Oscillations spotted on the head after maintenance 

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-support#46]
We have the hunch that after the maintenance work done to repair the Blacky's head there's been some weird problem with the head mechanics.

Refer to https://github.com/robotology/icub-main/issues/121 for the complete history.

**Comment by Tobias-Fischer** [comment]
Hi all,
I'd like to report that we've seen these oscillations on several other robots as well.

1) At the BCBT summer school, we've seen the oscillations on `iCubBarcelona01` when using `IOL`. A video can be found here: https://slack-files.com/T053A59T4-F0B1WACGL-e64d5fbece (sorry, it's quite large)

2) However, the problem does not only occur using `IOL`, but also when the gaze is not even controlled. We've seen the same behavior on `iCubLondon01` several times when we were driving the iKart around to map the environment. I am not 100% sure which modules were running at the time, but typically I reduce it to a minimum. I am not even sure whether `iKinGazeCtrl` was running.

The oscillations occur randomly, and I don't know how to track them down. Please let me know if I can help resolving this issue. It would be great if someone could look into this ASAP, as it is quite worrying ..

I am also not sure when we've encountered this problem the first time. We haven't updated the firmware for a little while, however we got the head upgrade to V2 a little while back. Typically `yarp` and `icub-main`

**Comment by pattacini** [comment]
@Tobias-Fischer 

Take https://github.com/robotology/icub-support/issues/30#issuecomment-144377458 into account regarding the oscillations when the robot is on the iKart.

/cc @maggia80 @randaz81 @super-ste

**Comment by lornat75** [comment]
any update on this?

**Comment by pattacini** [comment]
No progress at all.
Blacky's head still goes crazy every once in a while.

@hagenlehmann and @matejhof can provide a more recent report on this, I suspect.

I feel 99.9999999999999% confident to say that it's not an `iKinGazeCtrl` problem.

**Comment by super-ste** [comment]
Action Plan after IFI meeting:

- [ ] Check mechanical stability of support
![image](https://cloud.githubusercontent.com/assets/8122012/10667307/00b19d56-78d7-11e5-86e5-1f5105fd4085.png)

**Comment by julijenv** [comment]
has been changed, let's see if it brings improvments

**Comment by pattacini** [comment]
I'm the feeling we can close this :relieved:
