### ISSUE TITLE
Right middle distal tendon broken, finger not closing

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-support#460]
### Description of the failure
The right middle distal is unresponsive. The tendon is probably broken.
You can clearly ear the sound of the motor, but the middle finger is not closing.

**Comment by julijenv** [comment]
Hi @claudiofantacci ,
it has been repaired this midday.
ITICODE Qta Description:
2391 x 1m: carlstahl cable 0.45-0.61 coated
