### ISSUE TITLE
Mais Energy Problem

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#462]
Ciao @julijenv, 

Following the [previous issue](https://github.com/robotology/icub-support/issues/453), I am creating a new one to show you the evolution of the problem. 

1. This morning (and yesterday with you) we checked the encoder values of the right hand and they were perfect (zero). It was working pretty well. 

2. I turned iCub on again to check some things, and I saw that the values changed (with an offset around 5 degrees), as you can see in this image:
![1](https://cloud.githubusercontent.com/assets/11769446/26159294/869d5aee-3b1e-11e7-87f5-c4fb443a85ff.png)

3. Turn off yarprobotinterface, turn on. The values were a bit higher:
![2](https://cloud.githubusercontent.com/assets/11769446/26159347/acef9ce8-3b1e-11e7-9e63-679407009b61.png)

4. Same thing, off and on. The offset is around 15-20 degrees:
![3](https://cloud.githubusercontent.com/assets/11769446/26159395/c876e282-3b1e-11e7-8615-4c21f4f5011a.png)

5. Off and On: This time we have the 30s!
![4](https://cloud.githubusercontent.com/assets/11769446/26159422/d6c69968-3b1e-11e7-9709-8a2942595783.png)

6. Off and On again, even turning the power off. Calibration done, after a bit Mais OFF.
![5](https://cloud.githubusercontent.com/assets/11769446/26159458/e8c2d37a-3b1e-11e7-9292-dea1d0c12fc3.png)

7. Turn off the power. Turn on, the Mais was NOT on. 

8. Turn off the power, moved the arm and some of the connectors, on again. the Mais started, the values were around 5 degrees. After a couple of minutes, mais off again. 

9. Moved a bit the arm, turn it on. The degrees were 0! The mais was on.

10. Restarted again, the degrees are still 0. And after a while, it was still working.

So, I need your advice. I really think that there is a broken cable which is not giving enough power to the Mais. You recrimped the NET6 in the hand, so the problem may be in the arm. If not, where does the NET6 go after the shoulder? Can be that the problem is there?

@reafrancesco is suggesting that maybe we don't have enough voltage? Our current voltage is 41.2 for the motors, with 1.0 ampers.

**Update:** It seems that touching the cables between the shoulder and the back, makes the offset to change.

**Comment by julijenv** [comment]
Hi @amaroyo ,
when you say turn off and on yarprobotInterface, you mean

- close the yarprobotInterface ONLY BUT NOT shutting down the motor switch or do you mean
- close the power line when yarprobotInterface finally close and reboot ALSO motors OFF and ON

the line 6 is just in between the board 2B4 and the hand, you have however a black filter in between thenm at the very beginning of the 2B4, make them checked by Davide Dellepiane.

good luck,
btw if you test it in the first way that I assume you did, please try the other way and let me know, tht could also be related to firmware issue and in that case I would also suggest you to reupload teh firmware of MAIS inside the board.
Let me know,

**Comment by amaroyo** [comment]
Hi @julijenv, 

The first couple of times we did it only via software. When the values were getting strange, we did turn off the powerline and then we turned it on. Each time we tested it. This morning, the values were 30 again, and it entered in hardware fault.

I saw yesterday that there is a filter touching the motor of the shoulder, I also experienced that touching the cables between the shoulder and the back of the iCub, the mais turns on and off. Also, the encoder 1 of the shoulder got disconnected, and reconnected again while touching the cables. I do believe that there is something loose there. 

I will check them with Delle.

Thanks for the help. 

![img_20170518_112146](https://cloud.githubusercontent.com/assets/11769446/26195787/3dd7fc8e-3bbd-11e7-8616-e712c50d5950.jpg)
So, is this photo correct? Then which is the line that connects the board 2B4 to the back of the iCub?

**Comment by julijenv** [comment]
Hi @amaroyo ,
you are right, the net 6 goes up to the back of the head of iCub from the filter I was mentionning in my previous mail. BUT the power of the line for the MAIS is provided by 2B4, that why I dont think data cant be  altered from the filter to the back of the head but a little check is always welcome.
Let me know.

**Comment by amaroyo** [comment]
collateral damage: right pinky fingers are broken.

**Comment by julijenv** [comment]
It has been restored the all line net6, the skin wires as well.
We performed the rewiring of the pinky and ring finger motr of the right  hand.
IITCODE Qta descrition
2391 x 2m : cable carlstahl 0.45-0.61mm coated
