### ISSUE TITLE
missing eobrd_mais boards in CAN1

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-support#463]
errors starting yarprobotinterface - log errors below:

embObjMotionControl::open() fails to start mc service for board EB4 IP 10.0.1.4 : cannot continue
 from BOARD 10.0.1.4 (EB4) @ 109s 50m 184u: CAN discovery after 2999 ms has detected 1 missing eobrd_mais boards in CAN1:
1 of 1: missing eobrd_mais BOARD 10.0.1.4:CAN1:14
 from BOARD 10.0.1.4 (EB4), src LOCAL, adr 0, time 109s 50m 413u: (code 0x0500000b, par16 0x000e par64 0x0000000001000000) -> CFG: EOtheMAIS cannot be configured. can discovery fails. can address in p16, prot and vers in p64 lower 32 bits + .
 from BOARD 10.0.1.4 (EB4) @ 109s 50m 558u: CAN discovery after 2999 ms has detected 1 missing eobrd_mais boards in CAN1:
1 of 1: missing eobrd_mais BOARD 10.0.1.4:CAN1:14
embObjMais::open() has an error in call of ethResources::serviceVerifyActivate() for BOARD EB4 IP 10.0.1.4
One or more devices failed opening... see previous log messages for more info

**Comment by julijenv** [comment]
Hi @arrenglover ,
ok problem solved.
one of the can line was broken at the level of the knuckles
