### ISSUE TITLE
Head malfunction

### ISSUE THREAD

**Issue by pedrombmachado** [robotology/icub-support#465]
### Description of the failure
Hi Julien,
   I have an issue to report. The left motor, joint 0 starts starts to work full-speed a few seconds after the calibration process. Motor belt looks to be partially damaged. Please note that the head does not moves while this is happening.

![img_20170519_154150](https://cloud.githubusercontent.com/assets/9907068/26253368/0550224e-3cab-11e7-968a-7ad5a33d9686.jpg)
![img_20170519_154120](https://cloud.githubusercontent.com/assets/9907068/26253366/054bd95a-3cab-11e7-92a1-1953a08f8766.jpg)
![img_20170519_154010](https://cloud.githubusercontent.com/assets/9907068/26253369/0555aad4-3cab-11e7-868a-96482d4c6fae.jpg)
![img_20170519_153944](https://cloud.githubusercontent.com/assets/9907068/26253367/054ce94e-3cab-11e7-905b-d0b68961b5b9.jpg)
![img_20170519_153936](https://cloud.githubusercontent.com/assets/9907068/26253365/054b5840-3cab-11e7-8d62-8b115d92e0e0.jpg)

**Comment by julijenv** [comment]
Hi @pedrombmachado ,
please come on skype because the pictures R far from being useful.

**Comment by pedrombmachado** [comment]
Hi @julijenv ,
   Can we schedule a skype call for Monday? Let me know the best time for you.

**Comment by julijenv** [comment]
Hi @pedrombmachado ,
I'm right behind my desktop, so let me know when U r available, all morning is good for me.

**Comment by pedrombmachado** [comment]
Hi @julijenv,
  I am now ready. I have a 30 min window. Are you available or should we postpone to the afternoon?

**Comment by pedrombmachado** [comment]
Sorted with @julijenv support. Many thanks.
