### ISSUE TITLE
Problems on both arms

### ISSUE THREAD

**Issue by diegoferigo** [robotology/icub-support#466]
Joint 3 is in hardware fault. Furthermore, the right elbow doesn't reach its home position and stays bent. With a small external force, it reaches the home position with a sudden movement.

The left elbow is shaky and there is some play probably related to motor backlash.

**Comment by julijenv** [comment]
Hi @diegoferigo and @gabrielenava ,
The joint 3 goes in HW FAULT if the starting angle of the joint is way to close to 0 - I dont know precisely the software limit that has been implemented BUT if you just make sure that the elbow if close for at least 10 degrees, then the robot should calibrate.
I tightened the loose screws for the left elbow
