### ISSUE TITLE
The robot remains position controlled even after pressing fault button

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#467]
### Description of the failure

I pressed the fault button, but the robot remains position controlled. Even after removing the cable, the robot was still controlled. As you can see in the photo below, the fault is now useless:

![photo_2017-05-22_12-00-43](https://cloud.githubusercontent.com/assets/12396934/26303209/21258e08-3ee7-11e7-9b62-66ded65cb8ad.jpg)

**Comment by S-Dafarra** [comment]
[dumpLogger.txt](https://github.com/robotology/icub-support/files/1018422/dumpLogger.txt)

**Comment by julijenv** [comment]
Hi @gabrielenava  and @S-Dafarra ,
with the help of @MrAndrea, we debug the issue - the fault was touching a piece of the main robot structure.
everything should be working fine now.
