### ISSUE TITLE
left pinky broken and right hand skin unavailable

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#476]
Ciao @julijenv, 

Right hand, thumb and index finger skin is not working. 
Left hand, pinky finger cable is broken, see picture below.

Thanks!

![img-20170612-wa0002](https://user-images.githubusercontent.com/11769446/27035367-58c2c6e6-4f81-11e7-9840-620c925b0c96.jpeg)

**Comment by julijenv** [comment]
Hi @amaroyo ,
for the skin problem you may probably just need to open the dorso cover of the right hand to discover that the little pcb boards are a bit disconnected (not paralle to each other) to have all the fingertips aorking properly again.
for the palm you might consider taking a look at the wires going from the thumb base (where the wres from the palm gets out) up to the board above the MAIS.
Let me know

**Comment by amaroyo** [comment]
Ciao @julijenv, if it was only looking at the boards to see if they were disconnected, I was not going to write you ¬¬ 

The MAIS has been working properly since the last time!! But the pinky finger tendom is broken, as you can see in the photo! We miss you here in Erzelli, that's why we randomly broke some finger :P :D

**Comment by amaroyo** [comment]
fixed! :)
