### ISSUE TITLE
Thumb distal joint of the right hand is broken

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#478]
The tendon of the distal joint of the Purple iCub's right hand is broken.

**Comment by julijenv** [comment]
Hi @massimoregoli ,
the distal has been restored:
IITCODE Qta Description
2391 x 0.5m: carlsthal cable 0.45-0.61mm

**Comment by massimoregoli** [comment]
Oops I didn't specify thumb. Thanks!
