### ISSUE TITLE
Right shoulder cable broke down

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-support#481]
During the family day we were performing the red ball demo and the right shoulder cables broke down.

@julijenv

**Comment by julijenv** [comment]
Resolved.
IITCODE   Qta    Alias        Description
3852 x 1: (RC_TLR_003_P_099)    TENSIONER
4765x 1:	(RC_IIT_019_G_008)	    SHOULDERS ROTATION CABLE 8
4758 x 1: 	(RC_IIT_019_G_001)	    SHOULDERS ROTATION CABLE 1
1896 x 1:   (RC_IIT_003_P_007_00)    RIGHT PULLEY-CRIMP COVER
