### ISSUE TITLE
yarprobotinterface error: cannot find parameter fullscalePWM

### ISSUE THREAD

**Issue by gsaponaro** [robotology/icub-support#483]
Hi, we updated all software repositories to the latest **master branch**: robots-configuration, yarp, icub-main, icub-firmware-shared.

yarprobotinterface does not start anymore on the iCubLisboa01 pc104 because it does not find the parameter `fullscalePWM`.

Full log here:
https://gist.github.com/gsaponaro/248aee5b8dba7a73efbb38dd4f4fbdbd

I guess that we need to add the parameters `fullscalePWM` and `ampsToSensor` to our robot configuration xml files.

To do that, should I simply copy the parameter values from here?
https://github.com/robotology/robots-configuration/pull/25
https://github.com/robotology/icub-support/issues/451
And do you suggest that I make a PR in robots-configuration master or devel branch?

**Comment by randaz81** [comment]
Hi @gsaponaro, the issue should be fixed now. Please tell me if everything is ok. Thank you

**Comment by gsaponaro** [comment]
Yep, it works, thanks!
