### ISSUE TITLE
iCubGenova04 - joint 11 of left hand not working + left wrist needs tightening  

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#49]
Joint 11 of left hand (index proximal joint) is not moving when using yarpmotorgui.

I also noticed that joint 15 (little and ring fingers) is working with yarpmotorgui but when moved through the actions rendering engine, it stops halfway.

**Comment by lornat75** [comment]
Is this the same as: https://github.com/robotology/icub-support/issues/47#issuecomment-129376746 ?

**Comment by lornat75** [comment]
Is this issue the same as: https://github.com/robotology/icub-support/issues/47#issuecomment-129376746

**Comment by julijenv** [comment]
no it isn't the same issue: one was raised by @ale-git and referred to 2FOC boards which got burned but in the establishment of the repair I notice some details to be improved which could correlate a part of what is saying @bhigy .

**Comment by bhigy** [comment]
This issue is about the left hand while #47 is about the right one.

**Comment by vtikha** [comment]
@julijenv as @bhigy mentioned in this issue, the proximal joint of the left index finger is not working (although the little and ring do work) but I also noticed that the wrist of the left hand is extremely loose and needs tightening.

**Comment by julijenv** [comment]
left index prox and distal fixed
sledge redone entirely to be able to repair distals index and middle fingers.
wrist cables retense

**Comment by vtikha** [comment]
thanks @julijenv
