### ISSUE TITLE
Torso joints not working

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#492]
When the iCub starts up, the torso joints are always set in fault.

**Comment by diegoferigo** [comment]
I'd like to increase the priority of this issue, this Thursday we'll have a demo and we still need to start the tests of the Yoga. Since there's some work to do on the F/T sensors, we need sooner than later the robot running.

@DanielePucci

**Comment by spada1978** [comment]
replaced elettronic cable codice IIT 1310
