### ISSUE TITLE
[iCubGenova01] Left palm skin doesn't work

### ISSUE THREAD

**Issue by towardthesea** [robotology/icub-support#503]
### Description of the failure
There is no response from the skin patches for left palm while other parts work as normal. I tried to restart the iCub but the same thing happened.

**Comment by julijenv** [comment]
Hi @towardthesea ,
please check now if it is working. The connector of the palm was disconnected, so for sure it couldnt work properly

**Comment by towardthesea** [comment]
Last time I checked, it was fixed!
Thanks @julijenv
