### ISSUE TITLE
Broken cables on shoulder joints of iCubGenova04

### ISSUE THREAD

**Issue by pi-q** [robotology/icub-support#506]
While doing some tests on iCubGenova04, cables on the shoulder joints snapped.

**Comment by spada1978** [comment]
Replace broken left shoulder cables 7 and 8 iit 4764.1 and 4765.2
For the right shoulder it is verified as the piece RC_TLR_003_P_043 and bigger than the cad is therefore slim
Subsequently the broken cables n.1 and 8 have been replaced iit 4758.1 and 4765.2
