### ISSUE TITLE
Right hand motor doesn't stop spinnig during calibration

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#508]
At startup, the robot is unable to complete the calibration of the right hand. While both thumb and index are bended, the motor is spinning very fast but the fingers do not move. No errors are reported in the logger

**Comment by gabrielenava** [comment]
Update: I noticed that in the yarpmotorgui, the joint r_index_distal appears to be in NOT CONFIGURED state.

**Comment by julijenv** [comment]
Hi @gabrielenava ,

repaired with
IITCODE Qta Description
2391 x 0.5m = carlstahl cable 0.45-0.61mm
