### ISSUE TITLE
iCub not moving when running yarprobotinterface 

### ISSUE THREAD

**Issue by clement-moulin-frier** [robotology/icub-support#511]
Cc @julijenv @pattacini @jypuigbo @sockchinglow @Tobias-Fischer 

### Description of the failure

When starting `yarprobotinterface`, the robot doesn't move. When looking at the logs, there are a lot of timout errors like this:
`100ms Timeout occured in setControlModeRaw ( j:1), current mode: idl, requested: pos`.

Here is [the full log](https://github.com/robotology/icub-support/files/1156392/log_pc104_yarprobotinterface_1004.txt).

### Detailed conditions and logs of the failure

Since a couple of weeks we had problems with the ikart computer not starting time to time. Yesterday it was not starting at all anymore, so we opened it with Alex. We first thought it was due to the power supply we previously installed for the ikart computer. We changed it, still same problem. Then we saw that the graphic card fan was not moving correctly. We changed the graphic card and the ikart computer started correctly. End of the day.
Then today, we tried to start the iCub. When running `yarprobotinterface`, the robot doesn't move. Looking at the logs, there are a lot of timeout errors saying motors are in idle instead of pos (see above)

When running `canLoader` on the `pc104` we get this:
![img_20170718_170427](https://user-images.githubusercontent.com/6000622/28326100-1a26382a-6be0-11e7-9545-04d7b8c6e42b.jpg)

Thanks,
Clément

**Comment by Tobias-Fischer** [comment]
In case it's related to the torso boards, it seems like the lights of the boards are not switched on. Here is a photo:
https://wysiwyd.slack.com/files/clement_mf/F69NMR29F/img_20170718_165525.jpg
I am not in Barcelona though, so I might be totally wrong .. in that case, please ignore ;)

**Comment by julijenv** [comment]
HI @clement-moulin-frier ,
the robot is not moving at all?!?!?
did you press the red button by any chance?!?!
I red the log and it's hard to understand what's going wrong so the best will be to get in touch.
I'm available on skype, i will wait for you.

**Comment by julijenv** [comment]
Hi @clement-moulin-frier ,
we cleared this issue, if i recall, did we?
please close it

**Comment by clement-moulin-frier** [comment]
Yes indeed, I close it.
Cheers
