### ISSUE TITLE
Left thumb broken

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#513]
Please **fill in the following two sections** and then **remove any comment and/or remark become unnecessary**:

### Description of the failure
The left thumb does not open any more, so it seems that one of the cables got loose or broken

### Detailed conditions and logs of the failure

I was testing the tool use demo, and on the object grasping part, it squeezed the thumb against the table, probably causing the aforementioned failure. 

---
**Remark**: if you are not a daily icub-support user, please read carefully the guidelines for contributing linked at the top of this page. In particular, the **name of your robot** must be always indicated: either using **labels** if you're already a contributor, as per standard, or by specifying it while detailing the issue.

**Comment by spada1978** [comment]
replaced cable thumb proximal codice IIt 1815
