### ISSUE TITLE
Loose tendons at the thumbs

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#520]
The tendons of the right/left thumb proximal joints appear to be very loose (as a result such fingers apply a very weak force while grasping objects).

**Comment by julijenv** [comment]
Hi @massimoregoli ,
the work ahs been done for the left hand as it was requested , the right was not mentionning during my intervention.
So it means I will have to do that again on the other hand, later

**Comment by massimoregoli** [comment]
It's ok, the left hand was my priority at the moment, and I noticed the problem at the other hand later.

**Comment by julijenv** [comment]
Hi @massimoregoli ,
The tensionning of the right ahnd has been done.
