### ISSUE TITLE
Left elbow broken

### ISSUE THREAD

**Issue by anatanevska** [robotology/icub-support#522]
### Description of the failure
Left elbow broken

### Detailed conditions and logs of the failure
Tendon 9 of red iCub (iCubGenova03) snapped and needs to be replaced.

**Comment by amaroyo** [comment]
@julijenv, adding few more things:

left thumb is loose and the cable gets stuck some times not allowing the thumb to move. 

Left flat cable of the eye seems about to break. When you move the eyes to the left, you begin losing vision seeing blue horizontal lines, till you lose totally the vision.

**Comment by julijenv** [comment]
Hi @amaroyo please create a new issue ticket for your last comment, it isnt part of left elbow broken, and will be misleading to icub-support team.
