### ISSUE TITLE
firmware status

### ISSUE THREAD

**Issue by lschilli** [robotology/icub-support#526]
I am currently updating the software of iCubBielefeld03. I have a few questions regarding the currently installed firmware:
* Is the currently installed firmware recent enough for yarprobotinterface?
* Can I just update the firmware using `updateRobot.sh` or are there problems to be expected due to the age / version of our robot?
 
The following screenshots show the currently installed firmware versions:  
![net0](https://user-images.githubusercontent.com/1686536/29379824-f996c1e2-82c3-11e7-957d-a813173794aa.png)
![net1](https://user-images.githubusercontent.com/1686536/29379825-f9971818-82c3-11e7-8945-721cbb3eacbd.png)
![net2](https://user-images.githubusercontent.com/1686536/29379827-f99b0928-82c3-11e7-974e-5686ed54f8b8.png)
![net3](https://user-images.githubusercontent.com/1686536/29379826-f99837fc-82c3-11e7-93b8-b9fc4d8a0284.png)
![net4](https://user-images.githubusercontent.com/1686536/29379829-f99f96fa-82c3-11e7-9c3b-6c1dc1fd7184.png)
![net5](https://user-images.githubusercontent.com/1686536/29379828-f99ef36c-82c3-11e7-8182-ba583880328a.png)
![net6](https://user-images.githubusercontent.com/1686536/29379832-ff002e0c-82c3-11e7-801a-8c7968f72a23.png)
![net7](https://user-images.githubusercontent.com/1686536/29379830-f9b151ba-82c3-11e7-8dcb-af1b089b54ba.png)
![net8](https://user-images.githubusercontent.com/1686536/29379831-f9b32404-82c3-11e7-8204-c57605fac5d1.png)
![net9](https://user-images.githubusercontent.com/1686536/29379833-f9b4c264-82c3-11e7-98ca-9f27913d408c.png)

**Comment by lschilli** [comment]
Update: Currently installed firmware works with current yarprobotinterface for torso and head. In any case a quick check of the current firmware versions will be appreciated.

**Comment by julijenv** [comment]
Hi @lschilli ,
sorry for answering so late, but well I knew that as long as you dont try to launch the robot you will never know.
from the 9 printscreens you sent me just the one of the line 3 left leg is strange.
![net3](https://user-images.githubusercontent.com/7140395/38495663-ae03f9ac-3bfa-11e8-8725-cdbc3a2f9b62.JPG)
except that I guess that the upper part of the robot is ok, the only part you use I am sure.
let me know and I will let you close the 2 issues you opened for the same pseudo problem you absolutely knew how it works ;)
ciao Lars,

**Comment by lschilli** [comment]
Well, the idea was to ask for a quick check via this issue and then close it. The latency was a bit surprising but finally I can assume they are not that much outdated ;) Thanks for pointing out the leg issue.
