### ISSUE TITLE
Quadrature encoder broken on left leg

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#535]
At startup, the left leg remains in idle status. In particular, the left hip yaw joint is in hardware fault. On the logger, there is the following error:

```
<#STRING_START#> from BOARD 10.0.1.6 (left_leg-eb6-j0_3), src LOCAL, adr 0, time 131s 318m 410u: (code 0x0200000d, par16 0x0002 par64 0x0000000000000000) -> MC: 2FOC quadrature encoder phase broken. The motor encoder is not counting even if the motor is moving, please check motor encoder cables. In par64 0xFF is the mask of raw encoder value. par16 = ID of joint. + .

```

The full logger is attached to this issue. The problem is a broken quadrature encoder on left leg.

[quadEnBroken_7_9_2017.txt](https://github.com/robotology/icub-support/files/1285218/quadEnBroken_7_9_2017.txt)

cc @francesco-romano @S-Dafarra

**Comment by julijenv** [comment]
Hi @gabrielenava ,
It has been checked and repaired.
I also repaired an issue not documented by you guys, about the right arm board 29.
SO to me everything is working, let me know and close it if you agree.
