### ISSUE TITLE
Backlash on ankles

### ISSUE THREAD

**Issue by francesco-romano** [robotology/icub-support#536]
The robot has big backlash on both ankles.
This may create oscillations when the robot is standing.

@spada1978

**Comment by francesco-romano** [comment]
It seems that the backlash on the right ankle is due to some stripped screws.
On the left instead, it seems that the problem is in the motor / transmission.

**Comment by spada1978** [comment]
Per quanto riguarda la caviglia sx si necessita il controllo del giunto RC_IIT_018_G_003
Mentre per la caviglia dx si necessita di filettare il foro del pezzo RC_IIT_018_P_047 in quanto la vite gira a vuoto.
Appena francesco-romano ultimerà gli esperimenti prenderemo in consegna il robot per le riparazioni di entrambe

**Comment by francesco-romano** [comment]
cc-ing @ChiaraBartolozzi @vvasco @arrenglover @Iaxama as they will be affected by the maintenance.

**Comment by julijenv** [comment]
Hi @francesco-romano ,
this morning @spada1978 repaired both joint 5 for Left and Right knee, seems ok to me, now @valegagge is recalibrating the entire robot, if she cant find any issue related to the knee I'll close this issue.

**Comment by valegagge** [comment]
I recalibrated all joints with absolute encoder connected to ethernet boards. All is ok. Both joints move correctly, but i didn't performs other tests.

Before closing this issue, it should be better to verify that robot hasn't backlash on ankles.
