### ISSUE TITLE
Left thumb and flat cable not working well

### ISSUE THREAD

**Issue by anatanevska** [robotology/icub-support#539]
Left thumb is loose and the cable gets stuck some times not allowing the thumb to move.

Left flat cable of the eye seems about to break. When you move the eyes to the left, you begin losing vision seeing blue horizontal lines, till you lose totally the vision.

**Comment by julijenv** [comment]
Hi @anatanevska ,
Ok I already checked with @reafrancesco , and everything is ok, the flat cable has beeen chaged by D. Dellepiane and the thumb loose has been retensed by myself last time.
