### ISSUE TITLE
Broken cable on iCub Head and Broken pinky (right_arm)

### ISSUE THREAD

**Issue by gonzalezJohnas** [robotology/icub-support#540]
### Description of the failure
iCub head broken cable.
![img_20170922_145016](https://user-images.githubusercontent.com/12248551/30745236-a05a983e-9fa5-11e7-86e3-6829fc338e5b.jpg)

iCub pinky ( right_arm ) close but don't open.

### Detailed conditions and logs of the failure
During experiments we had uncontrolled behaviors resulting on breaking one cable for the iCub head.
Concerning the iCub pinky, the encoder works displaying the right value, but  only to close the pinky, the open movement no longer work. 

---

**Comment by julijenv** [comment]
Hi @gonzalezJohnas ,
could you please , check if the pulley next (iniside neck) from the serial number SN034 has  one single piece with 2 screws on it or if there are 2 set screw. to see it just spin the external pulley until you make the inside pulley make a turn,
let me know

**Comment by gonzalezJohnas** [comment]
This is the pulley you are talking ? 
![img_20170922_171757](https://user-images.githubusercontent.com/12248551/30751706-55e909b0-9fba-11e7-8525-b120c292cb86.jpg)
![img_20170922_171808](https://user-images.githubusercontent.com/12248551/30751709-56df485c-9fba-11e7-84e3-db90bb171779.jpg)

Then there is only 2 screws on it.

**Comment by julijenv** [comment]
IT has been used 
IITCODE Qta Description
5965 x 1 : cable A neck
