### ISSUE TITLE
Overcurrent issue

### ISSUE THREAD

**Issue by misaki43** [robotology/icub-support#550]
Dear all

we just started the robot, and while it was doing nothing it started to give this error (caught on the yarplogger):

ERROR	cfw2can [0] board 1 OVERCURRENT AXIS 0

what is it? how can we solve it?
Thanks in advance

**Comment by julijenv** [comment]
probably a fantom activation. I close it becaseu on the date of April 3rd, 2019, no thing to be seen like that
