### ISSUE TITLE
Board 27 Hardware problem in the magnetic position sensor

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-support#551]
### Description of the failure
Once the yarprobotinterface starts successfully the right wrist fall down.

### Detailed conditions and logs of the failure
Checking the log details seems that the issue is caused from the board 27 which reads wrong values from the encoders. Please attached you can find the logfile

[yarprunlog_16_10_2017_18_26_30.log](https://github.com/robotology/icub-support/files/1388301/yarprunlog_16_10_2017_18_26_30.log)

**Comment by julijenv** [comment]
Hi @ddetommaso ,
and this one too?? can we close it?
