### ISSUE TITLE
Head reboot using the extension cable

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-support#552]
### Description of the failure

The following issue occurs only when the robot is connected with the extension cable.
Before running yarprobotinterface, we try to run Calib_Cameras and Face_Expressions but the head reboots once the yarpdev of Face_expressions try to execute.

### Detailed conditions and logs of the failure
1. head and motors on
2. we launch Calib_Cameras processes and everything run correctly. 
3. we launch Face_expressions processes and the head reboot itself.

The power suppliers do not show OV or UV conditions.

**Comment by julijenv** [comment]
Hi @ddetommaso ,
can we close now???
