### ISSUE TITLE
fingertip not working on iCubGenova02

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#553]
The index fingertip of the right hand doesn't work properly on the purple iCub. It strongly suffers from hysteresis and also gives spikes as output even when pressure is released. I guess it needs to be replaced.

**Comment by julijenv** [comment]
Hi @massimoregoli ,
I wont be there for the 2 next weeks, please refer to the Production area to make it chnaged.

**Comment by julijenv** [comment]
After Double check with @massimoregoli, the replacement part work better than the replaced.
It has been taken
IITCODE Qta Description
1465.7 x 1 : iCub, subassembly - Fingertips for right hand, thumb or index finger, address 0, with lycra
