### ISSUE TITLE
Strapped neck tendons 

### ISSUE THREAD

**Issue by vtikha** [robotology/icub-support#556]
### Description of the failure
The two cables of the neck got strapped while the head was still. Just before the erratic motion that strapped the cables, the head slightly titled towards the front, and we suspect initial slippage of the cables. Nothing was actually running apart from the yarprobotinterface.

**Comment by julijenv** [comment]
Hi @vtikha ,
the robot is up and rinning again, enjoy!!

it has been taken from the warehouse
IITCODE Qty Desciption
5964 x 1 : cable neck B

**Comment by vtikha** [comment]
@julijenv thank you
