### ISSUE TITLE
Broken hands on Lilly (purple robot)

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-support#557]
### Description of the failure
 Thumb tendon in right hand is broken and all joints >= 8 on right hand start in hardware fault, even after restarting yarprobotinterface

### Detailed conditions and logs of the failure
This seems to refer to issue on right hand:
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  8  before starting the calibration procedure! 
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  9  before starting the calibration procedure! 
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  10  before starting the calibration procedure! 
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  11  before starting the calibration procedure! 
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  12  before starting the calibration procedure! 
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  13  before starting the calibration procedure! 
[ERROR]Right_Arm_Calibrator : detected an hardware fault on joint  14  before starting the calibration procedure! 

This seems to refer to issue on left hand:
[ERROR]unable to complete calibration: joint 4 in 'hw_fault status' inside doneRaw() function

**Comment by julijenv** [comment]
Hi @tanismar ,
actually there were more damages to the robot than the one you mentionned in your posts.
Both the right opposite thumb (j8) and the left thumb proximal joint were broken..
I repaired them on friday night. I relaunched the robot and it started correctly.

IITCODE Qta Description
1815 x 2m : carlstahl 0.63mm
