### ISSUE TITLE
Encoder problem in left upper arm

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#559]
While testing the robot before closing [this issue](https://github.com/robotology/icub-support/issues/555), another problem occurred, always in the left upper arm. In particular, the robot is unable to complete the calibration, and BOARD 24 sends a message stating `hardware problem in magnetic encoder`. I attached to the issue the logger messages.

[log_icub-head_yarprobotinterface_4799.txt](https://github.com/robotology/icub-support/files/1410260/log_icub-head_yarprobotinterface_4799.txt)

cc @spada1978

**Comment by spada1978** [comment]
si è reso necessario la sostituzione dell'AEA del polso in quanto non funzionante.
Codice IIT 1810 il lavoro è stato effettuato insieme al collega Davide Gandino
