### ISSUE TITLE
Need of Longer power supply and communication Cable for iCub

### ISSUE THREAD

**Issue by MichaelBombile** [robotology/icub-support#568]
Hi @DanielePucci , in your video of iCub balancing (https://www.youtube.com/watch?v=VrPBSSQEr3A), you have a longer power supply cable. It is possible to get such a long cable for iCubLausanne02?
If possible, what is the procedure that we must follow to get one?
Thanks in advance.

CC: @asutcl

**Comment by julijenv** [comment]
HI @MichaelBombile ,
could you please send me a picture of the connector coupling your power supply to the power supply cord? afterwards I will put you in contact with the purchase office.
thx in advance

**Comment by MichaelBombile** [comment]
Hi @julijenv ,
Thanks for your response. In fact, there is no particular connector between the power supply and the power supply cord. Here are some pictures of their connections.

![dsc_0398](https://user-images.githubusercontent.com/5852276/33131024-9228be24-cf95-11e7-8c51-a3fdf50fea8d.JPG)
![dsc_0400](https://user-images.githubusercontent.com/5852276/33131025-9247eae2-cf95-11e7-8b05-de967e7aa069.JPG)

And on the robot side
![dsc_0401](https://user-images.githubusercontent.com/5852276/33131026-9261bb98-cf95-11e7-97f6-3583efd1ab29.JPG)

Thanks.

**Comment by julijenv** [comment]
Hi @MichaelBombile ,
Ok I know What you need now.
Do you mind to give me the contacts of yours and your supervisor in order to send you a quotation for this 7m long extension cable.
Please send me a mail with the request at julien.jenvrin@iit.it
thx in advance
