### ISSUE TITLE
Right leg FT sensor may be broken 

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#571]
In particular, during the last experiment on iCubGenova04, we restarted the robot after a failure. After calibrating the robot in the air, this were the forces seen by FT sensors:

![screenshot from 2017-11-23 16-41-36](https://user-images.githubusercontent.com/12396934/33181384-5e4f0e4c-d070-11e7-822a-4d4b15956609.png)
 
the robot is on two feet and no-one is touching it, so this estimation is completely wrong. Furthermore, we checked the output of FT sensors (ports names `icub/....../analog:o`) and the output of the right leg FT was zero (I was touching the robot to see how the FT were responding):

![screenshot from 2017-11-23 16-41-56](https://user-images.githubusercontent.com/12396934/33181600-14bab74e-d071-11e7-9285-12239b5fa855.png)

restarting again the robot didn't change anything. So I think the FT is broken, or maybe a cable got disconnected.

**Comment by fiorisi** [comment]
The new FT has `half-gain` configuration, is this correct?

**Comment by fiorisi** [comment]
No, the new FT has the new electronic board `strain 2` with adjustable gains.

**Comment by julijenv** [comment]
Could you confirm. Is it still an open issue??? @fiorisi @gabrielenava

**Comment by fiorisi** [comment]
@julijenv thank you, the FT has been replaced.
