### ISSUE TITLE
Right shoulder tendon broken

### ISSUE THREAD

**Issue by giuliavezzani** [robotology/icub-support#573]
### Description of the failure
Right shoulder needs to be repaired.
The arm was not in the proper position while turned off and the tendon broke while starting on the `yarprobotinterface`.

**Comment by pattacini** [comment]
Thank you @spada for repairing the shoulder.

**Comment by spada1978** [comment]
sostituiti i cavi meccanici n.7 e 8 della spalla dx ed effettuato nuovamente il cablaggio del giunto
