### ISSUE TITLE
Left hand failure at startup

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#576]
After overcoming [the IMU failure](https://github.com/robotology/icub-support/issues/575), one the logger is printed an error saying that the robot was unable to complete the calibration of the left hand. This error is continuously printed on the logger, plus some of the left hand joints are in hardware fault (and cannot be run):

![lefthandfailure](https://user-images.githubusercontent.com/12396934/33366674-3aff296a-d4ec-11e7-8d9a-a8bf4252188a.png)

attached to the issue there is the logger.

[log_leftHandFailure.txt](https://github.com/robotology/icub-support/files/1513094/log_leftHandFailure.txt)

**Comment by julijenv** [comment]
It should have been repaired now.
