### ISSUE TITLE
Update firmware on STRAIN2 boards

### ISSUE THREAD

**Issue by fiorisi** [robotology/icub-support#589]
The robot is not starting. Probably there is an issue with the firmware version of the strain2 boards that have been recently [replaced](https://github.com/robotology/icub-support/issues/588).
In particular, might be necessary to update it from the version 1.0 to 2.0. 
A candidate could be the same version that is running on the r_leg FT sensor: [2.0.27](https://github.com/robotology/icub-firmware-build/blob/devel/CAN/strain2/strain2-v2.0.27.gain26.6.hex)
@marcoaccame @valegagge can you help us to update the firmware?

See attached log (line "1351 9,028682") and screenshot for further information.
**LOG**
[log_icub-head_yarprobotinterface_1684.txt](https://github.com/robotology/icub-support/files/1589631/log_icub-head_yarprobotinterface_1684.txt)

**FIRMWARE VERSION OF THE NOT WORKING FT IN THE LEFT LEG**
![screenshot from 2017-12-27 19-29-59](https://user-images.githubusercontent.com/8970230/34389859-5cb0e416-eb3c-11e7-8e3a-60f7d73c6c45.png)

**WORKING FT IN THE RIGHT LEG**
![screenshot from 2017-12-27 19-22-05](https://user-images.githubusercontent.com/8970230/34389687-7290d526-eb3b-11e7-90c7-f9fc731fbc92.png)

**Comment by traversaro** [comment]
If I remember correctly, there was a way to have the yarprobotinterface ignore this version checks by putting the desired version of `0.0.0` in some configuration files of the robot. @fjandrad can probably point you to the correct configuration files.

**Comment by fjandrad** [comment]
We modified locally the files of the right leg iCubGenova04 hardware FT in [here](https://github.com/robotology/robots-configuration/blob/791e4d7453300bbb2496fd8d79a928975f99b22d/iCubGenova04/hardware/FT/right_leg-eb8-j0_3-strain.xml#L22). Changing the protocol major to 0 minor was already at 0. This was mentioned to be a **temporary solution** since what it does is ignore some checks.  This can be done for all sensors.

**Comment by fiorisi** [comment]
Thanks @traversaro and @ fjandrad, we can try that, but don't you think that we should update the firmware to the same version of the right leg STRAIN2 ft?

**Comment by traversaro** [comment]
Yes, I think that actually both thing are necessary (updating the firmware and putting the 0.0.0 version in the configuration files).

**Comment by fiorisi** [comment]
Thanks @traversaro and @fjandrad , with the help of @randaz81 we managed to have all the FT working!
