### ISSUE TITLE
[iCubGenova01] Left wrist got Hardware fault

### ISSUE THREAD

**Issue by towardthesea** [robotology/icub-support#602]
### Description of the failure
I tried to run a simple motion with iCub left arm but motion stopped due to the hardware fault (informed by the firmware). When I had a look on `yarpmotorgui`, it showed clearly that there was a problem with the **left wrist** (joint 5, 6). I tried to restart the robot (both motor and PC104) and run again the application, then the error happened again. Moreover, when running the same motion with the right arm, it could run normally.

Please help check it as soon as possible. 

cc @pattacini @julijenv

**Comment by julijenv** [comment]
Hi @towardthesea ,
From what I could see, it seems that 2 crimp from the powerline of the board driving the 2 wrist motors wer flaky, I recrimped those 2 wores, and it seems that the problem was solved.
