### ISSUE TITLE
right arm: MC4 (CAN) with address 3 now has address 15

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-support#604]
Yarprobotinterface cannot start because the check of can boards presence, it fails.

I launched FirmwareUpdater, and after putting EMS4 in mantainance, I discovered its can boards and I saw 3 mc4 can boards with address: 15, 5 and 7. This means that the board with adress 3 has been changed in 15.
I think nobody changed address, but it is a fault of the board.

**Comment by julijenv** [comment]
Hi @valegagge ,
it is not the first time that CAN boards at some point have their ID getting a change into 15 - I dont really know the reason why but it is a common issue. rechanging back into the proper ID was the perfect thing to do and unfortunately the only one I know.
