### ISSUE TITLE
Loose hip pitch cables

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-support#606]
While walking, the cable on the right hip pitch became very loose. Talking with @julijenv, he noticed that one of the tensioner screws is stripped.
The left hip pitch instead has probably a too long cable. This can cause backlash and increase the probability for the cable to exit.

@DanielePucci

**Comment by fjandrad** [comment]
> The left hip pitch instead has probably a too long cable.

For sure is too long it also complicates getting clean data for calibration of F/T sensors on the pole. Since it can get smashed between the leg and the cover of the hip in some positions.

**Comment by S-Dafarra** [comment]
@fjandrad sorry I should have been more precise. I was meaning the mechanichal one, but I agree that also the electrical cables are quite long.

**Comment by julijenv** [comment]
to be lcosed due to same issue as 647
