### ISSUE TITLE
iCubLondon01 - Torso fault + smoke

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-support#61]
Hi all,

we have an issue with the torso of our iCub. One day we started up `robotInterface` as usually, when we heard a weird noise and smelled some burned electronics / plastics. We pressed the red button very quickly, and were able to avoid more damage. It happened just before the iCub is usually going to calibrate its parts (nothing moved yet).

We have the log file, were you can see that the main problem is with board 6 on can bus 0 (board label 0B3). We looked up the board in the motor and placement diagram, and visually inspected the board. We found some burning marks on one of the green connectors, as well as the one small black boards (see attached photos).

I guess we probably need a replacement board. Would it be hard to replace ourselves?

In the meantime, we can run the iCub with disabled torso and disabled cartesian solvers, which of course is no long term solution ;-).

Regarding issue https://github.com/robotology/icub-support/issues/48: It seems like since the board failed / has been deactivated, we have smoother movements of the head.

Thanks and best wishes,
Tobi, and @maxime-petit 
![img_1348_zoom](https://cloud.githubusercontent.com/assets/5497832/10071538/842d4e0e-62b2-11e5-987f-71dce24a80cf.JPG)
![img_1348](https://cloud.githubusercontent.com/assets/5497832/10071414/9a31b04c-62b1-11e5-86b3-c4630e62f773.JPG)
![img_1349](https://cloud.githubusercontent.com/assets/5497832/10071416/9a33a2da-62b1-11e5-8c49-769e82508a06.JPG)
![img_1350](https://cloud.githubusercontent.com/assets/5497832/10071417/9a33c83c-62b1-11e5-9cd5-44dcf5942a56.JPG)
![img_1351](https://cloud.githubusercontent.com/assets/5497832/10071415/9a334de4-62b1-11e5-86d3-a2d3f192e494.JPG)

Log file:
https://gist.github.com/Tobias-Fischer/fad5b1f5766368d494f2

**Comment by julijenv** [comment]
Hi @Tobias-Fischer and @maxime-petit ,
from the picture it looks quite clear that the BLP got burned, the reason, so far, remains unexplained and of course need to be understood before any further change or replace it.
in any case please from now check the flat cable from BLP (the burned one) and the board at the other extremity of the flat cable to see if there are some used part, or for exmaple the red white and black cables from motor going to the BLP to seen if they are worn.
I am going to talk to @super-ste about it and understand how we can give you and send you the spare parts you need (surely BLP = power board the one already burned and BLL = control board).

**Comment by super-ste** [comment]
The replacement parts are on the way.
Please contact us if you need help in replacing them.

In particular the BLP (the board with the black heat exchanger) is to be attached to the aluminum support with the given tape.

**Comment by Tobias-Fischer** [comment]
Great, thanks so much for shipping them over so quickly! We'll get in touch via Skype to replace the parts.

Best, Tobi and @maxime-petit

**Comment by Tobias-Fischer** [comment]
Hi @super-ste and @julijenv,
we were able to replace the boards, and iCubLondon01 is running fine again! Thanks a lot :)!

Best,
Tobi and @maxime-petit
