### ISSUE TITLE
yarprobotinterface doesn't start on PC104

### ISSUE THREAD

**Issue by fbottarel** [robotology/icub-support#612]
### Description of the failure
Running yarprobotinterface while logged in the pc104 fails, and I can't get the robot to move. According to the log file I attached, errors come from the `canmotioncontrol` driver. 
@randaz81 suggests the nature of the failure might be electrical. 
@pattacini @vtikha 

### Detailed conditions and logs of the failure
Here's the [log][1] I acquired.

[1]: https://github.com/robotology/icub-support/files/1796831/output.log

**Comment by julijenv** [comment]
the main power plug was loose
