### ISSUE TITLE
icub-head restarts after few minutes every time is switched on

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#619]
As you can see in the attached GIF, after being turned on the `icub-head` reboots. No one was touching the robot or was connected to `icub-head` via `ssh`. This happens every time the `icub-head` is switched on. No (visible) error messages are reported.

 Unfortunately, once it also happened while we were compiling `yarp`, and we suspect now there might be also issues in the `icub-head` file system.

![head](https://user-images.githubusercontent.com/12396934/37916312-ca88fe86-311b-11e8-84a1-493f449db6f7.gif)

**Comment by julijenv** [comment]
Hi @MrAndrea , this is your task, please fill up what you've done.

**Comment by MrAndrea** [comment]
There was a problem on a voltage regulator in the control board BCB (the one with the 2 push buttons), probably due to iCub falls on the floor.
I changed the board with a new one (iitcode is 6117.A) and I checked that the robot works correctly.

**Comment by S-Dafarra** [comment]
Thanks @MrAndrea. Now it seems to work fine!
