### ISSUE TITLE
eye lids on blue iCub get stuck

### ISSUE THREAD

**Issue by hagenlehmann** [robotology/icub-support#62]
When trying to run the blinker on the blue iCub, the eye lids are not controllable because they get stuck in different positions on the eye balls. It seems to be a structural problem. It would be important for us to use the eye lids on bluey because we need to test the blinker together with the face recognition / following which is, due to different cameras, only possible on the black and the blue iCub.

Many thanks for looking into the problem,
Hagen

**Comment by pattacini** [comment]
This issue would need attention 'cause we have a guest coming to visit us next week, who is going to work with the eye lids too.

**Comment by hagenlehmann** [comment]
The blinking appears to work great now! Many thanks! We will check it over a longer period of time next week and let you know.

Many thanks again,
Hagen
