### ISSUE TITLE
Issues on the left hand

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#621]
It seems there are issues in the iCub left hand. First of all, the `thumb distal` joint starts in `NOT CONFIGURED` state and therefore cannot be controlled. The logger is attached to this issue. Furthermore, it seems that one of the motors (maybe the one associated with the index finger) continuously spins without effectively move the finger, maybe the cable got detached from the transmission element.

[log_icub-head_yarprobotinterface_1698.txt](https://github.com/robotology/icub-support/files/1876810/log_icub-head_yarprobotinterface_1698.txt)

**Comment by julijenv** [comment]
It has been repaired and replaced : 
the distal thumb cable
the AEA COVER WRIST of the left arm (4682.A1)
