### ISSUE TITLE
Joint encoders measurements have spikes

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#624]
We tried the robot with a `yarp` branch different from `devel`, inside @valegagge fork. We had some problems running the Yoga demo because we were having spikes in the measured torque. By further investigation we noticed that the joint encoders were having spikes. In particular, from time to time, the encoders reading of a group of joints was going to zero for some instants. I'm going to update this issue with a picture of the spikes soon. In the end  we reverted to `devel` and we did not have this issue anymore.

**Comment by DanielePucci** [comment]
@valegagge 
I think the link to the issue open in yarp is missing

**Comment by valegagge** [comment]
@DanielePucci thanks for the ping.
Done!

**Comment by valegagge** [comment]
fixed by https://github.com/robotology/yarp/pull/1668
