### ISSUE TITLE
Firmware update

### ISSUE THREAD

**Issue by barbalberto** [robotology/icub-support#626]
### Description of the failure
yarprobotinterface does not start. A firmware update is required.

### Detailed conditions and logs of the failure
yarp and iCub repositories have been updated. This triggered a firmware update.
Support is requested to perform the update.

@julijenv can you help @tasbolat1 in this process?

**Comment by tasbolat1** [comment]
In

> Compile iCub,

 which flags should be ON? (We're iCubSingpapore01)
```
You need to enable (all versions of iCub):

 ENABLE_icubmod_dragonfly2
 ENABLE_icubmod_skinWrapper
 ENABLE_icubmod_xsensmtx

CAN robots:

 ENABLE_icubmod_sharedcan
 ENABLE_icubmod_canmotioncontrol
 ENABLE_icubmod_canBusAnalogSensor
 ENABLE_icubmod_canBusDoubleFTSensor
 ENABLE_icubmod_canBusSkin
 ENABLE_icubmod_canBusInertialMTB
 ENABLE_icubmod_canBusVirtualAnalogSensor
 ENABLE_icubmod_cfw2can
 ENABLE_icubmod_parametricCalibrator

ETH robots: enable also the following

 ENABLE_icubmod_embObjAnalogSensor
 ENABLE_icubmod_embObjMotionControl
 ENABLE_icubmod_embObjSkin
 ENABLE_icubmod_embObjVirtualAnalogSensor
 ENABLE_icubmod_parametricCalibratorEth

Cartesian controller:

 ENABLE_icubmod_cartesiancontrollerclient
 ENABLE_icubmod_cartesiancontrollerserver

Versions from iCub 1.1.1 enable also:

 ENABLE_icubmod_cfw2can
 ENABLE_icubmod_skinprototype

Previous versions (iCub 1.0 and 1.1.0):

 ENABLE_icubmod_pcan: iCub 1.0 and 1.1.0
 ENABLE_icubmod_ecan: iCub 1.1.0
```


When we update the icub-main, we set some flags in `ccmake` to ON, which were OFF for old version.
We are doubting about that those flags may cause the problem also.  How can we make sure which flags should be ON for our icub?

**Comment by barbalberto** [comment]
ENABLE_icubmod_dragonfly2
 ENABLE_icubmod_skinWrapper
 ENABLE_icubmod_xsensmtx

ENABLE_icubmod_embObjAnalogSensor
 ENABLE_icubmod_embObjMotionControl
 ENABLE_icubmod_embObjSkin
 ENABLE_icubmod_embObjVirtualAnalogSensor
 ENABLE_icubmod_parametricCalibratorEth
 ENABLE_icubmod_cfw2can
 ENABLE_icubmod_skinprototype

 ENABLE_icubmod_cartesiancontrollerclient
 ENABLE_icubmod_cartesiancontrollerserver

**Comment by tasbolat1** [comment]
we got an error:
`cfw2can: cannot find cfw2canapi, turn off device`

**Comment by julijenv** [comment]
disable cfw2can you have an ethernet board

**Comment by julijenv** [comment]
please contact me on skype: ID  = icub.support

**Comment by barbalberto** [comment]
ops, sorry

**Comment by julijenv** [comment]
Hi @tasbolat1 ,
here some pictures for the sensor that makes some problem for the right leg

![image](https://user-images.githubusercontent.com/7140395/38569972-f3e2318a-3cec-11e8-857c-0d67a66626ac.png)
![image](https://user-images.githubusercontent.com/7140395/38569889-ca434a94-3cec-11e8-9621-5fbad352fce8.png)
![image](https://user-images.githubusercontent.com/7140395/38570160-7bd70f98-3ced-11e8-9d52-8187a23c0905.png)
![capture](https://user-images.githubusercontent.com/7140395/38570267-ba337b00-3ced-11e8-942f-cf77dbdb0c07.JPG)
![capture2](https://user-images.githubusercontent.com/7140395/38570378-fe563f34-3ced-11e8-809b-88621d53511b.JPG)
![capture3](https://user-images.githubusercontent.com/7140395/38570499-4aec91fe-3cee-11e8-9276-2c21c267941b.JPG)
the list of tool needed for daily care of icub is in the following link
https://svn.robotology.eu/repos/iCubHardware-pub/trunk/mechanics/public/doc/tool/iCubMaintenanceTools.xlsx

**Comment by tasbolat1** [comment]
Thanks guys, firmware update has finished successfully!
