### ISSUE TITLE
Little fingers of icub don't work properly

### ISSUE THREAD

**Issue by tasbolat1** [robotology/icub-support#627]
Hello everyone,
I have a following issue with icub's fingers:
Little fingers (joint 15) don't move when move with `yarpmanager` (logs give no error). And, sometimes only little finger moves (not ring one). How to check the reason of such behavior?

**Comment by julijenv** [comment]
Hi @tasbolat1 ,
The joint probably run in the wrong direction or one of the 2 tendons is broken./ Could you take a philips (flat) screwdriver and spin it always to the external direction ( this should close both fingers).

**Comment by tasbolat1** [comment]
@julijenv thanks for quick answer.
Which screw do I need to spin?  (you can orient me relative to the index finger screw)

**Comment by tasbolat1** [comment]
Hi @julijenv! Are you around?

**Comment by julijenv** [comment]
Hi @tasbolat1 , could you close this issue if consider as settled? if not please contact me

**Comment by tasbolat1** [comment]
Hi @julijenv,
Yes, it's been solved. Thank you a lot
