### ISSUE TITLE
Loosen screws in the head neck

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-support#628]
### Description of the failure
The screws that fix the head at the level of the pitch (the very small ones) need to be tighten. We manage to tighten the left one, but the right other is difficult to reach, without a long screw.

**Comment by lornat75** [comment]
@karinne-ics-tum

**Comment by julijenv** [comment]
Hi @lornat75 ,
As already explained over the phone the best way to tighten the little screws are first to remove the 2 hexagonal print screws above them and use a long screw driver to pass from the top of the head down to reach the screws remove them ona after the other, add some thread locker and retighten them STRONGLY. when done, please rescrew also the hexagonal ones and you are done.
let me knwow

**Comment by julijenv** [comment]
any news on this matter??? @karinne-ics-tum
