### ISSUE TITLE
Left shoulder joints' cables detached/ broken

### ISSUE THREAD

**Issue by ahmadgazar** [robotology/icub-support#636]
### Description of the failure
Some of the cables controlling the left shoulder roll, pitch and yaw joints got detached/broken while testing the balancing with torque control.

**Comment by fiorisi** [comment]
In view of the demos on Monday the robot has been fixed by Marco Pinaffo.
The following components have been used:

|  CODE  | QUANTITY | 
| :------: | :----------: |
| 2525  | 18 |
| 2429  | 8   |
| 4758.1 | 1 |
| 1895  | 2 |
|4765.2 | 1 |
