### ISSUE TITLE
Right hand thumb distal actuator not working

### ISSUE THREAD

**Issue by fbottarel** [robotology/icub-support#646]
### Description of the failure
The actuation of the right thumb is limited since the actuation of the distal part of the thumb does not seem to be working. 

### Detailed conditions and logs of the failure
Moving the distal joint of the thumb from `yarpmotorgui` does not yield any results. The other joints in the thumb work, together with the distal encoder.

**Comment by julijenv** [comment]
@fbottarel ,
It has been repaired
It required
IITCODE Qta Description
2391 x 1m - CArlstahl o.45-0.61 coated

**Comment by fbottarel** [comment]
Thanks for fixing this right away!
