### ISSUE TITLE
Torso skin on iCubGenova02 is attached to wrong board

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-support#648]
### Description of the failure
Torso skin is wrongly attached to board 10.0.1.23. It should be attached to board 10.0.1.22.

The side effects are modest because the related wrapper is commented out in icub_all.xml, but I recommend to reconnect correctly at the next repair of the head, where board .22  resides.

### Detailed conditions and logs of the failure

FirmwareUpdater shows the mtb boards below 10.0.1.23.

**Comment by julijenv** [comment]
Hi @marcoaccame ,
It has been swapped as requested, and check later on with FirmwareUpdater.
