### ISSUE TITLE
Update the videos folder on the `icub13`

### ISSUE THREAD

**Issue by alecive** [robotology/icub-support#65]
It would be nice to update the videos folder on the `Blacky`'s display with new videos when we'll be back from IROS. Right now we have old and very low-res videos.

**Comment by pattacini** [comment]
`Blacky` is back, @alecive please get one of the latest usb-drive and copy the videos.

**Comment by lornat75** [comment]
any update on this?

**Comment by super-ste** [comment]
@alecive unfortunately passed away... to a better life we hope.
Shall we reassign this to someone else? [also added tags for same operation TBD on other internal robots]

**Comment by alecive** [comment]
...

**Comment by super-ste** [comment]
:metal: :angel: :metal:

**Comment by lornat75** [comment]
Closing.I wonder why we should open issues for things like this...
