### ISSUE TITLE
Left arm elbow goes in hardware fault while torque controlled

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#650]
### Description of the failure
While running the Yoga ++ demo the left arm elbow goes in hardware fault. This happens almost every time we run the demo

### Detailed conditions and logs of the failure

There is an error related to the left elbow joint in the logger.
[yarprunlog_09_05_2018_16_48_09.txt](https://github.com/robotology/icub-support/files/1988397/yarprunlog_09_05_2018_16_48_09.txt)

**Comment by DanielePucci** [comment]
CC
@julijenv It would be nice to do it tomorrow morning :-)

**Comment by hu-yue** [comment]
Might be related to #605 as well

**Comment by julijenv** [comment]
Hi @gabrielenava, hidden behind the pseudo of Francisco,
I recrimped both hall sensor for the left elbow as well as the Lcore for this same joint.
Let me know, if it solves the issue.
@DanielePucci 
@hu-yue

**Comment by gabrielenava** [comment]
I @julijenv, I worked with the robot during the morning and the elbow issue never happened. I think the issue is solved.
