### ISSUE TITLE
Left elbow joint cable broken.

### ISSUE THREAD

**Issue by ahmadgazar** [robotology/icub-support#654]
## Description of the failure

Left Elbow joint cable  got broken while testing the balancing with torque control.
![img_20180516_131734](https://user-images.githubusercontent.com/15094592/40114465-541a9c9a-590d-11e8-93b0-30845401bd87.jpg)

@julijenv @spada1978

**Comment by spada1978** [comment]
i cavi da cambiare sono sia il 10 (rotto in corrispondenza del crimp) che il 9 in quanto si e sguainato il cavo

**Comment by spada1978** [comment]
sono stati sostituiti i cavi n.9 e 10 in quanto rotti ed e stato effettuato nuovo cablaggio
