### ISSUE TITLE
Right thumb tendons are loose/broken

### ISSUE THREAD

**Issue by fbottarel** [robotology/icub-support#656]
### Description of the failure
Right thumb cables are loose and at least one has snapped. 

### Detailed conditions and logs of the failure
The robot came back from a demo session in Switzerland, so we set it up again in the lab. At startup, the thumb was not moving properly. We had the covers removed by one of the technicians and discovered that the proximal joint cable has snapped. The other cables might be a bit loose. 
![image](https://user-images.githubusercontent.com/33027628/40229454-9002eb76-5a94-11e8-90f2-966661680ee1.png)

**Comment by julijenv** [comment]
it has been repaired
IITCODE Qta Desciption
1815 x 1m : cable carlstahl 0.63mm non coated
