### ISSUE TITLE
Backlash on left arm elbow

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#657]
### Description of the failure

There is a considerable backlash in the left elbow joint.

### Detailed conditions and logs of the failure

While the robot was switched off I moved the elbow joint on the left arm. It was moving a bit also along the direction perpendicular to the elbow joint motion.

**Comment by spada1978** [comment]
sono stati sostituiti i cavi n.9 e 10 in quanto rotti ed e stato effettuato nuovo cablaggio
