### ISSUE TITLE
Right thumb doing weird unexpected movements

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#66]
When asking the robot to give an object through ARE, the thumb is sometimes making weird movements. Could be due to the new mechanics in the hand.

@randaz81 I can show you when you have a moment.

**Comment by lornat75** [comment]
Any update on this?

**Comment by super-ste** [comment]
@randaz81 can you have a look at this?
Is this an issue with the coupling of the joint in the thumb or is it there any hardware problem?

**Comment by kt10aan** [comment]
If it is any help, the  same issue happens to iCubOsaka01 when using ARE, on the thumb of the right wrist. And it's going on for quite a few months now. It is just that we were not using ARE much to open an issue about it.

**Comment by super-ste** [comment]
@kt10aan @bhigy does it happen ONLY on the right hand? in both cases?

Sounds weird to me ... but this may be a lead ...

**Comment by bhigy** [comment]
I didn't use the left hand a lot so I can't really say.

**Comment by kt10aan** [comment]
@super-ste It happens only on the right hand. I will take a video and post it here.

**Comment by kt10aan** [comment]
Regarding the Osaka01, this issue can be closed.
