### ISSUE TITLE
Left_hip_pitch joint's cable broken

### ISSUE THREAD

**Issue by vibhoraggarwal** [robotology/icub-support#661]
### Description of the failure
We were using the **l_hip_pitch** joint in `Torque control mode`. While pushing the joint to estimate the friction forces, we broke the cable.
![https://c1.staticflickr.com/1/975/41358548775_8155b56206_c.jpg](https://c1.staticflickr.com/1/975/41358548775_8155b56206_c.jpg)

### Detailed conditions and logs of the failure
The cable joining the gearbox and joint pulley is broken and it needs to be changed.

**Comment by julijenv** [comment]
it has been reapaired by changing cable n14
IITCODE Qta Description
4771.1 x 1 : Hip flexion cable

**Comment by vibhoraggarwal** [comment]
Thanks @julijenv
