### ISSUE TITLE
Torso smoke (again)

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-support#663]
Hi @robotology/icub-support-team,
We've got some issues with our torso. When we played around with `yarpmotorgui`, the color within the `yarpmotorgui` changed to orange(ish). Then we looked at the robot and realized that there was some smoke coming from the torso area. Also, the motors seemed disabled and the robot was slowly falling forwards.

We pressed the red button and then shut down the robot, and tried to find the detailed position of the smoke. The heat plate where the BLP / BLL of the torso are attached was really hot. We also saw some burn marks on one of the boards (the board is brown-ish where the white marking is, see red circle):
![20180531_145406](https://user-images.githubusercontent.com/5497832/40788514-2cb4153c-64e8-11e8-9797-fc25210d68f6.jpg)

We also realized that the middle motor of the torso was really hot, but could not see any damage (not the motor with the serial number of the robot, but the motor located centrally of the robot):
![20180531_145317](https://user-images.githubusercontent.com/5497832/40787715-32882b4e-64e6-11e8-89f5-55a52f1c12ff.jpg)

As discussed on Skype, here is also two pictures of the transistors. We cannot see any damage there:
![20180531_151358](https://user-images.githubusercontent.com/5497832/40787795-646dffbc-64e6-11e8-852a-93dccbdc6f1e.jpg)
![20180531_151350](https://user-images.githubusercontent.com/5497832/40787802-66f94c1e-64e6-11e8-8f57-827b283cc8f3.jpg)

This problem might be related to https://github.com/robotology/icub-support/issues/61 from a few years ago, where we also burned a motor board (however this time the damage doesn't quite look as bad). Another related issue is https://github.com/robotology/icub-support/issues/216 which describes a problem where the torso only worked for a limited amount of time, then we shut down the robot for a while, turn it back on and it worked again.

Via Skype, you mentioned that it might be related to some shorts somewhere ..

Please let us know how to proceed.

Best, Tobi

Update:
There is also some yellow stuff near one of the motors (it's not fully solid) - not sure whether that's normal:
![20180531_153829](https://user-images.githubusercontent.com/5497832/40788901-096e97fe-64e9-11e8-8931-35559846c076.jpg)

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
After your suggestion on Skype to start the robot again to get an error log, we switched on the motors and got more smoke from the area circled in the image below (without even starting the `yarprobotinterface`). Therefore, we don't really want to test any further - I guess we have a short somewhere as you suggested yesterday.

![whatsapp image 2018-06-01 at 11 08 11 am](https://user-images.githubusercontent.com/5497832/40835874-aeea0ddc-658c-11e8-84b3-c2e25891f9ed.jpeg)


What do you think our next steps should be?


Thanks, Tobi

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
 I would suggest you not to use the robot torso and leg for a while ( try to disconnect the main power line for those parts ( those have a total of 4 connectors with big red adn black wires, please see picture below)
Afterwards  just try to detect the short that you may have. I f you cant, please take a lot of pictures for me to try to see something. You may have to dig inside the butt to find out the short circuit.
![icub_butt.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/564dabdcd8616f15001b0f59/125516c66e82c728ace21e0d46e1978f21bd81bc9bfdfd0fe64de29b234324676b5ee17e26d1e22cb91a7a040c0a1baa44500c44fcad8e2fa5b46f62964e49bc8f3900299f7744eeaa880dbe08b0218e4d82beb98d4ac9ee3e2de299c2.png)

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
We think we have isolated the problem.
1) We disconnected all 4 cables on the main power line as suggested. No smoke / heat.
2) We connected back the cables one by one, and the cable which powers the board circled blue caused the trouble, whereas the boards circled red are all fine:
![20180531_145406](https://user-images.githubusercontent.com/5497832/40912985-118e839a-67eb-11e8-91d7-255b857bb788.jpg)
3) We connected all main cables, but disconnected the red/white/blue cables which go from the (blue circled) motor board to the motor. No problems.

Therefore, we assume that the motor itself is broken:
![whatsapp image 2018-06-01 at 11 10 42 am](https://user-images.githubusercontent.com/5497832/40836071-566013fe-658d-11e8-84af-27974f0c66a7.jpeg)

Is there any way for us to check whether it is actually broken?

Thanks,
Tobi

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
could you please check the Ohm values of everysingle pair of wire for the motor you think it is broken. Apply one probe a one side of the wire (black for instance) and the other probe on another wire (white or red). DO the 3 different combinaison and send me the values for each pair. thx in advance

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
For all combinations we obtain 1.3 Ohm .. any idea what that means?

Best, Tobi

**Comment by julijenv** [comment]
hi @Tobias-Fischer ,
yes it means that you motor is not dead. Make a last trial, please. Leave the 3 phases of the motor in a way that they do not touch each other, and see you can move the motor? next try to twist the 3 wires together and see if the motor can be moved?
let me know

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
It is hard to tell whether the motor is harder to move, as it is generally quite hard to turn with the robot being mounted. We asked our local tech guy for help, and he suggested to measure the voltage across the phases when moving the motor. There is some voltage for all phases when moving, which according to him is equivalent of saying that the second trial is harder :P.
I hope this helps. Please let us know.

Best, Tobi

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
I dont really understand , 

> It is hard to tell whether the motor is harder to move, as it is generally quite hard to turn with the robot being mounted. 

what I was asking was moving the roll of the torso by pushing the robot left and right with your hand on the shoulder by instance.
if the robot is more difficult to move when the 3 phases on twisted together I would consequestly assume that the motor is not dead, if in the contrary, it is the same, the motor may be dead.
why would you tell me, it is because by attaching every phase you create a closing chain which create a back electromagnetical force which prevent from moving.
let me know

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
We can still move the robot after attaching all phases, however it is slightly harder to move the robot after attaching the phases. But we can definitely still move it. Does that mean the motor is broken?

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
To me everything is alright, so I guess it is the controlling board that has an issue, could you try to remove it and check if you dont have one of the diode (components attach to black heatsink) one should be burnt).
Let me know

**Comment by julijenv** [comment]
ANy news?
@Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
Please see my messages on Skype asking for some clarifications :)

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
The motor control board arrived today. However, we are missing the glue. Do you have a reference number so we can order it at Farnell / RS?

Thanks, Tobi

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
We replaced the motor board, and tried to run the robot. However, `yarprobotinterface` reported some problems. We had a closer look, and found that one of the cables got damaged.
![whatsapp image 2018-08-07 at 12 40 37 pm](https://user-images.githubusercontent.com/5497832/43774046-acbd8362-9a3f-11e8-827d-e2a06107fccf.jpeg)

When trying to re-crimp the cable, the small black wire broke off, and now the cable is unusable. Is the part an encoder? Could we order a new one, with all the cables properly attached?

Thanks a lot,
Tobi

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
I am checking and i will make your sensor + cable and i will send it to you.

**Comment by Tobias-Fischer** [comment]
You're a champ, thanks @julijenv

**Comment by julijenv** [comment]
Hi @Tobias-Fischer ,
should leave soon to reach you ( the package, I mean)
C U soon

**Comment by Tobias-Fischer** [comment]
It seems like all is working okay. Maybe the iCub just needed a little break ;-). I'll open a separate issue in case we run into new problems.
Thanks again for all your help @julijenv.
