### ISSUE TITLE
Neck cable broken during walking experiment

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-support#668]
### Description of the failure
During a walking experiment the a cable on the neck joint was broken. 

### Detailed conditions and logs of the failure
During a walking session one of the neck cable was broken, this was due an undesired impact with the rope of the crane.

**Comment by julijenv** [comment]
has been reapired
it has been taken for mthe warehouse
IITCODE Qta Desciption
5965 x 1 : neck cable A
