### ISSUE TITLE
Plastic protection for finger cables broken

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#67]
On the left hand, pinky finger, one of the plastic parts that protects the cables on each phalanges is broken and needs to be replaced.
![img_20150930_161246](https://cloud.githubusercontent.com/assets/12236986/10195495/30d7a2aa-678e-11e5-836c-06befe112d9b.jpg)

**Comment by spada1978** [comment]
positioned rubber cover electrical wires fingers

**Comment by bhigy** [comment]
Thanks !
