### ISSUE TITLE
Fault button stopped working on iCubGenova04

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/icub-support#670]
### Description of the failure
The Fault button stopped working.

### Detailed conditions and logs of the failure
After a first failure of the low level torque control, we had to use it once. After running all joints again through the **Yarpmotorgui**, everything seemed fine, except that hitting again the fault button will have no effect on the robot.

**Comment by julijenv** [comment]
some cable from the skin right leg cover where touching the chassis, and consequently prevented the fault button to work
