### ISSUE TITLE
Replacement tendons needed

### ISSUE THREAD

**Issue by emilio-cartoni** [robotology/icub-support#671]
Today our cable 7 in the right shoulder broke but we have no ready replacement (we only have replacement for hand tendons).
I've read in #225 that keeping 3x replacements for all arm tendons (5 xfor cable 7 and 8) is suggested, so we would like to make an order to get 3x of all cables, 5x for cable 8 and 6x for cable 7 (since it just broke).

We might also be interested into head and torso tendons, can we get a quote for them as well?
(we don't move that joints much, so maybe just 1x?)

**Comment by julijenv** [comment]
Hi @emilio-cartoni ,
could you please contact andrea.derito@iit.it or send me a direct email at julien.jenvrin@iit.it  with the name  (email fo your superior) in order to start a quotation - I know we have a set of cable for V1 robot and V2 robot, I think it will be fast.
let me know

**Comment by emilio-cartoni** [comment]
Hi @julijenv !
I've sent you an email with the request and my supervisor in copy :)

**Comment by julijenv** [comment]
hi @emilio-cartoni ,
send me a picture of your robot neck and forearm please

**Comment by emilio-cartoni** [comment]
![img_20180612_151029](https://user-images.githubusercontent.com/18488075/41292673-8782c444-6e53-11e8-91b1-6bfe2bc4ef57.jpg)
![img_20180612_150955](https://user-images.githubusercontent.com/18488075/41292674-87a98822-6e53-11e8-90f7-cb31417f4e41.jpg)
![img_20180612_150949](https://user-images.githubusercontent.com/18488075/41292675-87c8962c-6e53-11e8-8c2c-a1ec133fbdd4.jpg)
![img_20180612_151004](https://user-images.githubusercontent.com/18488075/41292676-87e5302a-6e53-11e8-97c5-8c6cfc917f6b.jpg)

**Comment by julijenv** [comment]
Hi @emilio-cartoni , you received the tendons, AM I right?
if yes, could you close this issue , thx in advacen
