### ISSUE TITLE
Left hand index distal actuator not working

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-support#672]
### Description of the failure
The actuation of the left index is limited since the actuation of the distal part of the index does not seem to be working.

### Detailed conditions and logs of the failure
Moving the distal joint of the left index from `yarpmotorgui` does not yield any results.

**Comment by julijenv** [comment]
it has been taken from the warehouse
IITCODE Qta DEscription
2391 x 0.5m: cable carlstahl 0.61mm coated
