### ISSUE TITLE
Right shoulder tendon popped up

### ISSUE THREAD

**Issue by towardthesea** [robotology/icub-support#676]
### Description of the failure
As the title says, the right arm of Blackie is malfunction due to the broken tendon, which can be seen by bare eye.

### Detailed conditions and logs of the failure
It happened just after I turn on the `yarprobotinterface`.

**Comment by towardthesea** [comment]
Please consider that we will have a demo with **Blackie** tomorrow (20/06/2018).

cc @pattacini @vtikha @Arya07

**Comment by julijenv** [comment]
Hi @towardthesea ,
the cable was not broken , needless to say that ist was posisble to see it by the bare eye :D:D:D:D:D.
I rewre everything, you can play now

**Comment by towardthesea** [comment]
Thanks @julijenv  for your decent talent :+1:

**Comment by towardthesea** [comment]
Please check the log files with error @julijenv 


[popout_logs.zip](https://github.com/robotology/icub-support/files/2115986/popout_logs.zip)
Thanks :+1:
