### ISSUE TITLE
Torso failure on Bluey

### ISSUE THREAD

**Issue by hagenlehmann** [robotology/icub-support#68]
Blue iCub collapses after calibration frequently because of hardware failure in one of the torso joints.

cheers,
Hagen

**Comment by pattacini** [comment]
@hagenlehmann is this issue really fixed? I've seen people still struggling to figure it out.

**Comment by hagenlehmann** [comment]
After Marco’s intervention we (Frank, Reza and I) have not experienced any further problems last week. 
Giulia just told me that she has experienced the error once in the last two days. She talked to Julien and they found a problem with one of the encoders. I was not aware of this, sorry - I will reopen the issue

**Comment by pattacini** [comment]
:+1: thanks

**Comment by julijenv** [comment]
it has been changed once more the sensor of the belly, let's hope that it will solve the issue once for all, or else I guess that you will need to find the root of the issue somewhere else.
