### ISSUE TITLE
Neck backlash 

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#681]
### Description of the failure
During random checks, we noticed that the neck of `iCubGenova04` has some backlash. By blocking the neck gears with the fingers, we get the following 

![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/5045846/42285280-680156f4-7faf-11e8-85e5-a1c160e2f8ce.gif)

It seems that the purple robot does not have this problem (checked also on `iCubGenova01`)

![ezgif com-video-to-gif 4](https://user-images.githubusercontent.com/5045846/42285302-7a442436-7faf-11e8-91f2-096d5df95146.gif)

### Detailed conditions and logs of the failure
None.

**Comment by spada1978** [comment]
Intervento Meccanico 
 
Parte Dx del collo 
Serraggio vite di fissaggio flax plain lato dx del collo; 
modifica serraggio tensionatori cavo A del collo; 
Sostituzione del cavo del collo A, previa posa di colla Attack sui pezzi RC_IIT_010_P_071 e sulla piastrina RC_IIT_010_P_072, per il fissaffio della parte sguainata del cavo; 
rifacimento cablaggio del cavo 
 
Parte Sx del collo 
a seguito di giri a vuoto del motore/puleggia si e riscontrato come l-albero dell harmonic drive si fosse sfilato dalla stessa in quanto i gradi non hanno tenuto (evidentemente posiziobato male non sulla parte piatta dellalbero stesso); 
montaggio corretto dell-albero e chiusra del pacchetto pulegge. 
 
Si suggerisce come detto da Marco Maggiali, apertura commessa per la realizzazione dei seguenti pezzi meccanici: 
RC_IIT_010_P_071 codice IIT 6791 
RC_IIT_010_P_072 codice IIt 6792 
 
Resta da verificqre il tipo di materiale, sarebbe opportuno
