### ISSUE TITLE
Right sole skin cable broken

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#682]
### Description of the failure
The cable to connect the right sole is slightly broken, just a matter of time for it to be completely ripped.

### Detailed conditions and logs of the failure

When attaching the sole skin to the right foot, we saw that one of the cables is slightly ripped.
See picture:
![img_20180705_142525](https://user-images.githubusercontent.com/7060968/42324081-67e79e90-8062-11e8-979c-eeb2d8049ca1.jpg)

**Comment by DanielePucci** [comment]
CC
@spada1978

**Comment by davidetome** [comment]
Fixed by Gandini; 11N2 has been repalced. Now it works.
