### ISSUE TITLE
Missing MTBs on EMS10

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#685]
### Description of the failure
The `yarprobotinterface` shows continuously errors on the ems10:
```
2775	6,529087	ERROR	 from BOARD 10.0.1.10 (left_leg-eb10-skin), src CAN2, adr 0, time 82s 519m 107u: (code 0x00000019, par16 0x0301 par64 0x0000000000000000) -> SYS: EOtheCANservice could not tx frames on CAN bus. In par16 there is: on msb the size of txfifo, on lsb a code. + .
2776	6,529122	WARNING	 from BOARD 10.0.1.10 (left_leg-eb10-skin), src LOCAL, adr 0, time 82s 519m 255u: (code 0x0000000d, par16 0x0371 par64 0x0300037102e8015e) -> SYS: the TX phase of the control loop has last more than wanted. In par16: TX execution time [usec]. In par64: num of tx can2 and can1 frames and latest previous execution times of TX, RX, DO [usec] + .
```

### Detailed conditions and logs of the failure
After the left lower leg skin has been repaired as in https://github.com/robotology/icub-support/issues/683, we detached the skin soles for some walking experiments.
After detaching them we got a lot of errors on board 10, see log: 
[log_icub-head_yarprobotinterface_28691_skin10.txt](https://github.com/robotology/icub-support/files/2177226/log_icub-head_yarprobotinterface_28691_skin10.txt)

At first we thought about a firmware mismatch, as on the ems10 there was a different version, we updated the firmware but the errors were still there.
From the firmware updater we then saw that there are some missing MTBs (compared with ems 11):
![skin](https://user-images.githubusercontent.com/7060968/42464986-09f6055a-83ab-11e8-8c6f-fef6a0474987.png)

**Comment by davidetome** [comment]
We noticed that on the new EMS **EB10**  we forgot to close the jumpers to make CAN line terminated.
With the sole it works because on the last MTB3 of the CAN BUS (in the sole precisely) the termination is present.
Now all MTBs are reachable.
