### ISSUE TITLE
Green_icub cameras not working on the head

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-support#686]
### Description of the failure

When
```
yarpdev --from camera/ServerGrabberDualDragon.ini --split true 
```
We face the following error:

![cam_error](https://user-images.githubusercontent.com/36491318/42505439-080e0f6e-843f-11e8-8a4c-aed2719b8e34.png)

@hu-yue 

### Detailed conditions and logs of the failure
This is within the context of running the Oculus with the head on the `iCubGenova04`
[icub_cameras.txt](https://github.com/robotology/icub-support/files/2179991/icub_cameras.txt)

**Comment by mebbaid** [comment]
@traversaro if you can manage a 15 minutes, would be appreciated.

**Comment by mebbaid** [comment]
Several reboots seems to do the trick !

**Comment by Nicogene** [comment]
For my personal experience it is firewire fault, unplug and plug it in the head or reboot usually does the trick!
