### ISSUE TITLE
Right shoulder tendon pop up (again)

### ISSUE THREAD

**Issue by towardthesea** [robotology/icub-support#688]
It happened as similar as [this issue](#676) after normal motion of robot and physical interaction with human. No hard collision took place.

Thanks @spada1978 of having a look on it.

**Comment by spada1978** [comment]
sono stati sostituiti i cavi n.6 - 7 e 8 in quanto la guaina di protezione del cavo di acciaio era spellata e in alcuni punti rotta pertanto il cavo si infilava tra le pulegge.
I cavi cambiati sono:
4763.1
4764.1
4765.2
e stato successivamente effettuato il nuovo cablaggio.
Si consiglia di effettuare up-grade del giunto spalla in quanto ancora di tipo V1
