### ISSUE TITLE
Issues after IROS demo

### ISSUE THREAD

**Issue by alecive** [robotology/icub-support#69]
* [x] FT sensor on left leg is spiking and needs to be replaced (the one in the SS toolbox is probably not calibrated)
 * [x] Hall sensor, left hand, index, proximal is flaky (i.e. `licchelacche`)
 * [x] Neck harmonic drive (right hand side) gets stuck (o da ingrassare o da cambiare)
 * [x] Fingertip on left hand got broken by hard interaction with a bad robot (reincollare testare funzionalitá)
 * [x] Right Hand thumb Proximal Joint. Tendon broken or about to break. Inspect and check.

**Comment by pattacini** [comment]
Don't use the robot name in the issue title, we have the labels for that :smirk:

**Comment by super-ste** [comment]
@pattacini label suck I prefer the name in the title. It's clearer and easier to look.

**Comment by pattacini** [comment]
That's at least questionable.
With labels you have a much easier way to sort issues by robots.

**Comment by alecive** [comment]
With titles you have a better way to sort issues by robots **without** resorting to a further step ( ie filtering them by hand).

**Comment by pattacini** [comment]
Where is the option to sort by *issue title*? To do so, you have to fill in the search field with the robot name.

By contrast, with labels, you just click on the desired robot label and that's all folk.

**Comment by spada1978** [comment]
Repaired proximal thumb right hand and glued fingertip left hand anulare

**Comment by spada1978** [comment]
Replaced ft sensor s7n 209

**Comment by spada1978** [comment]
Neck harmonic drive fatted (right hand side)

**Comment by spada1978** [comment]
verified sensor proximal index and middle everything is working properly

**Comment by pattacini** [comment]
Thanks @spada1978 
If you deem this issue complete, please close it.

**Comment by spada1978** [comment]
It was not closed because it lacks the functionality test of the repaired finger tip, but if you feel like I close

**Comment by pattacini** [comment]
Nope, go ahead, I thought all the points of the issues were addressed.
