### ISSUE TITLE
Right hand thumb seems broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-support#693]
### Description of the failure
During a walking experiment the right hand impacts the right leg and the thumb seems broken. 

### Detailed conditions and logs of the failure
In the following a `gif` is attached. In details:
1. we put the finger in idle
2. we run the finger
3. at the first touch the finger is closed  
4. we cannot move from the `yarpmotorgui` 

![out](https://user-images.githubusercontent.com/16744101/43219336-500e60d4-9047-11e8-958f-d236656d45f0.gif)

cc @hu-yue  @mebbaid

**Comment by julijenv** [comment]
it has been restored.
IITCODE  Qta Description
1815 x 1m : cable carlstahl 0.63mm non coated

**Comment by GiulioRomualdi** [comment]
Thank you @julijenv !
