### ISSUE TITLE
neck cable broken

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#695]
The neck cable if the iCub broke yesterday. Please take a look to the red arrows in the picture. The simetrical cable seems alright. 

![img_20180801_113935](https://user-images.githubusercontent.com/11769446/43514636-e2a7895a-9580-11e8-906f-e1ba488faf78.jpg)

**Comment by spada1978** [comment]
Il cavo rotto in oggetto e cavo B.
vengo nel pomeriggio ad effettuare la riparazione, in linea di massima per le 14:30 al massimo alle 15

**Comment by amaroyo** [comment]
perfetto! Grazie mille!

**Comment by spada1978** [comment]
ho effettuato la sostituzione del cavo B del collo ma durante la lavorazione si è verificato il problema tra la puleggia e il supporto porta cavi.
e stato chiesto supporto a Torrazza quindi si procederà con la sostituzione del pezzo non appena la commessa di officina sarà pronta.

**Comment by julijenv** [comment]
it has been replaced also the cable A of the neck after being a bit worn out.
I checked both motor and the ballbearing part of the harmonic drives , I remove the dust from one, and consequently check the moving of the neck entirely
I couldnt find any problem related to the neck afterwards.
IITCODE Qta Description
5965 x 1 : HEAD CABLE A
