### ISSUE TITLE
Right shoulder tendon broken

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#696]
### Description of the failure

The tendon of the right shoulder is broken, it has been ripped apart.

### Detailed conditions and logs of the failure

During the teleoperation task, the shoulder performed a fast movement which ripped off the shoulder tendon, see picture below.
![photo_2018-08-01_18-14-48](https://user-images.githubusercontent.com/7060968/43534110-ced810c6-95b6-11e8-9f48-2c7310fea6ee.jpg)

FYI @DanielePucci @GiulioRomualdi @mebbaid

**Comment by hu-yue** [comment]
The shoulder has been repaired. It seems to be working fine. Thanks for repairing!

**Comment by DanielePucci** [comment]
CC @fiorisi 

We shall re-start working on strengthening iCub shoulders
