### ISSUE TITLE
Tendon of right shoulder jumped out

### ISSUE THREAD

**Issue by xEnVrE** [robotology/icub-support#697]
### Description of the failure
The tendon of the right shoulder jumped out and it is not in its housing.
![img_20180803_115213680](https://user-images.githubusercontent.com/6014499/43637801-a481180c-9716-11e8-93c0-29673de9b496.jpg)

**Comment by spada1978** [comment]
Non dovrebbe essersi rotto il cavo.
Appena è disponibile il robot vengo a controllare

**Comment by spada1978** [comment]
ho sostituito la vite 2,5 x 10 TCEI del tensionatore del cavo n.5 in quanto si era rovinato il filetto e non lavorava correttamente.
Successivamente ho effettuato il cablaggio.
Robot Ok
