### ISSUE TITLE
Robot shuts down during retargeting

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#700]
### Description of the failure

We were performing arm motions retargeting with walking (but the robot was not walking yet, however the walking controller was running), when the robot shuts down suddenly, i.e. switches off all motors, similar to when it goes in overcurrent.

### Detailed conditions and logs of the failure

The setup was: battery + wifi.
Retargeting setup: Oculus and Cyberith.
Running modules: walking controller and retargeting modules for hands and walking.
The robot was standing on the floor, we ran all the modules. It was not walking, we tried to move the arms in several positions. At a certain point the robot just crashed, shutting down all the motors.

The log is as follows: 
[log_icub-head_yarprobotinterface_1876.txt](https://github.com/robotology/icub-support/files/2275014/log_icub-head_yarprobotinterface_1876.txt)

We are not sure about the reasons. But it has happened every time we tried the demo today, i.e. about 4 times.
We see some hardware limit reached, but would this induce to shutting down the robot?
Thanks!

P.S. we tried the same setup with the power supplier instead of the batter, just to test if it was a power issue. The robot is still shutting down some times.

**Comment by julijenv** [comment]
Hi @hu,
From what I could have done it is more than probble than the facct that the cable 9 break make some short circutis or move the boards and create the problem. I btw recrimp 2 crimps of the conenction in between the board EB24 e EB25.
