### ISSUE TITLE
Left elbow tendon broken

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#701]
### Description of the failure

During one of the walking experiments, the left elbow tendon broke.

### Detailed conditions and logs of the failure

Please fin below the picture of the broken tendon (it seems that one has popped out and one is broken):
![brokenelbow_tendons](https://user-images.githubusercontent.com/7060968/43918230-cc8de2ac-9c12-11e8-9341-36e43d599aaa.jpeg)

**Comment by julijenv** [comment]
it has been replaced the cable n9 of the left elbow
ITICODE Qta DEscription
4766 x 1 : ELBOW CABLE 9
