### ISSUE TITLE
Neck and battery broke due to falling 

### ISSUE THREAD

**Issue by mebbaid** [robotology/icub-support#702]
### Description of the failure
While teleoperating the robot walking and grasping using the Oculus and the Virtualizer platform, the robot fell on its back.

### Detailed conditions and logs of the failure
Possible reasons would be battery dying out, and fault line stuck.
The following video demonstrate the event

![ezgif com-gif-maker 1](https://user-images.githubusercontent.com/36491318/44087424-12b774ae-9fc0-11e8-9fb7-0917d64bbe2f.gif)

### Note
We are not sure if the only part broken is the neck. It is still to be verified.

@hu-yue

**Comment by hu-yue** [comment]
After @julijenv repaired the neck, the robot is working fine, we have tested several things and no issues arose.

However, it has to be noted that the battery that was inside (the "green-ish" one) has broken during the fall, in particular it seems that the BMS is broken, apart from some part of the plastic holder. Few hours after the fall, the BMS was very hot and still today (two days after) it was warm. @MrAndrea is taking a look at it.

**Comment by MrAndrea** [comment]
I checked the battery and I found wires broken under the BMS board, and short circuits between some Lithium cells and BMS. I repaired the wires but the BMS seems burned.

![img_20180817_092210](https://user-images.githubusercontent.com/20459541/44389238-9a419980-a52a-11e8-97d9-c174d880480e.jpg)
![img_20180817_092704](https://user-images.githubusercontent.com/20459541/44389241-9a419980-a52a-11e8-8143-df36e013ab14.jpg)
![img_20180817_092919](https://user-images.githubusercontent.com/20459541/44389243-9a419980-a52a-11e8-82e8-36c5ed7c0037.jpg)
![img_20180817_093326](https://user-images.githubusercontent.com/20459541/44389244-9a419980-a52a-11e8-9641-291a0cb7a560.jpg)
![img_20180817_094529](https://user-images.githubusercontent.com/20459541/44389245-9ada3000-a52a-11e8-8109-de63affa01b7.jpg)

**Comment by MrAndrea** [comment]
I have the offer from the supplier regarding a new BMS, and I'm waiting for it.

**Comment by hu-yue** [comment]
The robot fell again, and we broke another battery. The status seems a bit better than the previous one. The battery has been handed to @MrAndrea. 
Now we have two batteries left, one with working LEDs and one with not working LEDs. The one with not working LEDs cannot be housed properly in the battery pack, i.e. it had connection issues and we could not use it eventually. We are not sure if this might be due to the housing deformed after the fall or the battery itself, or both.

**Comment by hu-yue** [comment]
cc @DanielePucci, @S-Dafarra, @GiulioRomualdi

**Comment by DanielePucci** [comment]
Thanks to @MrAndrea and @maggia80, batteries have been repaired. We currently have three working batteries
