### ISSUE TITLE
Start-up failure due to communication errors on left leg boards.

### ISSUE THREAD

**Issue by ahmadgazar** [robotology/icub-support#707]
### Description of the failure
iCub is failing to start-up  due to communication erros on the left leg boards as stated here:

![image](https://user-images.githubusercontent.com/15094592/44720765-19eddc00-aac8-11e8-8b33-f8cdcce03bf0.png)

We restarted the robot a couple of times, however the error remained the same.
@julijenv 

### Detailed conditions and logs of the failure
Details can be found on the attached log file.
[log.txt](https://github.com/robotology/icub-support/files/2327829/log.txt)

cc: @fjandrad

**Comment by marcoaccame** [comment]
@julijenv: the CAN cable on EB6:CAN2 is either unplugged or broken. The EB6 board cannot send CAN message to the STRAIN and complains w/ the above messages.

**Comment by ahmadgazar** [comment]
Exactly @julijenv fixed that. Thanks.
