### ISSUE TITLE
Neck and left hand cables broken during a walking experiment 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-support#710]
### Description of the failure
During a walking experiment one of the cable of the neck (left side) and the left hand cable broke. 

### Detailed conditions and logs of the failure
Unfortunately during a walking experiment some high frequency oscillations broke the the left neck cable and one of the cable of the hand. 
![photo5796368974148120408](https://user-images.githubusercontent.com/16744101/45040897-52149200-b067-11e8-8f4b-15b046614928.jpg)
![photo5798811517754388219](https://user-images.githubusercontent.com/16744101/45040923-6062ae00-b067-11e8-97dc-44ffac4a5f01.jpg)

**Comment by julijenv** [comment]
Hi @GiulioRomualdi ,
it has been repaired both cable A of the neck and the wrist tendon, I also perform so basic check on the left thumb that was showing some loosiness - I retensed it- and I tightend some scrwews at the level of the left elbow that had some backlash
IITCODE Qta DEscription
5965 x 1 : neck cable A
6419 x 1 : wrist cable V2
