### ISSUE TITLE
iCubGenova02: Broken left hand cover

### ISSUE THREAD

**Issue by FabioBergonti** [robotology/icub-support#713]
During an experiments the hand entered in contact with the ground, because icub falled down.  This broke the cover.

![20180907_062738](https://user-images.githubusercontent.com/38210073/45198549-5d361080-b267-11e8-96c9-909d5dc71878.jpg)
![20180906_191407](https://user-images.githubusercontent.com/38210073/45198556-645d1e80-b267-11e8-9966-217f0091a7c5.jpg)

Cc. @fiorisi

**Comment by julijenv** [comment]
done by mechanical designer I guess, so I close
