### ISSUE TITLE
iCubGenova02: Broken suspension hooks

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-support#714]
### Description of the failure

Both the suspension hooks are broken while running the standup demo.

![image](https://user-images.githubusercontent.com/6505998/45510771-7ffe8280-b79b-11e8-8d37-42bedddaaa88.png)

**Comment by hu-yue** [comment]
cc @julijenv as discussed F2F, probably it is better to check also inside the covers. The broken part is now stuck inside and we could not remove it.

**Comment by julijenv** [comment]
This has been resolved, please test if the robot restarted and close the issue, thx in advance

**Comment by hu-yue** [comment]
Thanks @julijenv, we started the robot and everything is working fine except for a problem on the neck, which is giving this error, even if we run it, after few seconds it goes back into hw fault:
```
[ERROR] from BOARD 10.0.1.20 (head-eb20-j0_1), src LOCAL, adr 0, time 498s 865m 437u: (code 0x02000002, par16 0x0000 par64 0x0000000000000000) -> MC: i2t limit exceeded. The motor has been turned off to prevent it from being damaged by overheating due to a continuous high current. par16 = ID of joint. + .
```
should I close this and open one just for the neck issue?

**Comment by hu-yue** [comment]
There was a screw stuck in the neck causing the issue.
It has been removed and now everything is working fine except for the fingers as in #715.
Closing.
