### ISSUE TITLE
iCubGenova02: Broken left hand wrist plastic

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-support#716]
### Description of the failure

The plastic cover at the wrist of the left hand is broken during the standup experiment.

![left-hand](https://user-images.githubusercontent.com/6505998/45570708-ef3fa980-b863-11e8-995b-380ad75d3a75.jpg)

**Comment by hu-yue** [comment]
It was glued and now it's broken again.
We arranged a temporary "arrangement" to use the robot without breaking further the wrist.
I think the palm cover has to be replaced, maybe we can order the pieced and replace it, also considering that the robot has been scheduled to be off for about two weeks starting from the 10th October. 

cc @fiorisi @FabioBergonti @julijenv 

See pictures below:
![palmo_sx_rotto](https://user-images.githubusercontent.com/7060968/46544655-7791f700-c8c4-11e8-9a3f-f5114f0d61ee.jpg)
![palmo_sx_imballato](https://user-images.githubusercontent.com/7060968/46544654-7791f700-c8c4-11e8-940f-1aa3fd8fe602.jpg)

**Comment by Yeshasvitvs** [comment]
@hu-yue I am assuming this is fixed. Please close the issue if this is no longer required.
