### ISSUE TITLE
Hardware fault and torque shortfall 

### ISSUE THREAD

**Issue by ChiaraBartolozzi** [robotology/icub-support#72]
We have been experiencing random hardware fault and torque shortfalls on iCubGenova02. 

Either of these issues occur at any time, e.g. during calibration or run-time tests. A control board failure is the worst case, which requires a power cycle and a reboot of the robot interface. -- possibly linked to issue 
A torque shortfall can compromise a specific task or eventually the robot stability. For instance, if the torque shortfall occurs during calibration, the joint may not reach the desired value within the expected time, thus leading to the calibration failure “timeout before reaching position 0...”. -- possibly linked to issue #52 (Purpley) 

We suspect that these problems are related to the hardware.

@hu-yue @nunoguedelha @DanielePucci @randaz81 @maggia80 @giorgiometta @Fabrizio69

**Comment by hu-yue** [comment]
Hi, can I know if this issue also might affect iCubHeidelberg01 or now you're sure that this is not going to happen?

**Comment by DanielePucci** [comment]
Hi @hu-yue, we are still investigating the causes of these hardware faults/torque shortfalls. So, no conclusion has been derived yet. We will keep you in the loop.

**Comment by hu-yue** [comment]
Ok thanks, I'll keep an eye in case something similar happens to our robot.
