### ISSUE TITLE
Broken wire to Zynq

### ISSUE THREAD

**Issue by Iaxama** [robotology/icub-support#723]
One of the wires going from the new boards mounted on the left hand of the robot to the zynq board are broken (tested with multimeter).

Probably during one of last fixes on the arm in which the cable was cut and rejoined with a connector, one of the wires got loose.

**Comment by julijenv** [comment]
Did anyone of you guys, test if it works, I mean not just the wire that I repair but the overall connexion?!?!?
close if evrything os, thx in advance
@Iaxama , @ChiaraBartolozzi , @marco-monforte
