### ISSUE TITLE
Right shoulder and elbow cable broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#724]
### Description of the failure
While performing the Yoga ++ demo and touching the robot right arm, the right shoulder and (later) the elbow cable got broken. See the attached pictures:

![photo5857205407779499625](https://user-images.githubusercontent.com/12396934/45966642-f87f0200-c02b-11e8-8733-217cdd876be8.jpg)
![photo5857205407779499624](https://user-images.githubusercontent.com/12396934/45966643-f87f0200-c02b-11e8-80f3-1573bcf0632b.jpg)
![photo_2018-09-25_09-48-19](https://user-images.githubusercontent.com/7060968/46000178-299d1800-c0a8-11e8-8283-b09c559f75fa.jpg)

**Comment by julijenv** [comment]
to repair and fix the robot elbow and shoulder i need to use
IITCODE Qta DEscription
4763.1 x 1 : shoulder cable N6
4764.1 x 1 : shoulder cable N7
4767.1 x 1 : elbow cable N10

looks like that it works like before again.
