### ISSUE TITLE
Left shoulder cable broken 

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#725]
### Description of the failure

While performing toque control demo, the left shoulder cable broke after a controller's failure.

**Comment by julijenv** [comment]
it has been changed shoulder cable N8 on which the crimp set the cable free.
IITCODE Qta DEscription
4765.2 x 1 : shoulder cable N8
Afterwars the shoulder has bee n rewired entirely and restart and lokks like it bahave correctly.
