### ISSUE TITLE
Torso Broken iCubGenova02

### ISSUE THREAD

**Issue by FabioBergonti** [robotology/icub-support#726]
### Description of the failure
The tendons of the torso are slack.

**Comment by julijenv** [comment]
Hi @FabioBergonti ,
it should be ok now

**Comment by FabioBergonti** [comment]
Hi @julijenv 
The torso behaves in a strange way, I've tried to command it using the `yarpmotorgui` and sending a variation on torso pitch, there are movements also in the other directions
It seems that some cables are not connected or they are connected in a wrong way

**Comment by FabioBergonti** [comment]
Solved
It was a firmware problem
