### ISSUE TITLE
One or more encoders of the left hand little fingers are broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-support#731]
### Description of the failure
During the IROS demos we noticed that the left little fingers were going continuously in hardware fault. With @julijenv we tried to perform calibration but the values were not moving. Also, @julijenv tried to move the magnets manually, but nothing changed. We suspect that some encoders are broken 

### Detailed conditions and logs of the failure
After calibration, the left little finger usually goes in hardware fault. This usually is not blocking anyway.

@DanielePucci @hu-yue @GiulioRomualdi

**Comment by julijenv** [comment]
has been restored but need to be recalibrated
