### ISSUE TITLE
Wrist cables broken left+right wrist

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-support#733]
### Description of the failure
When shutting down `yarprobotinterface`, the robot suddenly started shaking. By the time we pressed the red button, the right shoulder was broken, as well as several cables of the left and right wrist. We managed to fix the shoulder, but require some remote assistance to fix the wrist.

### Detailed conditions and logs of the failure
Please see the attached pictures for more details.

Right arm top-view - see one end of the broken cable (going to the tensioner)
![20181022_153804](https://user-images.githubusercontent.com/5497832/47300254-f2247b80-d613-11e8-97b0-ae380b815e2e.jpg)

Right arm side view - see other end of the broken cable (sticking out on top)
![20181022_154802](https://user-images.githubusercontent.com/5497832/47300341-213aed00-d614-11e8-91ae-2abd8a68c026.jpg)

Left arm view - similar damage as the right arm
![20181022_153857](https://user-images.githubusercontent.com/5497832/47300386-3748ad80-d614-11e8-96dc-f6159a21a856.jpg)

I am not sure what the correct procedure is to replace those cables. It would be great if you could briefly describe what to do here, or if you're available on Skype to have a quick chat. I think we will be okay once we know the rough procedure, but we don't want to take the wrong things apart.

If you need any more pictures from different angles, please let us know.

Best and thanks a lot in advance,
Tobi

/cc
@umgnunes

**Comment by umgnunes** [comment]
Hi.

We have managed to fix both wrists.

![img_20181025_104918](https://user-images.githubusercontent.com/28675245/47558667-90ae2680-d90b-11e8-9a65-f3d83cdcfaad.jpg)
![img_20181025_104933](https://user-images.githubusercontent.com/28675245/47558668-90ae2680-d90b-11e8-9b9c-57cea0df775b.jpg)

We have ensured that the cables were at least as tense as the other ones that were not broken. If more pictures are needed for you to corroborate, please let us know.

Now, we still have a broken cable related to the left arm middle finger, which again we are not sure how to correctly proceed to replace it. It would be great if you could briefly describe what to do here, or if you're available on Skype to have a quick chat.

Thank you for the support,
Urbano Miguel Nunes

/cc
@Tobias-Fischer

**Comment by julijenv** [comment]
Hi @Tobias-Fischer , @umgnunes ,
great job :+1: 
did you also succeed to redo the proxximal joint , I remember it was broken too?

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
We got the cable for the proximal middle finger joint and are in the process of repairing. We are feeding the wire through the tube, but it gets stuck at some point. Do you have any advice on what to do? Would be great to have a quick Skype chat.

Best, Tobi and Urbano

**Comment by julijenv** [comment]
it has been done from what I recall
