### ISSUE TITLE
Bosch IMU broken

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#734]
### Description of the failure

The Boschu IMU inside the head broke during a demo in Milan with Ericsson.

### Detailed conditions and logs of the failure

During walking, we heard a "crack" as if there was a short circuit, then the robot collapsed and `yarprobotinterface` could not run and showed errors on the Boschu IMU. We then checked and realized it was broken.

@DanielePucci brought a new sensor but we eventually did not mount it.

cc @GiulioRomualdi @julijenv

**Comment by maggia80** [comment]
I suggested to @julijenv to install the IMU Bosh connected via I2C (robotology/yarp#1743).
Since you have installed the new COM-Express (Kontron) it is worth to test this solution. @Nicogene, they may need some help.

**Comment by julijenv** [comment]
Hi @nunoguedelha , @S-Dafarra  and @DanielePucci , 
The IMU has been replaced and should be tested. Therefore please refer to @Nicogene .
@Nicogene , could you double check, as @maggia80  was suggested, that the substitution of the IMU is detected and useable,
 thx in advance.

**Comment by Nicogene** [comment]
@barbalberto  and I tried to launch the device but it gives a linking problem (undefined symbol) but both i2c header and .so are found by CMake.
Tomorrow we will ask to help to @drdanz if he knows if there might be some problem in FindI2c.cmake or in the installation process.
I never experienced such problem when I tried it on the pc104 in May 2018, we will keep you updated.

**Comment by drdanz** [comment]
Should be fixed now. Please let me know is there are still related issues.

**Comment by Nicogene** [comment]
@drdanz fixed the linking issue and @barbalberto and I fixed the runtime issue(https://github.com/robotology/yarp/pull/1920).

Now should be ok. 
I changed the xml on the green icub to run the i2c imu with the robotinterface, it is a local change on the `icub-head` I don't know if you want to push it in `robot-configurations`.
