### ISSUE TITLE
Head cage and cover broken

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-support#739]
### Description of the failure
As @julijenv noticed, the greeny's head cage is bent, while the plastic hear ring holding the face cover is broken. This is probably due to some fall the robot has undergone. 

### Detailed conditions and logs of the failure
- Face cage bent
![image002](https://user-images.githubusercontent.com/18591940/48311336-9f007180-e59e-11e8-8efb-60a20d051a16.png)
- Plastic ear ring broken
![image003](https://user-images.githubusercontent.com/18591940/48311346-b7708c00-e59e-11e8-844a-a8d6a8743d4b.png)

cc 
@DanielePucci @nunoguedelha  @gabrielenava @GiulioRomualdi

**Comment by DanielePucci** [comment]
@julijenv 
We would need support on this. May you give us a hand?

**Comment by julijenv** [comment]
Hi @DanielePucci ,
We saw with M. SAvoldi this morning that the frame is bent has from the picture already taken above (RC_IIT_030_P_010) but we also found out that the T shape holding the tilt motor and making a cube with the frame is also bent but more badly(RC_IIT_010_P_051).
I will see if we have this latter piece on stock and try to replace it, rebending the first piece as it is simpler and a quick fix for the overall head.
The best fix would be to make n upgrade but I fear that the robot will fall again so to me , quick fix could be less expensive and take less time on the robot.

**Comment by DanielePucci** [comment]
@julijenv 
Thanks, great!

**Comment by DanielePucci** [comment]
Hi @julijenv, do you have any update on this?

**Comment by DanielePucci** [comment]
Hi @julijenv, do you have any update on this?

**Comment by julijenv** [comment]
Hi @DanielePucci ,
cover head had been recreated 2/3 weeks ago, 2 days ago with the help of M. SAvoldi we replaced the T-shape of the face cage and we also the reshape the plate on which lie the inertial sensor
