### ISSUE TITLE
Encoders not calibrated

### ISSUE THREAD

**Issue by massimoregoli** [robotology/icub-support#74]
Several encoders on both hands of the purple iCub are not properly calibrated

**Comment by julijenv** [comment]
After a little check on the right hand, it appears that the thumb abduction joint is broken

**Comment by lornat75** [comment]
Was this fixed?

**Comment by massimoregoli** [comment]
the thumb abduction joint is now working properly but the right thumb joints 8 and 10 still have calibration problems

**Comment by super-ste** [comment]
is this issue the same as #66 ?
Shall we close this guy and keep following up on the other one instead?

**Comment by massimoregoli** [comment]
No it's a different issue, this is just about calibration problems

**Comment by julijenv** [comment]
is it alright now? @massimoregoli
