### ISSUE TITLE
Broken shoulders, fingers, skin on the finger tips...

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#742]
Help @julijenv!

Right shoulder 2 cables broken.
Left hand pinkie finger broken. 
Random skin broken on the figer tips.

See you!

**Comment by julijenv** [comment]
It has been changed cable N5 as usual the wear cable N8. The j15 of the left hand was Ok, just out of boundary.
One of the right index fingertip wires is broken and prevent the fungertip to broacast data. With @reafrancesco we forecast a replacement of those wires when the robot will perform an update of the head.
