### ISSUE TITLE
High current load melted wires in waist

### ISSUE THREAD

**Issue by Iaxama** [robotology/icub-support#743]
### Description of the failure
While launching yarprobotinterface high current load in a wire at the level of waist caused melting of surrounding plastic and of the board attached to it. 
During the startup phase of yarprobotinterface the calibration never started, however the robot slightly moved the torso before starting to smoke, forcing us to shut it down.

### Detailed conditions and logs of the failure
I attach pictures showing the damages and the log of yarprobotinterface.

![photo5785396049966378982](https://user-images.githubusercontent.com/5638912/49575245-85a2d900-f942-11e8-9b1b-1bd33f3fd372.jpg)
![photo5785396049966378981](https://user-images.githubusercontent.com/5638912/49575246-85a2d900-f942-11e8-8491-7216f2880c31.jpg)
![photo5785396049966378980](https://user-images.githubusercontent.com/5638912/49575248-85a2d900-f942-11e8-804d-9e814b07d66e.jpg)
![photo5785396049966378976](https://user-images.githubusercontent.com/5638912/49575249-863b6f80-f942-11e8-8a83-8511f8021aa4.jpg)
[log.05dec18.h1245.txt](https://github.com/robotology/icub-support/files/2652415/log.05dec18.h1245.txt)

**Comment by MrAndrea** [comment]
Thanks to @julijenv and Emiliano who replaced the cables and boards. I programmed the BDC board inside the backpack since it was not already programmed, and I decided to put the hardware limit of the maximum current to 32A by replacing the shunt resistor on the board with two 3mohm resistors in parallel.

**Comment by julijenv** [comment]
#748
