### ISSUE TITLE
A few accelerometers on the left leg stopped working after calibration tests

### ISSUE THREAD

**Issue by nunoguedelha** [robotology/icub-support#744]
### Description of the failure
While running a test on the accelerometers for calibrating their offsets, I've realized that the accelerometers 10B5, 10B6, 10B7 on the left upper leg where returning frozen values instead of the expected varying gravity measurement.

### Detailed conditions and logs of the failure
During the sensor data acquisition, the leg was moving slowly between two limit positions of the hip yaw: `hip_pitch (-20), hip_roll(+90), hip_yaw(-60) --> hip_pitch (+40), hip_roll(+90), hip_yaw(+60)`

Before the test I checked the joints limits while moving the leg in Idle mode. By accident I let it fall and it hit the pole (left leg upper cover, the same where the accelerometers are fixed), so that's a potential cause.
Other possibility is that some cable got ripped during the leg movements.

No log available yet (yarprobotinterface). I'll take one on Monday.

**Comment by nunoguedelha** [comment]
CC @fjandrad

**Comment by DanielePucci** [comment]
Hi @nunoguedelha, did this issue happen again?

**Comment by nunoguedelha** [comment]
Hi @DanielePucci , I've just tested (full accelerometers calibration of the left leg): **the issue is no more reproducible**.
Closing...
