### ISSUE TITLE
Right leg hip pitch in hardware fault, encoder invalid measure

### ISSUE THREAD

**Issue by fjandrad** [robotology/icub-support#745]
### Description of the failure
After performing some movements on the pole (usual movements), the right leg hip pitch went into hardware fault and it can not be idled.

### Detailed conditions and logs of the failure 
When rising the robot with the crane the right leg hip pitch went into hardware fault 
 <ERROR>  from BOARD 10.0.1.8 (right_leg-eb8-j0_3), src LOCAL, adr 0, time 1143s 344m 163u: (code 0x02000008, par16 0x0000 par64 0x0000000000000002) -> MC: AEA encoder invalid data. Hardware problem in the magnetic position sensor of the joint caused invalid position readings. par16 = AEA port (msb) and ID of joint (lsb). + .
[log_icub-head_yarprobotinterface_8327.txt](https://github.com/robotology/icub-support/files/2663603/log_icub-head_yarprobotinterface_8327.txt)

cc @GiulioRomualdi @DanielePucci @S-Dafarra @gabrielenava

**Comment by fjandrad** [comment]
Update: 
After restarting the motors it did not happen again. We might try a few more times tomorrow and see if it repeats.

**Comment by GiulioRomualdi** [comment]
This morning Emiliano has checked the robot. It seems there are no problems related to the connection and since the problem disappears after restarting the robot, we cannot exclude that the issue is related to the board itself.

**Comment by fjandrad** [comment]
Update: 
It happened again once more. Rebooting the motors makes the error go away.

I do not know if it might be caused by static discharges (everyone is having) .

After rebooting and trying to discharge before touching the robot , the error did not present again.
