### ISSUE TITLE
Left shoulder cable broken

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-support#747]
### Description of the failure
While performing the Yoga ++ demo, the left shoulder got broken. Spikes coming from the encoders maybe cause the issue.

![photo5807919640150651280](https://user-images.githubusercontent.com/16744101/49952867-283bf880-fefd-11e8-9cd3-fa18416fed67.jpg)
 
cc @S-Dafarra @DanielePucci @julijenv

**Comment by kouroshD** [comment]
From the following figure you can see the spikes coming from the left arm encoders

![screenshot from 2018-12-13 17-35-25](https://user-images.githubusercontent.com/17707730/49953045-91bc0700-fefd-11e8-9e08-9fa7cbb4920e.png)

In the following you can find the data collected
[backupYogaAfterSpikesLeftArm.zip](https://github.com/robotology/icub-support/files/2676888/backupYogaAfterSpikesLeftArm.zip)

**Comment by julijenv** [comment]
Hi @kouroshD , could you please tell me which joint are we talking about??? which encoder (AEA I presume)?
for @GiulioRomualdi , it has been replaced 2 cables of the left shoulder
IITCODE Qta Description
4765.2 x 1 : cable shoulder 8
4758.1 X 1 :shoulder cable N1

**Comment by GiulioRomualdi** [comment]
@julijenv thank you for your prompt intervention. 
As regards the left arm encoder I was talking about the shoulder and elbow encoders. Here a screenshot af the data collected  using simulink. 
* left_arm 1: shoulder pitch
* left_arm 2: shoulder roll
* left_arm 3: shoulder yaw
* left_arm 4: elbow

![schermata del 2018-12-13 19-40-43](https://user-images.githubusercontent.com/16744101/49959884-18c5ab00-ff0f-11e8-82e0-40a8a47650ae.png)

The issue seems to be similar to that one https://github.com/robotology/icub-support/issues/624

**Comment by traversaro** [comment]
The fact that the spikes are synchronized among the different axis may suggest that the spike does not come from the raw encoder, but rather from some bug in the software architecture. It is easy to reproduce the issue? It would be great to get discrete datasets (no plots) and also read the motor encoders to understand what the problem is.

**Comment by DanielePucci** [comment]
@kouroshD - helped by @GiulioRomualdi - please run the Yoga++ demo and see if these spikes occur again

**Comment by GiulioRomualdi** [comment]
Today we tested the Yoga++ demo several time (left and right). We did not notice any kind of spikes. I think we can close this issue

**Comment by DanielePucci** [comment]
That's unfortunate, but clearly if we are not able to reproduce the issue, closing is the right move to do. Thanks @GiulioRomualdi and @kouroshD
