### ISSUE TITLE
Too frequent HW faults on head joints

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-support#75]
Gentlemen,

We have a long-lasting issue on the head of `Bluey`: the joints go in `HW Fault` very frequently, heavily bothering any kind of work with the robot (demos included).

Can we find a suitable time slot to seat around a table and discuss how to carry out **profitable investigations** and sort out this problem once for all?

/cc @vtikha @super-ste @randaz81 @alecive @julijenv @robotology/icub-support-admin ... and whoever may be involved

**Comment by pattacini** [comment]
@super-ste we're going to attend **IFI Day 3** on 22 Oct.
Will you be willing to discuss this with us during that session?

**Comment by super-ste** [comment]
Action Points from IFI:

- [ ] Get recent Logs
-  [ ] Check PWM limit in config file (we're piloting this 12V motors with 40V)
- [ ] Check Limit Current on Config File
- [ ] Check mech assy for stiction

**Comment by pattacini** [comment]
Any news on this? 
Yesterday I saw again `HW` occurring on `Bluey` and on _another robot_ too.

**Comment by super-ste** [comment]
Who can perform the checks stated above?
@randaz81 any Idea?
@julijenv can you and/or @spada1978 check for mechanical stiction (and maybe grease a bit) the HDs on the neck?

**Comment by pattacini** [comment]
I'd give priority to the _"math"_ required for reducing the PWM limit, apply them and then perform checks.

**Comment by julijenv** [comment]
It has been changed the PWM limit from 800 to 480 in the file .local/shareyarp/robots/iCubGenova04/hardware/mechanical/head-cfw2_can0-mec.xml
Let's see if it solves this sooooo long pending issue with the neck. If yes, we will add this change on the repository and github and other robots with V2 head..

**Comment by pattacini** [comment]
Thanks @julijenv :+1:

**Comment by julijenv** [comment]
If he head of bluey isnt making any other HW Fault we could hink of applying the change on all the other V2 head robot (especially in ours)
@super-ste , @pattacini , @randaz81 , @vtikha

**Comment by pattacini** [comment]
I believe we can go ahead with the proposed change, even if it won't be decisive; it's somehow a bug fix.

Please apply the fix into the repository, not locally.

**Comment by super-ste** [comment]
hi all,
has this been done? Can we close the Issue? And maybe #121 too?

**Comment by pattacini** [comment]
Hi @super-ste 
Unfortunately not yet: those faults are still very annoying.

However, I think @randaz81 is preparing a new special `FW` release to patch the way the temperature control is done.
