### ISSUE TITLE
Address conflict in 2FOC torso boards

### ISSUE THREAD

**Issue by ale-git** [robotology/icub-support#750]
### Description of the failure

La scheda sostituita nel torso ha gli indirizzi in conflitto con l'altra (ovvio: c'era il 50% di probabilità...) per cui bisogna scollegare un cavo can in modo da isolare una delle due schede 2FOC (non importa quale, va bene la più comoda da raggiungere) nel momento in cui si cambia l'indirizzo. Possiamo farlo nel primo pomeriggio?

**Comment by julijenv** [comment]
has been solved
