### ISSUE TITLE
Hands issues

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#76]
I spotted following issues with blue icub hands:
   - [x] Left hand - ring finger: tendon is too tensed and the finger is always folded.
   - [x] Left hand - ring finger: fingertip is not working
   - [ ] Left hand - fingers adduction/abduction : not calibrated properly and the motor is overheating
   - [x] Left hand - thumb finger: tactile fingertip not working
   - [ ] right hand - index: moves with saccades
   - [ ] right hand - thumb proximal: takes time before moving
   - [ ] right hand - thumb opposition: not calibrated properly (shows 20 degrees when it should be 0)
   - [ ] right hand - thumb opposition: doesn't move properly when joint position is 0 (shows as 20 because of the the calibration issue)
   - [ ] left elbow : the tendon jutting out of the elbow is going out to far and touches other parts when rotating the arm.

**Comment by bhigy** [comment]
Left hand - ring finger fingertip and left elbow tendon repaired thanks to @julijenv

**Comment by bhigy** [comment]
I tried to make rotations with the left forearm and the protruding tendon still touches other parts. This prevents the rotation from being performed smoothly.

**Comment by bhigy** [comment]
Thumb tactile fingertip of the left hand repaired.

**Comment by lornat75** [comment]
DO we still have the first issue:
tendon is too tensed and the finger is always folded

otherwise we could close this issue?

**Comment by lornat75** [comment]
@julijenv
