### ISSUE TITLE
Migration from iCubInterface to RobotInterface

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-support#77]
iCubLugano01 files need to upgraded from .ini format (iCubInterface) to xml format (robotInterface). Robot firmware needs to be updated too. Contact: @marijnfs

**Comment by marijnfs** [comment]
should I be able to simply run the update script as in http://wiki.icub.org/wiki/Firmware?

**Comment by marijnfs** [comment]
Hello, what are the most up-to-date documentations regarding these procedures? I can not find a clear new documentation for these new changes.

**Comment by randaz81** [comment]
Sorry Marijn, upgrading from iCubInterface to RobotInterface is something which cannot be done by a icub user, since it involves the complete reorganization of the robot configuration files. We already started the upgrade process: the old iCubLugano01 folder has been deleted, and the new template has been committed. The new xml files will be written by hand, so it will take few days of additional work.

**Comment by marijnfs** [comment]
Ok I see, thank you for the effort! I'll wait eagerly for the files;)

regards,
Marijn

**Comment by randaz81** [comment]
calibration files pushed to the repo

**Comment by randaz81** [comment]
New configuration files ok (tested remotely)
There's an issue on joint 10 of the left arm (thumb distal), the joint does not come back. @robotology/icub-support-admin @julijenv can you give a look?

**Comment by julijenv** [comment]
Hi @marijnfs ,
please let come on skypewith a webcam and we will try to understand the little issue you have with the joint 10 of the left arm:
our skype ID : icub.support
