### ISSUE TITLE
Eye-lids are not controlled, fall down and cover the cameras

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-support#771]
### Description of the failure

If the eye is controlled to tilt down and then back up, the eye-lids cover the eye and must be manually moved up again. 

### Detailed conditions and logs of the failure

There is currently no way to control the eye-lid motor in the yarpmotorgui, and I'm not sure if the motor control is exposed in some other place.

Currently the eye-lids have been removed as they cause problems doing the tracking demo.

**Comment by julijenv** [comment]
Hi @arrenglover ,
I will need to add some files in order to operate correctly the eyelids, I dont know though if the peculiarity of the control of this motor when the eye tilt down allow the motor to compensatethe movement of the eye.

**Comment by julijenv** [comment]
This shuld have been resolved by @marcoaccame .
