### ISSUE TITLE
Skin on torso, forearms and hands not working

### ISSUE THREAD

**Issue by arrenglover** [robotology/icub-support#772]
### Description of the failure

When loading the `Skin_Gui_All` application in yarpmanager and running/connecting everything, there is no visual output of the taxels on the torso, forearms and hands.

**Comment by julijenv** [comment]
Hi @arrenglover ,
I did my best yesterday night to make sure that the overall right arm is properly, the torso was already ok by changing the calibrator file and for the left arm;
- palm looks dead
- the lower part of the forearm skin doesnt get enough current so I will need to recrimp this part, that was btw working yesterday night ( :( )
