### ISSUE TITLE
Problem with the connection of  batteries to the robot backpack

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-support#779]
Yesterday during the walking experiment we face the problem that battries does not connect well to the robot backpack, so as result it fell down at a certain point while walking because of the power outage.

CC @MrAndrea  @maggia80

**Comment by maggia80** [comment]
@kouroshD could you please give more details about the failure. Did you see the button on the backpack becoming red or switched off?

**Comment by kouroshD** [comment]
If I am not wrong, it became switched off.  @GiulioRomualdi  @DanielePucci, correct me if I am wrong!

**Comment by DanielePucci** [comment]
The problem was similar to https://github.com/robotology/icub-support/issues/651, but with the real battery instead of the dummy. Although we opened the contacts of the battery (similarly to what we did [here](https://user-images.githubusercontent.com/7060968/39890070-f5fe694c-5499-11e8-9f53-94ad022d560a.jpg)) we connection between the battery and the electronics was not stable, and the robot shut down during walking

**Comment by DanielePucci** [comment]
As @MrAndrea was mentioning here https://github.com/robotology/icub-support/issues/651#issuecomment-414595143 it may be the time to re-think the connection between the battery and the robot

**Comment by maggia80** [comment]
yes, I agree. We need to do a redesign of the battery-pack (and of the dummy battery-pack). Candidates for replacing the springs are: http://www.coda-systems.co.uk/catalog/Swift_Dock.html

**Comment by DanielePucci** [comment]
We shall discuss about this relatively soon. We have some important demos by the end of the month and this issue is a little scaring

**Comment by maggia80** [comment]
I have checked the battery and there are some missing parts: 
   
![image](https://user-images.githubusercontent.com/6987330/54365776-cdd34500-466f-11e9-9937-4d0cfa903e8c.png)

We need to put them back.

**Comment by maggia80** [comment]
I requested them to Fabrizio.

**Comment by DanielePucci** [comment]
@maggia80 @MrAndrea 
Sorry for bothering, but I do not remember the status of this. We did a tapullo that allowed us to temporarily work, right? (demo corriere della sera in Genoa if I remember correctly)

**Comment by MrAndrea** [comment]
Thanks to Marcello S. we have new plastic parts and the battery which was fallen, is good again.
![image](https://user-images.githubusercontent.com/20459541/58034275-7dbca700-7b26-11e9-9c6c-ae52e88807d9.png)

Regarding the _tapullo_, we used 2 plastic screws:
![image](https://user-images.githubusercontent.com/20459541/58034293-8f05b380-7b26-11e9-9e83-e3ed12c8b198.png)

**Comment by kouroshD** [comment]
I check the icub-green workstation, I have seen only one battery and there is no plastic screws with the battery. I am not sure if that is the fixed battery! Where can I find the fixed battery?

@DanielePucci @MrAndrea

**Comment by MrAndrea** [comment]
@kouroshD the battery is still on my desk, you can come here and take it!

**Comment by kouroshD** [comment]
Thank you @MrAndrea .

**Comment by traversaro** [comment]
Hi @kouroshD , if the problem was fixed, can you comment also on https://github.com/robotology/icub-tech-support/issues/651 ? Thanks a lot!
