### ISSUE TITLE
Robot setup in view of CoDyCo Year 3 Review meeting @Darmstadt 

### ISSUE THREAD

**Issue by francesco-romano** [robotology/icub-support#78]
This issue clarifies the tasks that the Darmstadt guys must accomplish before our visit to their lab

cc @jeljaik @DanielePucci @robertocalandra

**Comment by DanielePucci** [comment]
As discussed with Jan, @robertocalandra  and  @AlexandrosParaschos should accomplish  the following tasks before @francesco-romano and @jeljaik leave for Darmstadt:

- [ ] Update the software of: firmware, yarp, icub-main, and codyco-superbuild; the update should be done one week before our visit;
- [ ] Do quantitative tests for kinematics measuring devices: check that all encoders, both on motor and joint side, work properly.  Also, check that the IMU respond reasonably;
- [ ] Do qualitative tests for dynamics measuring devices: check that all  force/torque sensors work reasonably;

**Comment by lornat75** [comment]
Please open individual issues for each problem, itemized multi-issues are difficult to track. Group issues with labels (we can create additional labels) to simplify searching.

**Comment by DanielePucci** [comment]
Ack. However, the above items are not issues, but tasks. So, I think we can keep this issue open to track tasks, and open individual issues for eventual HW or SW problems.

**Comment by robertocalandra** [comment]
Ok then we will just post links to the issues.

Please note: #25 still open

**Comment by marcoaccame** [comment]
About the software update ... 
@robertocalandra can you please also verify if you have the latest kernel w/ RT features?
I believe you already have because together with Rueckert Elmar in July we performed an update of the SW which works with RT kernel, but ...

you just need to digit (as explained in #87):

```
less /VERSION_PC104
```

**Comment by rueckert** [comment]
Hi, 

@marcoaccame our version is 5.0-15.03.31

**Comment by marcoaccame** [comment]
Ok, thanks.

you should update the live key to latest version, which is now 5.0-15.10.26 following instructions in http://wiki.icub.org/wiki/The_Linux_on_the_pc104

**Comment by DanielePucci** [comment]
Two weeks to go, tasks 2 and 3 shall be considered of highest importance.

**Comment by francesco-romano** [comment]
Any news?

**Comment by robertocalandra** [comment]
Kernel updated to 5.0-15.11.02. However, after updating also the firmware and the repositories, the robotInterface fail during initialization as detailed in #108

**Comment by DanielePucci** [comment]
What about the tasks 2 and 3?

**Comment by paraschos** [comment]
The tasks 2 and 3 were completed as accurately as their description.

**Comment by DanielePucci** [comment]
Thanks.
