### ISSUE TITLE
Green icub right thumb oppose cable broken

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-support#780]
### Description of the failure

Green icub left thumb oppose cable is broken during retargeting experiments

![photo_2019-02-28_19-48-54](https://user-images.githubusercontent.com/6505998/53590521-39a6af80-3b92-11e9-86cf-c1ccce15c3c1.jpg)

**Comment by julijenv** [comment]
it has been repaired.
IITCODE Qta DEscription
1815 x 1m: carlstal cable 0.63mm uncoated
