### ISSUE TITLE
Left shoulder and left thumb proximal cable broken

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-support#782]
### Description of the failure

Green icub left shoulder cable and possibly left thumb proximal cable is broken while doing the whole body retargeting experiments

![photo_2019-03-05_12-20-04](https://user-images.githubusercontent.com/6505998/53802131-513eb900-3f41-11e9-97b4-ab5747672ded.jpg)

![photo_2019-03-05_12-20-04 2](https://user-images.githubusercontent.com/6505998/53802137-5439a980-3f41-11e9-965b-4766199b5894.jpg)

**Comment by julijenv** [comment]
it has been settled by replacing cable N8 broken and rewiring the joint 9 of the left arm

IITCODE Qta DEscription
4765 x 1 : shoulder rotation cable N8
1815 x 1m : carlstahl 0.63mm diametre uncoated
