### ISSUE TITLE
Left shoulder cable broken

### ISSUE THREAD

**Issue by kouroshD** [robotology/icub-support#783]
Description of the failure:
Green icub left shoulder cable is broken while doing the whole body retargeting experiments
![photo6050859349942841361](https://user-images.githubusercontent.com/17707730/53836264-d5b82880-3f8f-11e9-8939-6ca85f0cb29f.jpg)
![photo6050859349942841362](https://user-images.githubusercontent.com/17707730/53836265-d5b82880-3f8f-11e9-80fc-3ea5ee4f2de0.jpg)
![temp1](https://user-images.githubusercontent.com/17707730/53836270-db157300-3f8f-11e9-9c74-da8e4f06512e.jpg)

**Comment by julijenv** [comment]
I was advertised that the limit where not respected so as a matter of act the brand new cable shoulder N8 just got snapped again in the same way as faillure #782 .
@kouroshD , told me it should have this time make sure that the constraint limit for not snapping the cable has been restored.
To make the repair I used the following item
IITCODE Qta DEscription
4765 x 1 : shoulder rotation cable N8
