### ISSUE TITLE
Right arm shoulder cable broken 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-support#790]
During a walking experiment, a cable of the right shoulder was broken

cc @julijenv

**Comment by julijenv** [comment]
Hi @GiulioRomualdi ,
it has been replaced the broken cable N8
IITCODE Qta Description
4765 x 1 : shoulder rotation cable 8

**Comment by GiulioRomualdi** [comment]
Thank @julijenv!
