### ISSUE TITLE
Shoulder tendon is loose

### ISSUE THREAD

**Issue by tasbolat1** [robotology/icub-support#791]
### Description of the failure
After having experiment involving right arm, the right arm becomes shaky in some configurations. I also noticed that the one of the tendon is loose. How can make it tight again?

This is a picture where I can see that the tendon is loose.

![IMG_6528](https://user-images.githubusercontent.com/4617666/54429750-58916e00-475c-11e9-8e94-03c86a1fb1d9.jpg)

### Detailed conditions and logs of the failure
There is no error or hardware failure in the log file.

**Comment by julijenv** [comment]
Hi @tasbolat1 ,
if you go to the icub wikipage [Tendons_and_replacement](http://wiki.icub.org/wiki/Tendons_and_replacement) and download the document ShoulderWiring you will be able to see that this cable is shoudler cable number 6 which is antagonist with 5 and to tighten it you need to tighten both 5 and 6 tensionner you can find on this picture
![image](https://user-images.githubusercontent.com/7140395/54433999-84e1c600-472d-11e9-804d-ad5727fcb408.png)
Let me know,

**Comment by tasbolat1** [comment]
Hi @julijenv,
I have managed to tighten the tendons. So far seems good. Yet need to see the results in the real experiments. Thanks a lot.
