### ISSUE TITLE
Left pinkie finger not moving

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-support#796]
### Description of the failure
The left pinkie finger does not move, while the ring finger has a wrong zero position. Probably it broke during transportation after Corriere Innovazione demo.

### Detailed conditions and logs of the failure
![image](https://user-images.githubusercontent.com/18591940/55147376-8e642880-5146-11e9-9fba-a2d7e047a2d5.png)

cc @julijenv

**Comment by julijenv** [comment]
I check this morning and the last joint cable is broken, to be replaced.

**Comment by julijenv** [comment]
it has been repaired by using
IITCODE Qta DEscription
2391 x 0.5m : carlstahl 0.45-0.61mm ocated
