### ISSUE TITLE
Turning off in the moment I switch on motors

### ISSUE THREAD

**Issue by TheCamusean** [robotology/icub-support#804]
### Description of the failure

Hello again @julijenv , this has been fast.

Right now, we are facing a strange hardware problem. The steps we are following are these:

1. Turn on the power supplies. Before turning on pc and motor switches they look like the photo I shared you via mail.
2. I turn on the switch of the pc and everything works. I can even ping the pc104.
3. Turn on the switch of the motors. Then, something goes wrong and power suppliers stops proving voltage.

How should we procedure?

Best wishes

**Comment by julijenv** [comment]
Hi @TheCamusean ,
but by your quotation
> Then something goes wrong

What do u mean? Did u launch the robot?
From the picture you sent me the second power supply went in protection. So there was a short circuit somewhere.
Please find me on skype.

**Comment by TheCamusean** [comment]
Our iCub's head looks as follows:

![IMG_20190408_114604_508](https://user-images.githubusercontent.com/19637265/55718623-6f924b80-59fc-11e9-879d-1e58453f4e68.jpg)
![IMG_20190408_114641_067](https://user-images.githubusercontent.com/19637265/55718624-702ae200-59fc-11e9-8ed1-a16646970b5f.jpg)
![IMG_20190408_114657_122](https://user-images.githubusercontent.com/19637265/55718625-702ae200-59fc-11e9-8fe9-101fccff5b9e.jpg)
![IMG_20190408_114702_627](https://user-images.githubusercontent.com/19637265/55718626-702ae200-59fc-11e9-81af-703eaf90512f.jpg)
![IMG_20190408_114715_477](https://user-images.githubusercontent.com/19637265/55718627-702ae200-59fc-11e9-97c4-96041c8eb0eb.jpg)
![IMG_20190408_114722_427](https://user-images.githubusercontent.com/19637265/55718628-702ae200-59fc-11e9-99a3-335b4b297c95.jpg)
![IMG_20190408_114750_680](https://user-images.githubusercontent.com/19637265/55718629-70c37880-59fc-11e9-9634-07f725be5c3b.jpg)
![IMG_20190408_114809_971](https://user-images.githubusercontent.com/19637265/55718631-70c37880-59fc-11e9-9fa4-1ae111a73cd3.jpg)

**Comment by TheCamusean** [comment]
Better view from sides: 
![IMG_20190408_115625_013](https://user-images.githubusercontent.com/19637265/55718767-d9aaf080-59fc-11e9-95af-214ff3a7832e.jpg)

![IMG_20190408_115654_671](https://user-images.githubusercontent.com/19637265/55718743-c3049980-59fc-11e9-9fc7-6588fa40bf88.jpg)

**Comment by julijenv** [comment]
hi @TheCamusean ,
did you succeed to remount everything and is everything working again?!??!
let me know

**Comment by TheCamusean** [comment]
Hello @julijenv,

Everything smooth and fine.

Thanks alot :dancer:
