### ISSUE TITLE
Left shoulder and wrist cable broken

### ISSUE THREAD

**Issue by gabrielenava** [robotology/icub-support#807]
After a failed balancing experiment, the left shoulder cable broke again. This time also the left wrist cable got broken.

**Comment by julijenv** [comment]
It has been taken in the warehouse the following list of items to repair the left arm broken
IITCODE Qta description
4761.1 x 1 : Shoulder rotation cable 4
4764.1 x 1 : Shoulder rotation cable 7
2391 x 1m : carlstahl cable 0.45-0.61mm coated
