### ISSUE TITLE
left shoulder broken calbes

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#810]
Ciao @julijenv, 

The cables 3, 4, 5 and 6 of the left shoulder are broken - you can check the photo below:

![IMG_20190412_095438](https://user-images.githubusercontent.com/11769446/56028281-18e88280-5d18-11e9-964b-d45b693bc5e5.jpg)

Thanks, 
Alex.

**Comment by julijenv** [comment]
it has been repaired using the following list of items

IITCODE Qta Description
4760.1 x 1 : shoulder cable N3
4761.1 x 1 : shoulder cable N4
4763.1 x 1 : shoulder cable N6
1895 x 2 : LEFT PULLEY CRIMP
