### ISSUE TITLE
iCubErzelli03: grinding noise from the eyes

### ISSUE THREAD

**Issue by ddetommaso** [robotology/icub-support#812]
The robot doesn't have any mechanical failure but a grinding noise is produced during the calibration of the robot, specifically when the eyes move to the limit position.

**Comment by julijenv** [comment]
looks like the metallic frame of the eye is touching the nylon 
![image](https://user-images.githubusercontent.com/7140395/56976014-49cb1300-6b72-11e9-93c9-95f54451e9cc.png)
![image](https://user-images.githubusercontent.com/7140395/56976186-aa5a5000-6b72-11e9-9e58-d69379257747.png)
from CAD there is no need of putting some tiny washer to prevent that. So I guess that the screw was excessively tensed.
