### ISSUE TITLE
Problem with right hand during calibration

### ISSUE THREAD

**Issue by marco-monforte** [robotology/icub-support#813]
### Description of the failure

The right hand goes up and pushes toward the joint limit, touching  the forearm.

### Detailed conditions and logs of the failure

During the calibration procedure when turning on the yarprobotinterface, the right hand wrist moves up reaching the joint limit and pushing against the forearm.

![20190415_160958](https://user-images.githubusercontent.com/32684998/56139861-ffef0400-5f99-11e9-937f-c51d6c123f3d.jpg)

**Comment by julijenv** [comment]
recalibrated
