### ISSUE TITLE
Right shoulder cable broken

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-support#814]
### Description of the failure

While starting `yarprobotinterface` with [icub_all.xml](https://github.com/robotology/robots-configuration/blob/master/iCubGenova01/icub_all.xml) configuration file, the right shoulder went into a weird configuration and the shoulder cable is broken.

CC @gabrielenava

**Comment by julijenv** [comment]
the cable 8 has been replaced.
IITCODE Qta DEscription
4765.2 x 1: shouldler cable 8
