### ISSUE TITLE
Cannot connect to pc104 from the server switch

### ISSUE THREAD

**Issue by GiuliaDAngelo** [robotology/icub-support#815]
### Description of the failure
Cannot connect to pc104 using an ethernet cable from the server switch to the backpack.
If we connect directly using the VGA port on the head we are able to log in. 

### Detailed conditions and logs of the failure
When turning on the robot, the communication between the server and the pc104 doesn't hold. 
The light on the switch blinks for a few seconds and then it goes off. 
We also tried using another ethernet cable instead of the one attached to the power supply cable. 
By using the VGA cable inside the head we are able to log in using an external monitor and the keyboard, hence the pc104 is still working. Furthermore, the problem should be related to the communication between the backpack and the ethernet port and the connectors in the head. 
It could be the COM Express board or a weakly plugged cable. 

Attached you can find a video of the COM Express board and a picture of the screen when logging in from the head port. 

![IMG_9192](https://user-images.githubusercontent.com/24890035/56597984-e0885480-65f3-11e9-8adc-0365080ce29e.JPG)

**LINK to the video:**   [HERE](https://www.dropbox.com/s/mdlcutd8nx4t7p3/COMExpress.MOV?dl=0)

**Comment by julijenv** [comment]
problem with the network reconfiguration after the last experiment of robot cooperation
