### ISSUE TITLE
Loose mechanical coupling of right arm shoulder joints 

### ISSUE THREAD

**Issue by Yeshasvitvs** [robotology/icub-support#816]
### Description of the failure

We noticed that the right shoulder joints mechanical coupling is loose. We had a lot of broken cables on this shoulder previously and this loose mechanical coupling could be a possible reason.

![ezgif com-resize](https://user-images.githubusercontent.com/6505998/56681292-4eeb1680-66c9-11e9-8771-924a976a3fea.gif)

CC @DanielePucci @kouroshD @lrapetti

**Comment by julijenv** [comment]
Hi @Yeshasvitvs ,
I checked the tension of all cables and effectively some of the inside part where looses. I retightened everything I could posibility find. Let me kow if it is better ths way.

**Comment by julijenv** [comment]
any news? @Yeshasvitvs ?!?

**Comment by Yeshasvitvs** [comment]
During the pHRI experiments yesterday we did not notice any problems. I can be more conclusive after doing retargeting experiments.

**Comment by GiulioRomualdi** [comment]
Today we noticed that the problem is still there. Furthermore, as @julijenv noticed last week, this is caused by a joint of the torso.

**Comment by Yeshasvitvs** [comment]
As discussed with @julijenv this issue was not observed in the last test we did for pHRI.
@julijenv will make sure to double check the tension in the cables when mounting the robot parts back. So closing this issue.
