### ISSUE TITLE
CAN errors

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#817]
Hi @julijenv, 

The CAN 7 (left arm skin) is not powered up, some of the cable connections may be broken. However, after commenting the skin, we discovered we have other problems, for example, the sharedcan[0] gives an error as well. 

The CAN lights of the back of the neck (bottom part of the head) try to light up but then they turn off. 

Cheers, 
Alex.

**Comment by julijenv** [comment]
Until now it seems that something is wrong at the level of config files. We were able to launch with no errors the robot commenting the MTB_inertial lines.
So far the robot is okay

**Comment by amaroyo** [comment]
I will close this one as it seems fixed.
