### ISSUE TITLE
Left hand index proximal tendon broken

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#82]
As the title says, the index proximal tendon of the left hand just broke.

**Comment by bhigy** [comment]
Repaired this morning but it broke again this afternoon after only a movements.

**Comment by julijenv** [comment]
repaired again. let see what's going wrong this time, hopefully it isnt due to the grasp or else u will need to find a way to apply less force on the object you take or pay atteention of the hardness of the object seize.
