### ISSUE TITLE
Left hand fingertip skin unresponsive

### ISSUE THREAD

**Issue by fbottarel** [robotology/icub-support#822]
### Description of the failure
Index fingertip skin on the left hand is not working. SkinGui shows no contact. Moreover, the fingernail PCB of the index finger is bent out of shape and one of the wires has detached. 

![image](https://user-images.githubusercontent.com/33027628/57681806-b513eb00-7630-11e9-96de-378c556a3249.png)

**Comment by julijenv** [comment]
Hi @fbottarel ,
I sent a mail to Fabrizio to send someone to resolder this cable.
cheers

**Comment by julijenv** [comment]
Hi @fbottarel ,
I hope you do know that I am away from genova until the 26th of June, So please go directly in my lab to get someone to take of that little problem which require a physical interaction.
thx in advnace

**Comment by fbottarel** [comment]
Ok, tnx @julijenv!

**Comment by julijenv** [comment]
@fbottarel , from my colleague I heard they resoldered the wire, could you please if it works and give feedback to them in the production area, thx in advance

**Comment by fbottarel** [comment]
It works as intended, thank you guys as always!
