### ISSUE TITLE
Right hip yaw encoder not working!

### ISSUE THREAD

**Issue by MiladShafiee** [robotology/icub-support#829]
### Description of the failure
During the demo today for video recording the robot failed suddenly during walking and the encoder of the hip yaw of the right foot is broken!

### Detailed conditions and logs of the failure
The right hip yaw encoder doesn't work!

**Comment by fjandrad** [comment]
As a part of this, we also observed that the other joints in the ems ( hip roll, hip pitch, knee ) of the right leg are not stiff enough.

**Comment by fjandrad** [comment]
This has been addressed if I'm not mistaken.
