### ISSUE TITLE
Right arm encoder not working

### ISSUE THREAD

**Issue by Giulero** [robotology/icub-support#832]
### Description of the failure
If we launch the `yarprobotinterface` the error reported in the next section appears and it is not able to complete the calibration of the right arm. We've tried to open the cover on the arm and we notice that some wires close to the elbow are not soldered.

![photo_2019-06-19_19-09-14](https://user-images.githubusercontent.com/29798643/59786264-26495c80-92c7-11e9-9839-61691d93df60.jpg)

### Detailed conditions and logs of the failure
`
[ERROR] from BOARD 10.0.1.3 (right_arm-eb3-j0_3), src LOCAL, adr 0, time 147s 681m 454u: (code 0x05000016, par16 0x4008 par64 0xffffffffffff1000) -> CFG: EOtheEncodeerReader cannot be configured: verification fails. p16&0xf000: number of joint; primary encs: failure mask in p16&0x000f and errorcodes in p64&0x0000ffff; secondary encs: failure mask in p16&0x00f0 and errorcodes in p64&0xffff0000 + .
`
cc @FabioBergonti

**Comment by julijenv** [comment]
It has been performed a resoldering of the 2 wires broken  by emiliano.
