### ISSUE TITLE
Failed right_arm BOARD connection while running yarprobotinterface

### ISSUE THREAD

**Issue by GiuliaDAngelo** [robotology/icub-support#835]
### Description of the failure
I found the yarprobotinterface not working today after @VenusPasandi experiments. 
The yarprobotinterface fails to run reporting a problem related to the right arm. 

### Detailed conditions and logs of the failure
The problem is related to the right arm BOARD and a missing eobrd_mais, as written on the yarplogger below. 

![iCubPurpleIssue](https://user-images.githubusercontent.com/24890035/60534410-10458e00-9d02-11e9-8068-b3dc1c20e555.png)

Detailed error message: 
![detailed](https://user-images.githubusercontent.com/24890035/60535440-69162600-9d04-11e9-8a98-00a7798ee229.png)

I already tried:
* Rebooting the robot but did not solve the issue.
* Pinging the board server (BOARD 10.0.1.4) successfully. 
* Launched the yarprobotinterface from the GUI and from the terminal.
 
We are now running the yarprobotinterface removing all the robot parts from the configuration file except the head and the face.

**Comment by VenusPasandi** [comment]
Just to know, I worked with the robot while using all the joints without any issue. I had hardware faults in the fingers but nothing else!
By the way, this morning @GiuliaDAngelo tested the robot again and it worked fine without any error. I mean, the yarprobotinterface run without error and the right arm moved nicely by using yarpmotorgui. So, I think we can close this issue.

**Comment by GiuliaDAngelo** [comment]
Thanks @VenusPasandi !
