### ISSUE TITLE
Right thumb proximal tendon snapped

### ISSUE THREAD

**Issue by fbottarel** [robotology/icub-support#837]
### Description of the failure
The right thumb proximal tendon snapped during grasping experiments. 

### Detailed conditions and logs of the failure
![image](https://user-images.githubusercontent.com/33027628/60803429-7bb4b300-a17b-11e9-8262-89e9e6f19272.png)

**Comment by julijenv** [comment]
Hi @fbottarel ,
it has been replaced the proximal joint as well as the distal joint of the thumb of the right arm.
pieces needed to restored it:
IITCODE Qta Description
1815 x 1m: cavo carlstahl 0.63mm
2391 x 0.5m : carstahl cable 0.45-0.61
