### ISSUE TITLE
broken cables in both arms

### ISSUE THREAD

**Issue by amaroyo** [robotology/icub-support#849]
@julijenv, 

**S**o, we **h**ave th**e** right hand - pinky cab**l**e broken (joint 15), and the le**f**t hand finger (joint 7) broken as well. Or the other way around... I don't remember which one was the right one xD 

Thanks,
Alex.

**Comment by amaroyo** [comment]
thanks @julijenv !

**Comment by julijenv** [comment]
it has been repaired by the use of the following items:
IITCODE Qta Descitpion
2391 x 1m: carlstahl 0.61mm (core 0.45)
1815x1m:carlastahl uncoated 0.63mm
