### ISSUE TITLE
Weird HW fault

### ISSUE THREAD

**Issue by hu-yue** [robotology/icub-support#90]
Hi, there has been a hw fault with the following error:

```
from BOARD 6, src CAN1, adr 2, time 286s 512m 505u: (code 0x02000002, par16 0x0001 par64 0x0000000100020000) -> MC: 2FOC i2t limit exceeded + INFO = NO MORE
```

```
from BOARD 6, src LOCAL, adr 0, time 284s 770m 577u: (code 0x0200000c, par16 0x0001 par64 0x0000000100020000) -> MC: generic motor error (see 64 bit mask parameter) + INFO = NO MORE
```

```
Unable to set the control mode of board 6 joint 1 in HW_FAULT
```

The error occurred during single foot torque balancing on the left leg.
The joint in hw fault is left hip roll.

cc @DanielePucci @barbalberto

**Comment by marcoaccame** [comment]
@ale-git : can you comment?

**Comment by DanielePucci** [comment]
@hu-yue, did you see the problem also on two-feet balancing?

**Comment by hu-yue** [comment]
I forgot this other error, which comes also before the hw fault:

```
from BOARD 6, src CAN1, adr 2, time 286s 512m 505u: (code 0x02000002, par16 0x0001 par64 0x0000000100020000) -> MC: 2FOC i2t limit exceeded + INFO = NO MORE
```

**Comment by hu-yue** [comment]
@DanielePucci no I did not try, I can try now

**Comment by DanielePucci** [comment]
Yes, thanks :) @hu-yue

**Comment by hu-yue** [comment]
On two feet it did not happen. I tried my best to push he robot in all directions and the only thing happened is that the torso roll had torque saturation.

**Comment by hu-yue** [comment]
I just tried the balancing on right leg, and also the right hip roll went in hw fault.
These the errors:
```
from BOARD 8, src CAN1, adr 2, time 442s 171m 507u: (code 0x02000002, par16 0x0001 par64 0x0000000100020000) -> MC: 2FOC i2t limit exceeded + INFO = NO MORE

from BOARD 8, src LOCAL, adr 0, time 442s 171m 586u: (code 0x0200000c, par16 0x0001 par64 0x0000000100020000) -> MC: generic motor error (see 64 bit mask parameter) + INFO = NO MORE
```
@DanielePucci

**Comment by DanielePucci** [comment]
Well, waiting for @marcoaccame @ale-git opinions.

**Comment by DanielePucci** [comment]
@randaz81

**Comment by ale-git** [comment]
Maybe the I2T limit is too conservative for this task. I've to discuss a little bit with @randaz81 about this issue, then we'll probably able to increase the I2T limit.

**Comment by DanielePucci** [comment]
So, @ale-git tell us when you are done, so @hu-yue can update the software and check.

**Comment by hu-yue** [comment]
Hi @ale-git any update about this issue?

**Comment by ale-git** [comment]
@hu-yue we're working on a more precise management of motor current limits in the next releases of the firmware... in the meanwhile, plese try to increase the Currents parameter in this section of 
hardware/motorControl/left_upper_leg-ems6-mc.xml
hardware/motorControl/right_upper_leg-ems8-mc.xml
Please make also sure to increase it by small steps (about 500) and don't grow too much (stay below 8000). I hope this momentary workaround will fix the problem.

    <group name="LIMITS">
        <param name="Max">              85            70            70          0       </param>
        <param name="Min">             -30           -15           -70         -100     </param>
        <param name="Currents">         5000          5000          5000        5000    </param>
    </group>

**Comment by hu-yue** [comment]
@ale-git thanks, for the moment I changed the limit of the ```hip_roll``` joint to ```6500``` and the robot is not going into hw fault anymore.
I will update the firmware for the next release then and keep these changes in my local files.
