### ISSUE TITLE
push button of motors power is broken

### ISSUE THREAD

**Issue by marcoaccame** [robotology/icub-support#93]
the push button is broken and the user needs a stylus, a pen or a screwdriver to power motors on/off.
i have taken possess of the broken part so that it does not get lost.

the repair is mildly urgent because @DanielePucci needs the robot for heavy tests before external demo of end november.

**Comment by DanielePucci** [comment]
Thanks @marcoaccame for noticing the issue. Actually, the power on button is pretty important :D

**Comment by DanielePucci** [comment]
Guys, can we fix this ASAP?

**Comment by DanielePucci** [comment]
@julijenv @super-ste

**Comment by super-ste** [comment]
Done thanks to Marcello Savoldi

![a30ad6a3-c148-45ea-8440-104b47dfc9ee](https://cloud.githubusercontent.com/assets/8122012/11445384/f0f0fcd8-952b-11e5-92db-a83be4284865.jpg)

**Comment by DanielePucci** [comment]
Very nice job. Thank you very much guys.
