### ISSUE TITLE
Fingers tendons broken

### ISSUE THREAD

**Issue by bhigy** [robotology/icub-support#94]
Left hand - middle finger proximal tendon is broken
Right hand - pinky and little finger is broken too

**Comment by spada1978** [comment]
if you could get your hands in the morning we can repair

**Comment by bhigy** [comment]
Right hand repaired thanks to @spada1978. Unfortunately I have to say that the fix didn't last long. The same tendon broke again after a few grasps.

I will need the hand for my experiment tomorrow morning so please don't touch it until then.

Thanks !

**Comment by super-ste** [comment]
@bhigy 
Please let us know when we can get the hand for repair.

**Comment by julijenv** [comment]
Left hand medium proximal joint restored.

**Comment by spada1978** [comment]
It was repaired the last joint of the right hand , and replace the cable sheaths of the passage of wiring
