### ISSUE TITLE
Problems in updating linux icub-live 5 on pc104

### ISSUE THREAD

**Issue by urielmtz** [robotology/icub-support#96]
Hello,

We tried the .iso image using Debian and we have the output shown in the attached picture. We are following the steps as indicated in the wiki page but I am wondering if we are missing something else?.
Thanks.

![debian_icub_script_error](https://cloud.githubusercontent.com/assets/4717988/10843178/49d5c4b2-7eef-11e5-9e01-6aaacc6efd7e.png)

Kind regards
Uriel

**Comment by marcoaccame** [comment]
hi @mbrunettini have you got any idea about what has happened? ;-).

**Comment by mbrunettini** [comment]
As described in the [wiki](http://wiki.icub.org/wiki/The_Linux_on_the_pc104#How_to_use_the_icub_iso2usb.sh_script) **you MUST use a device NOT a partition**
In the above picture is clear that A PARTITION (sdb1) has been used.
Moreover, before issuing the command be sure to use the correct device correponing to the USB device you want to write you: if you use the wrong device, you may destroy the filesystem on the PC you are using.

**Comment by urielmtz** [comment]
Thanks, I replace sdb1 by sdb and the script created in the usb key the live and persistence partitions. Live partition contains the operating system and the persistence partition contains a persistence.conf file.

I put back the usb key inside the iCub head but pc104 isn't replying to the ping.

Cheers
Uriel

**Comment by mbrunettini** [comment]
Which address are you trying to ping?

**Comment by urielmtz** [comment]
I am doing ping 10.0.0.2 and also ping pc104

**Comment by mbrunettini** [comment]
The first is correct, the second is correct only if you have an entry on the DNS.
You should connect a monitor to the PC104 to see what's wrong.

**Comment by mbrunettini** [comment]
Issue resolved by using the icub_iso2usb.sh script with the supported linux distro.
