### ISSUE TITLE
Weight of iCub V3

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-support#98]
This issue is intended for collecting information on the weight of iCub V3. 

@Spada1978 @super-ste @Mick3Lozzo @traversaro @iron76 @francesco-romano @fiorisi

**Comment by DanielePucci** [comment]
Waist components.
![20151103_092348](https://cloud.githubusercontent.com/assets/5045846/10933286/c687fe76-82d7-11e5-90e8-a4c093a2cbbd.jpg)
![20151103_092354](https://cloud.githubusercontent.com/assets/5045846/10933287/c6b38da2-82d7-11e5-975d-ab351e24c141.jpg)
![20151103_092400](https://cloud.githubusercontent.com/assets/5045846/10933288/c6b77dd6-82d7-11e5-9248-8112fe0e3126.jpg)

**Comment by DanielePucci** [comment]
Upper body.
![20151103_091652](https://cloud.githubusercontent.com/assets/5045846/10933319/eea09198-82d7-11e5-8d51-1d41669badb2.jpg)
![20151103_091719](https://cloud.githubusercontent.com/assets/5045846/10933320/eece5f60-82d7-11e5-9d47-86a8ccbb70d2.jpg)
![20151103_091729](https://cloud.githubusercontent.com/assets/5045846/10933321/eed22b2c-82d7-11e5-8723-c07f0e04d44a.jpg)

**Comment by spada1978** [comment]
Left/Right arm
![20151118_092119](https://cloud.githubusercontent.com/assets/14175004/11236291/ba4620d2-8dd8-11e5-9c87-18635bb031cc.jpg)
![20151118_092054](https://cloud.githubusercontent.com/assets/14175004/11236305/ddc510b8-8dd8-11e5-88e1-4615db35c2e2.jpg)

**Comment by spada1978** [comment]
Tlkn Head with cover
Kg 2,69

![20151120_100333](https://cloud.githubusercontent.com/assets/14175004/11301571/82ea3242-8f98-11e5-952a-3d867b6fb69e.jpg)

**Comment by spada1978** [comment]
Tlkn Head without cover
Kg 2,32

![20151120_100459](https://cloud.githubusercontent.com/assets/14175004/11301597/b0ed1a9c-8f98-11e5-890c-0bbf2f120efc.jpg)

**Comment by DanielePucci** [comment]
I just wanted to mark somewhere that @spada1978 sacrificed a finger for this issue.

**Comment by spada1978** [comment]
It is for a good cause no problem

**Comment by spada1978** [comment]
Upper body + wiast without battery
Kg 16,05 
photo incoming

**Comment by spada1978** [comment]
buttocks
Kg 1,36
![20160217_092849](https://cloud.githubusercontent.com/assets/14175004/13106472/bded1704-d568-11e5-954e-310c379eeeed.jpg)

**Comment by spada1978** [comment]
hip
Kg 2,96

![20160217_093423](https://cloud.githubusercontent.com/assets/14175004/13106502/e7377744-d568-11e5-9831-3950f5906b04.jpg)

**Comment by spada1978** [comment]
Shoulder - arm - forearm - hand
Kg 3,60
![20160218_145244](https://cloud.githubusercontent.com/assets/14175004/13146421/ee121b26-d655-11e5-9594-1b5158607385.jpg)

**Comment by spada1978** [comment]
Lowerlag
Kg 4,45
![20160302_143949](https://cloud.githubusercontent.com/assets/14175004/13633603/62c1f1d6-e5f0-11e5-94e1-54e5aad4bd73.jpg)

**Comment by spada1978** [comment]
Lowerlag + Knee
Kg 5
![20160302_144955](https://cloud.githubusercontent.com/assets/14175004/13633657/b7e0e992-e5f0-11e5-8a4c-ee09ed1b96e7.jpg)

**Comment by fjandrad** [comment]
![photo_2018-08-29_10-37-31](https://user-images.githubusercontent.com/11043189/44776099-8ecc1f00-ab77-11e8-8587-20e7a3a79ffa.jpg)

iCubGenova04 on the scale. 
**Total weight = 33.33kg**
@DanielePucci

**Comment by DanielePucci** [comment]
@fjandrad 
I do not understand why the [comment above](https://github.com/robotology/icub-support/issues/98#issuecomment-416872933) has been put in the present issue. Please notice that [the present issue](https://github.com/robotology/icub-support/issues/98#issue-114999396) is concerned about the weight of only iCub V3, or as we call it iCub3. So, I strongly suggest to remove the comment above, and update the table https://github.com/robotology/QA/issues/61#issue-110842856 to keep trace of iCubGenova04 weight.
