### ISSUE TITLE
Mechanical adjustment of eyes needed

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-support#99]
Hi @super-ste and @julijenv,

we found that our eyes are misaligned, i.e. one eye is tilted a little further up than the other. This causes some trouble when using the stereo vision pipeline using the higher resolution of the camera. The misalignment is more than a few pixels, so I guess we need the mechanically adjust it.

Is there any documentation on how to do it around? If not, would it be possible for you to remotely help us out via Skype?

Thanks a lot,
Tobias

PS: We will host an integration meeting at the end of the month, and it would be great if we could sort this out before then :).

/cc @maxime-petit @martz21 @hjchang

**Comment by julijenv** [comment]
Hi all- iCubLondon01 users ( @Tobias-Fischer , @maxime-petit , @martz21 , @hjchang )
I'll be on skype to give you an han.  Is it a recent problem or a brand new one, I mean since when you hace tis issue with theyes? what is alright at the beginning and by the use of it you got this offset, or you just for the first time use the stereo vision and realize there was a misalignemnt?
Let me know

**Comment by Tobias-Fischer** [comment]
Hi @julijenv,
Thanks for getting in touch with us so quickly. Just to keep this issue up-to-date: The misalignment is 20px. We have had the misalignment for while now, but it just recently started giving us issues. Foreseeing the integration meeting, we would like to have the robot working perfectly, and this is the only remaining issue which needs to be tackled.

Thanks,
Tobi

**Comment by Tobias-Fischer** [comment]
Here are the requested images of the eyes. The first image shows both eyes, the second one the right eye, and the last one the left eye of the iCub.

![img_20151104_145657](https://cloud.githubusercontent.com/assets/5497832/10941797/ee9950ea-8304-11e5-8797-11abc5ea2611.jpg)
![img_20151104_145714](https://cloud.githubusercontent.com/assets/5497832/10941799/ee9a49be-8304-11e5-9626-a700db078fba.jpg)
![img_20151104_145720](https://cloud.githubusercontent.com/assets/5497832/10941798/ee99b7f6-8304-11e5-96d9-e8d3033fd171.jpg)

**Comment by Tobias-Fischer** [comment]
Some more images with a ruler.

![img_20151104_150920](https://cloud.githubusercontent.com/assets/5497832/10942072/46d2883e-8306-11e5-8d1c-4189d7fa12b7.jpg)
![img_20151104_150944](https://cloud.githubusercontent.com/assets/5497832/10942075/46e956e0-8306-11e5-8ef5-f669015cf1bb.jpg)
![img_20151104_150950](https://cloud.githubusercontent.com/assets/5497832/10942074/46e8d65c-8306-11e5-90a6-33d14e00f37f.jpg)
![img_20151104_151017](https://cloud.githubusercontent.com/assets/5497832/10942073/46e804ca-8306-11e5-9a47-e2cddd86abe4.jpg)
![img_20151104_151022](https://cloud.githubusercontent.com/assets/5497832/10942076/46eafe8c-8306-11e5-925c-b398e7eb3a0a.jpg)

**Comment by Tobias-Fischer** [comment]
Hi @julijenv, thanks again for your help yesterday. The alignment now is much better, thanks a lot. If we run into trouble again, we'll let you know, but I think the couple of pixels misalignment still left shouldn't be a big deal.

Thanks,
Tobi and @maxime-petit
